### ISSUE TITLE
Object related to itself does not seem to work

### ISSUE THREAD

**Issue by mkdjns** [SFDO-Community/declarative-lookup-rollup-summaries#10]
Attempting to add a Rollup Summary where the same object os on both sides of the relationship doesn't seem to work. For example, the rollup in this screenshot does not update the Parent Account when modifying the Child Account

![screen shot 2014-01-21 at 8 02 38 am](https://f.cloud.github.com/assets/884516/1965047/8749c646-82b5-11e3-91fd-28c1d93a8c5f.PNG)

**Comment by kvonachen** [comment]
Andrew - I'm working on a rollup that is working in the normal sense of parent child objects.  But my parent object is Accounts and my record has a Parent Account.  How come the rollup isn't calculating the total sum of child records (across all the child accounts) on the Parent record?  does this functionality work?  I JUST installed the tool today on the org so it's the latest and greatest version!  Please advise.

**Comment by afawcett** [comment]
Have you seen [this](http://andyinthecloud.com/2014/05/08/account-hierarchy-rollups-clicksnotcode/)?
