### ISSUE TITLE
Process Builder unable to update a record because of a dlrs_AccountTrigger error

### ISSUE THREAD

**Issue by nashlash17** [SFDO-Community/declarative-lookup-rollup-summaries#1001]
I want to start by acknowledging that I love DRLS. It has been a great tool for my clients and I look forward to continuing to use it in the future.

I'm posting to get help on an error that I recently started seeing. The error is on an unrelated process builder which is unable to update an account because of a dlrs_AccountTrigger error.

Here's the PB error message:
Error element myRule_1_A1 (FlowRecordUpdate).
The flow tried to update these records: null. This error occurred: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_AccountTrigger: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 0032M000034BpzNQAS; first error: UNKNOWN_EXCEPTION, java.lang.NullPointerException: [] Class.dlrs.RollupService.Updater.updateRecords: line 1318, column 1 Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1361, column 1 Class.dlrs.RollupService.updateRecords: line 1289, column 1 Class.dlrs.RollupService.handleRollups: line 895, column 1 Class.dlrs.RollupService.triggerHandler: line 329, column 1 Trigger.dlrs_AccountTrigger: line 7, column 1. You can look up ExceptionCode values in the SOAP API Developer Guide.

Any help or guidance would be much appreciated.

**Comment by afawcett** [comment]
I had a quick look at line 1361 in RollupServce and a cause does not leap off the screen for this - can you try with latest version?

**Comment by aheber** [comment]
Marking this as closed. If this needs further support and review please open a conversation is the Trailblazer Community Group for DLRS, our preferred channel for support. Many fantastic individuals are available there to help work through challenges and answer questions.
