### ISSUE TITLE
Getting Error while deploying the DLRS 

### ISSUE THREAD

**Issue by SahanaS1** [SFDO-Community/declarative-lookup-rollup-summaries#1003]
![image](https://user-images.githubusercontent.com/75590679/101296487-c3a89100-37d8-11eb-9de3-40bd49d422a2.png)
Hi All,

I am getting this error while deploying the trigger.
Please find my setup also for the below trigger
![image](https://user-images.githubusercontent.com/75590679/101296510-e5a21380-37d8-11eb-9f92-5adea4c1d5ee.png)

Urgent request. Please let me know the workaround for this.

Thanks

**Comment by aheber** [comment]
@SahanaS1 I realize this isn't a timely response to your request. It looks like the test class that was auto-generated isn't compatible with your environment. You'll need to probably figure out test code that can be compatible with your system. You may need to engage a developer familiar with your system and your data needs.

I'm hoping you've already overcome this but if you need further support you'll likely find much more timely support in the Trailblazer Community Group for DLRS.
