### ISSUE TITLE
System.LimitException: Maximum stack depth reached: 2

### ISSUE THREAD

**Issue by arunaveeru** [SFDO-Community/declarative-lookup-rollup-summaries#1008]
Recently, we started getting following error in one of our sandboxes for DLRS trigger on contacts:

 

(dlrs)

23:20:59.705 (13888276685)|FATAL_ERROR|System.LimitException: Maximum stack depth reached: 2

 

All our Contact updates and any batch jobs started failing.

 

in order to check what is causing the issue, we started reverting back the recent changes done one by one. the error vanished. however, upon deploying back the exact same components, there was no error. 

 

This issue can reoccur in any of the environments, it cannot be fixed without knowing the rootcause. Your help would be greatly appreciated.

**Comment by afawcett** [comment]
Hmmm i wonder if its this platform bug? https://trailblazer.salesforce.com/issues_view?id=a1p30000000sY20AAE

**Comment by aheber** [comment]
I'm going to mark this for closure. If there are more details or if the problem returns please reach out to the Trailblazer Community Group for DLRS for additional support. That is our current recommended channel to receive support as that is where the majority of our experts are available to help respond and answer questions.
