### ISSUE TITLE
Parent updated to "blank" unexpectedly 

### ISSUE THREAD

**Issue by alineas86** [SFDO-Community/declarative-lookup-rollup-summaries#1010]
I have a DLRS setup with the following:

- Parent obj: Account
- Child obj: Contact
- Relationship Field: AccountId (this field has only Household Accounts)
- Relationship Criteria: npsp__Primary_Contact__c = true AND "<a date field>" != null

The rollup is supposed to copy <a date field> value from the Contact to the Account.

But I would like the rollup to only work for household accounts. For Org Accounts I want my users to enter the date manually. Because I am using AccountID I thought it would work, but every night the field in the Org Accounts are getting overwritten with blank, even though they have no Contact associated with them. 

Is this expected to happen?

**Comment by aheber** [comment]
@alineas86 I know I'm late to the party on this one. We're you able to get this resolved?

It sounds like you have a scheduled full calculate that needs to be scoped down to just your target records. (filtering on Parent Type?)

**Comment by aheber** [comment]
Closing to inactivity.
