### ISSUE TITLE
Add Org name/ID in error email

### ISSUE THREAD

**Issue by Scarrien** [SFDO-Community/declarative-lookup-rollup-summaries#1011]
I received an email from DLRS about an Apex job failing to update rollups (see below). However, since I have DLRS installed in multiple orgs for different clients, it was time consuming to figure out which org the error was happening in.

I recommend adding the organization name and org ID to the email message to make it easy to know where the error is happening. Looking at the code, the change would be about line 70 in the RollupCalculateJob class.
https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/force-app/main/classes/RollupCalculateJob.cls

I would add a reference to the Organization object [SELECT Id, Name FROM Organization] that contains the Org ID and Name then add this info the the email subject and/or message. I created a pull request with this change that is linked below.

----------------------------------

SUBJECT: Apex job xxxxxxxxxxx failed to update rollups

MESSAGE: Error: Record Currently Unavailable: The record you are attempting to edit, or one of its related records, is currently being modified by another user. Please try again.. Parent record Ids _[record Ids here]_

**Comment by afawcett** [comment]
Why thank you - working on a release now - will include.

**Comment by JimBTek** [comment]
released in 2.13
