### ISSUE TITLE
Metadata API Errors in Safari

### ISSUE THREAD

**Issue by ZennifyLuke** [SFDO-Community/declarative-lookup-rollup-summaries#1017]
When accessing the DLRS interface using the Safari browser (version 14.0.2 on MacOS version 11.1) we are consistently receiving a Metadata API error:

`Salesforce Metadata API connection failure, click the link below to configure`

On the Welcome page's debug info, the error we receive is:

`Web service callout failed: Failed to get next element`

Refreshing the Remote Site Setting, deleting it and recreating it, and reinstalling DLRS entirely did not solve the issue. This occurs in both normal mode and in a Private browsing session. Switching to the Chrome browser seemed to clear the issue up immediately.

**Comment by ZennifyLuke** [comment]
Closing this issue as the Metadata API errors persist in Chrome, so may be related to session issues.

**Comment by ZennifyLuke** [comment]
Sigh. Apologies for the back and forth, but reopening with some additional details.

The issue seems to be tied to Safari after all. Clicking the button on the Welcome page to create the Remote Site Setting causes the Metadata API error to show in all browsers. Clicking it again in Chrome restores access to Chrome users, while Safari users still see the error and cannot access the tool.

**Comment by mkolodner** [comment]
I think I'm seeing the same behavior. Logged into client org in Safari (my default) and got the Metadata API error. Logged in via Chrome and was able to restore access. But in Safari I still can't access the tool.

**Comment by mkolodner** [comment]
BTW, I'm also on Safari Version 14.0.2 (15610.3.7.1.10, 15610) on MacOS 10.15.7 (19H512)

**Comment by winstonhenke** [comment]
Having the same issue
macOS: 11.2.1
Safari: v14.0.3 (16610.4.3.1.4)

**Comment by zhubj** [comment]
Having the same issue
macOS:11.2.3
Version 14.0.3 (16610.4.3.1.7)

**Comment by mlregal** [comment]
Having the same issue accessing it in Chrome, we've don't have macOS, so I think it may be bigger than just a Safari issue:
OS: Windows 10 Enterprise
Chrome Version 92.0.4515.131

**Comment by msakarettnaborg** [comment]
Same here! Issue visible in Safari on mac OS big sur 11.6, not visible in Chrome on same OS.

Were able to resolve the error message in Chrome on mac OS by deleting the remote site setting and using the button on the welcome page to recreate the remote site setting.

We just (manually) ran one of the scheduled DLRSs and it worked fine.

**Comment by aheber** [comment]
I'm going to close this, hopefully most of this is resolved with our new LWC wizard available in v2.21. It uses different mechanisms to manage rollups and is hopefully more reliable.

If you find you aren't able to use that wizard and still have concerns, please open another issue.
