### ISSUE TITLE
Developer script exception error

### ISSUE THREAD

**Issue by nimmi400** [SFDO-Community/declarative-lookup-rollup-summaries#1019]
I have been getting this error often. What can be done to troubleshoot this error?

Apex script unhandled trigger exception by user/organization: 

dlrs_Attendance_DailyTrigger: execution of AfterInsert

caused by: System.DmlException: Update failed. First exception on row 74 with id a0t3s000003FLuOAAW; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, This connection is a duplicate: []

Class.dlrs.RollupService.Updater.updateRecords: line 1381, column 1
Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1424, column 1
Class.dlrs.RollupService.updateRecords: line 1352, column 1
Class.dlrs.RollupService.handleRollups: line 1000, column 1
Class.dlrs.RollupService.triggerHandler: line 311, column 1
Trigger.dlrs_Attendance_DailyTrigger: line 7, column 1

**Comment by aheber** [comment]
@nimmi400 this sounds like a custom validation rule on the parent record, when a child is updated and the rollup tries to update the parent (record with ID a0t3s000003FLuOAAW) it isn't compatible with the current validation rules and likely needs to be cleaned up independent of the DLRS rollup.

I'll move this to closed but if you do come back and have some additional details or need additional support I'd recommend you contact our wonderful Trailblazer Community Group for DLRS which is our recommended channel to obtain support and get answers to your questions.
