### ISSUE TITLE
Unable to connect to the Salesforce Metadata API.

### ISSUE THREAD

**Issue by itsabsolute** [SFDO-Community/declarative-lookup-rollup-summaries#102]
Have created a remote site setting but still receive an error connecting to the metadata API?

**Comment by afawcett** [comment]
Check this out https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/110, could be a break through at long last! :+1:

**Comment by rbhagat30** [comment]
Facing the same issue ,remote site is already there . can you please help me in this
