### ISSUE TITLE
dlrs preventing record edit.

### ISSUE THREAD

**Issue by cjtoyn** [SFDO-Community/declarative-lookup-rollup-summaries#1020]
**Describe the bug**
When I try to update the parent account field on an account, it gives me an error. Initially it looks like there isn't a parent account, but when you click into it to edit, it shows Unknown record. Whether I try to remove that and make the parent account blank, or if i try to change it to another parent account, it gives me the same error. We have two DLRSs that roll up using the ParentId, but both have been inactivated to try and resolve the issue but that was unsuccesfull.

dlrs_AccountTrigger: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 0012G00001eBaJCQA0; first error: INVALID_CROSS_REFERENCE_KEY, invalid cross reference id: [] (dlrs)

**To Reproduce**
1. Go to account 0012G00001ZynF8QAJ
2. Edit the record
3. Remove the parent account labeled "Unknown record"
4. Save

**Expected behavior**
When I click save, I expect there to be no linked parent account anymore. However, i get the error instead which prevents me from saving the account

**Screenshots**

**Additional context**
![Screen Shot 2021-02-11 at 5 02 52 PM](https://user-images.githubusercontent.com/78938307/107777134-b25f9180-6cff-11eb-8700-793289e61dde.png)
![Screen Shot 2021-02-11 at 5 03 03 PM](https://user-images.githubusercontent.com/78938307/107777140-b4295500-6cff-11eb-9ae2-054099824e62.png)
![Screen Shot 2021-02-11 at 5 03 16 PM](https://user-images.githubusercontent.com/78938307/107777148-b5f31880-6cff-11eb-86af-22b565ca94ca.png)

**Comment by aheber** [comment]
@cjtoyn were you able to get this resolved? I haven't seen this behavior before. Is there any chance this is a Sandbox and some records are missing?

If you're still experiencing the problem I'd recommend you reach out to our Trailblazer Community Group for DLRS to request support, that is our recommended channel to receive support and get your questions answered.
