### ISSUE TITLE
PMD flags tests with no asserts

### ISSUE THREAD

**Issue by charles-thompson-salesforce-com** [SFDO-Community/declarative-lookup-rollup-summaries#1025]
I noticed that PMD is flagging tests with no asserts in some of the Apex test classes.  Not a big deal at all, but it's interesting what gets trapped by PMD.

**Apex unit test classes should have at least one System.assert() or assertEquals()   or AssertNotEquals() call (rule: Best   Practices-ApexUnitTestClassShouldHaveAsserts)**

Classes flagged:

force-app/main/default/classes/dlrs_AccountTest.cls
force-app/main/default/classes/dlrs_AuthorisationTest.cls
force-app/main/default/classes/dlrs_CaseTest.cls
force-app/main/default/classes/dlrs_ContactTest.cls
force-app/main/default/classes/dlrs_Tax_Payer_RegistrationTest.cls

It flags lots of other things that are immaterial, but you may want to consider adding an assert here and there.

**Comment by aheber** [comment]
Dup of #581
