### ISSUE TITLE
Manage Lookup Rollup Summaries - only get option Create New

### ISSUE THREAD

**Issue by JimWight** [SFDO-Community/declarative-lookup-rollup-summaries#1028]
The Manage Lookup Rollup Summaries page has a dropdown.  The only option displayed is 'Create New'  - how do you display / manage existing Rollups - at present I manage from a list view.  Is there not the ability to manage from the Manage Lookup Rollup Summaries page??

Screenshot below:

![Screenshot 2021-04-14 at 22 33 52](https://user-images.githubusercontent.com/82545364/114783560-e4c65300-9d71-11eb-8a1e-ba5563be2f90.jpg)

**Comment by aheber** [comment]
@JimWight, if you're still stuck on this you'll be able to get much better support from the Trailblazer Community Group for DLRS. That group is usually monitored by many talented and experienced individuals who should be able to give you a hand.

As for your current screenshot, I think this is the difference between the older SObject-based configuration objects and the more recent Custom Metadata based configurations.
