### ISSUE TITLE
Case Merge Error Message

### ISSUE THREAD

**Issue by becksmcg** [SFDO-Community/declarative-lookup-rollup-summaries#1032]
**Describe the bug**
I have used DLRS to roll up Time Log objects onto a Case.  When I go to merge a case, the DLRS now prevents this
**To Reproduce**
1. Go to a Cases list view, select two cases and Merge
2. See error: dlrs_CaseTrigger: execution of AfterDelete caused by: dlrs.RollupService.RollupValidationException: Scheduled rollups are running in legacy mode and are unable to resolve corresponding shadow rollups. Please visit the Lookup Rollup Summary Tools tab for more information and steps to resolve. Class.dlrs.RollupService: line 1082, column 1 Class.dlrs.RollupService: line 1001, column 1 Class.dlrs.RollupService.triggerHandler: line 329, column 1 Trigger.dlrs_CaseTrigger: line 7, column 1

**Expected behavior**
Expected would be that the two cases merge successfully

**Screenshots**
<img width="1675" alt="Screenshot 2021-04-27 at 09 14 08" src="https://user-images.githubusercontent.com/83273921/116208593-fc6de600-a738-11eb-8304-b716a6f6a8ba.png">
<img width="1675" alt="Screenshot 2021-04-27 at 09 14 59" src="https://user-images.githubusercontent.com/83273921/116208680-10194c80-a739-11eb-99d5-48e00bbe5572.png">

**Additional context**

**Comment by aheber** [comment]
@becksmcg I'm sorry this has been sitting for so long.

The error says you're running in legacy mode but it doesn't see some records that should help it run.
Please complete the steps found here to get it out of legacy mode.

Instructions should be here:
https://sfdo-community-sprints.github.io/DLRS-Documentation/Issues/#attention-need-to-delete-unused-field-on-dlrs__lookuprollupsummaryscheduleitems__c
