### ISSUE TITLE
Apex script unhandled trigger exception - dlrs_ContactTrigger: execution of AfterUpdate

### ISSUE THREAD

**Issue by Meg-Lynch** [SFDO-Community/declarative-lookup-rollup-summaries#1034]
Got this error email the other day. Any idea how to fix this issue?

caused by: dlrs.fflib_QueryFactory.InvalidFieldException: Invalid field 'CreatedDate' for object 'dlrs__LookupRollupSummary__c'

Class.dlrs.fflib_QueryFactory.getFieldPath: line 91, column 1
Class.dlrs.fflib_QueryFactory.addOrdering: line 543, column 1
Class.dlrs.fflib_SObjectSelector.configureQueryFactory: line 434, column 1
Class.dlrs.fflib_SObjectSelector.newQueryFactory: line 318, column 1
Class.dlrs.fflib_SObjectSelector.newQueryFactory: line 300, column 1
Class.dlrs.RollupSummariesSelector.CustomObjectSelector: line 165, column 1
Class.dlrs.RollupSummariesSelector: line 80, column 1
Class.dlrs.RollupService: line 1135, column 1
Class.dlrs.RollupService: line 816, column 1
Class.dlrs.RollupService.triggerHandler: line 329, column 1
Trigger.dlrs_ContactTrigger: line 7, column 1

**Comment by danicawytch** [comment]
I have this same error message. Any help would be much appreciated!

**Comment by Meg-Lynch** [comment]
I had 2 triggers scheduled for the same time on the same object. I updated that and haven't got the error since. Hopefully that was it!

**Comment by andyjb** [comment]
@Meg-Lynch It appears that this has now been resolved, so I have closed the issue. Please advise if this is not the case.
