### ISSUE TITLE
Scheduled Jobs Naming Conventions & Other Questions?

### ISSUE THREAD

**Issue by jmiz** [SFDO-Community/declarative-lookup-rollup-summaries#1037]
I'm having a really hard time gaining visibility into scheduling for my DLRSs. We use the Scheduled calculation mode. Two questions:

- I do not understand what the "Scheduled" option correlates to the options listed here: https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups . How do I know if I'm using full or incremental calculate?
- When I visit Scheduled Jobs, some of the jobs are clearly named "rollup_{{DLRS NAME}}" and others are named "rollup_{{DRLS record ID}}". Why is this?
- When I pull a report of DRLS Scheduled Items, I have 105k rows. There is obviously something wrong there. How do I troubleshoot and/or fix?

**Comment by aheber** [comment]
@jmiz if you still have questions on this I'll give a preliminary answer but I'd recommend you reach out to the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) with any follow up.

"Scheduled Full Calculate" is what is creating the named rollup scheduled actions. This is taking a rollup and reprocessing all parent records to get current values. This is generally done independent of the "Calculation Mode" and is use when a reactive recalculation, such as realtime or scheduled, won't work for your situation or for the object you're working with.

This is different than having the rollup in "Scheduled" calculation mode which uses a trigger to watch for record changes, notices a possible need to recalculate the parent and creates a DLRS Scheduled Item record. Those records are expected to be later processed by a recurring "RollupJob" scheduled in your org. This isn't scheduled for a single rollup but rather processes ALL scheduled items in the org and removed the Scheduled Item records after success.

Some additional information available here: https://sfdo-community-sprints.github.io/DLRS-Documentation/User%20Guide/
