### ISSUE TITLE
Validation Errors While Saving Record(s) There were custom validation error(s) encountered while saving the affected record(s). 

### ISSUE THREAD

**Issue by mani-radhu** [SFDO-Community/declarative-lookup-rollup-summaries#1040]
Hi,

I am facing installation issues The error is not meaningful.
![image](https://user-images.githubusercontent.com/82180969/121586756-a0fe6b80-c9f9-11eb-9d37-4d559f8a680d.png)

Please help me out

Thanks and Regards
Mani

**Comment by aheber** [comment]
@mani-radhu I'm afraid I have no idea what could cause this. I have never seen this before.

If you're still having this error could you look in the Deployment history (after what will probably need to be another attempt to install) to see if there are any details there? If you can't track down any details from your system you might need to get Support involved to track down what is happening.

**Comment by yogee-areya** [comment]
Is it resolved?
I'm facing the same issue.
Please help us out.

**Comment by aheber** [comment]
@yogee-areya could you look at your deployment history and see if there are additional details?
Unfortunately the current report doesn't provide enough information.
Not having anything to help reproduce it makes it very difficult to troubleshoot.

**Comment by yogee-areya** [comment]
Unfortuantely there is no additional information too on deployement history page.

<img width="1165" alt="image" src="https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/94613175/42df520a-ceb6-49c3-9046-11b109562f6f">

**Comment by aheber** [comment]
I don't think we ever found a root cause for this. If someone else runs into this please open a support case with Salesforce for additional details and if DLRS needs to make any changes based on that feedback, please open a new issue.
