### ISSUE TITLE
Error while scheduling a calculate job

### ISSUE THREAD

**Issue by TahreemR** [SFDO-Community/declarative-lookup-rollup-summaries#1041]
Hi,

Before I explain the issue, a little background about what we have been trying to achieve.

So we have a formula checkbox field on account which when checked should send off an email (via workflow rule), however since the checkbox is updated by automation our WFR is not detecting it as changed hence not firing off. We tried different hacks but nothing helped.

A similar issue with another client was dealt by creating a DLRS field and scheduling it to calculate it every day e.g. total number of contacts / opps on account etc. 

Now coming towards the issue:
I have created the DLRS and tested it out first by doing a full calculate job/realtime to ensure the criteria is all set and it worked. I then scheduled it to calculate at a certain time however I didn't receive the email that I was expecting hence I started experimenting with the DLRS and tried scheduling it after every hour if the email was not received.

The Problem: It would not let me schedule the calculate a 2nd time - I get 'The Apex job named "rollup_a074x000002cDpM" is already scheduled for execution.' however when I go to the 'Calculate Jobs' there is nothing. Also I added the field 'Calculate Job Id' to the page layout and cleared it out, refreshed and tried again - same error.

Can you please help with this.
![Screen Shot 2021-06-11 at 12 18 09 AM](https://user-images.githubusercontent.com/79998230/121630127-928c7000-ca4a-11eb-9d76-c86963c6931f.png)
![Screen Shot 2021-06-11 at 12 18 27 AM](https://user-images.githubusercontent.com/79998230/121630128-928c7000-ca4a-11eb-8107-e7c7393d5d08.png)

**Comment by amatigianc** [comment]
I had this very same error message. From salesforce:
Set up --> scheduled Job ---> Find the job with that ID, and delete it. You can then recreate that job.
GC

**Comment by TahreemR** [comment]
Thank you so much, it worked.

_ _ _
Best Regards,
Tahreem Rasool
Sales Operations Analyst & Account Manager

Mobile: 647-914-1261
***@***.***
Want to learn more about Sales Ops best practices? Check out our CEO,
Rachel Haley, on this amazing podcast
<https://www.melindawittstock.com/wingspodcast/rachel-haley/>.

**Comment by andyjb** [comment]
@TahreemR this appears now to have been resolved, and so I have closed the issue. Please advise if this is not the case.
