### ISSUE TITLE
DLRS Trigger Not Working

### ISSUE THREAD

**Issue by mshammel1007** [SFDO-Community/declarative-lookup-rollup-summaries#1042]
I have two summaries identical summaries, one is counting all records, and that works fine.  The other is counting only records where the status is accepted and that isn't working.  It works when I run the full calculate but not when the child record is updated to accepted.  The user changing the status is an external guest user, but I wouldn't think that would matter.  My guess is that its not recognizing that the status has changed.  Any thoughts?

**Comment by muralithe1** [comment]
Hi team , Could you please help. Works when clicked "Full calculate" but not working on realtime update of records. Seems the triggers are not working.

**Comment by aheber** [comment]
@mshammel1007 any chance you're missing the Status field name in the Relationship Criteria Fields? DLRS needs to be told which fields are likely to be the source of meaningful changes. (the package doesn't parse the Relationship Criteria to try and auto-determine candidate fields)

If you're not already familiar with the Trailblazer Community Group for DLRS, I would recommend that as a fantastic place to receive support and is our recommended channel.

**Comment by aheber** [comment]
@muralithe1 would you be able to provide any details on your situation? I would guess you're likely in a similar situation, Relationship Criteria Fields could be setup incorrectly.

**Comment by jhoanborges** [comment]
Same error

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/32471957/a495bc42-a734-4058-b0e2-f3b26babf58c)

**Comment by aheber** [comment]
@jhoanborges, I think I'd like to close this issue as it doesn't have a clear purpose or specific issue and seems to be collecting "me too" contributions.

It would be best for you to start in the Trailblazer Community Group for DLRS to work through the issue you're experiencing. There are many more people there that are able to help and provide insight for troubleshooting configuration and behavior problems with the tool.

When you start a post there would you be able to provide any details on your goals, error messages you've received, what you've done to try and resolve them, details of your configuration and environment? That would give a head start to anyone who feels like they might be of help to you. Thanks!

**Comment by renatoliveira** [comment]
> @jhoanborges, I think I'd like to close this issue as it doesn't have a clear purpose or specific issue and seems to be collecting "me too" contributions.

I think this issue should remain open and should gather more "me too" comments too. I'm having this same issue, for seemingly no reason, on the latest version of the app, and I don't know why either. Clicking on "Full Recalculate" works for the rollup then, but it doesn't work when a record is updated from the UI, which is basically the explanation for everyone who had this issue.

If you look at @jhoanborges's screenshot, you'll see that there isn't anything wrong with the setup at first glance. As long as the field in the "Relationship Field" is a lookup, that should work, right? And if the trigger is deployed too, of course.

In my situation I'm trying to make a rollup on accounts with their child accounts. The lookup is obviously `ParentId` and it should "count" the `Id` field. Can't be more simple than that. And my trigger is deployed too.
