### ISSUE TITLE
Upgraded DLRS to version 2.13 and now receiving APEX errors on all rollups 

### ISSUE THREAD

**Issue by DNeibert1234** [SFDO-Community/declarative-lookup-rollup-summaries#1043]
Hi-  I'm our SF admin and have recently upgraded to the 2.13 version (previous version worked like a charm).  Now, all of my DLRS are throwing off errors when I attempt to "Manage Child Trigger".  I have deactivated child validation rules and rebuild.. but can't seem to get this to work.  Any help would be greatly appreciated.  Thanks

Error:
dlrs_ts2_PlacementTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, ts2.Placement: execution of BeforeInsert caused by: System.NullPointerException: Attempt to de-reference a null object Trigger.ts2.Placement: line 14, column 1: [] Class.dlrs.RollupService.testHandler: line 282, column 1 Class.dlrs_ts2_PlacementTest.testTrigger: line 11, column 1

**Comment by aheber** [comment]
@DNeibert1234 were you able to get this resolved? It looks like the test code for the rollups is failing to meet an expected configuration state from the `ts2` managed package. DLRS likely won't know what is expected for the Placement records and you'll probably need to get a custom test script coded. If you're not comfortable with Apex you'll need to reach out to someone who understands your environment and the packages you have so help get a correct test script created.

If you need support in the future you'll likely get much better/faster support from our Trailblazer Community Group for DLRS where all the expoerts hang out and provide support.
