### ISSUE TITLE
When I run Full Calculate or Schedule Full Calculate, nothing happens. I receive no error, the job just doesn't run and the summary logs are blank. This is in Sandbox. Install has not taken place in Production.

### ISSUE THREAD

**Issue by crystalmregan** [SFDO-Community/declarative-lookup-rollup-summaries#1047]
**IMPORTANT NOTE** The Chatter Community Group can be found [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p). If it is an issue that you need help on configuring the tool or have an unexpected error its really worth seeing if the community can help first before raising a GitHub issue. Most users hangout in the Chatter Community Group. Otherwise if prefer you can post here and still link in the Chatter Community Group.

**Comment by aheber** [comment]
@crystalmregan, if this is still an issue I'd encourage you to bring this to the Trailhead community, https://trailhead.salesforce.com/trailblazer-community/groups/0F9300000009O5pCAE.

Have you looked in the Apex Jobs setup page to see if anything executed? Is that what you mean by "job just doesn't run?"
