### ISSUE TITLE
Reduce number of SOQL queries made by using new Spring'21 Custom Metadata methods

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#1049]
**Is your feature request related to a problem? Please describe.**
Currently in RollupSummariesSelctor.cls SOQL is used to query the custom metadata objects that store rollup definitions. This consumes query counts and contributes to the overall limit permitted by the tool. 

**Describe the solution you'd like**
Salesforce has since Spring'21 (API 51) enabled a way to query custom metadata objects WITHOUT consuming limits - yay! Here is the details https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_custom_metadata_types.htm

**Describe alternatives you've considered**
None

**Additional context**
To apply this enhancement one can update the code solely in the RollupSummariesSelector.cls. Note that this code knows if the query is for edit or not (and thus per the docs for this new feature can intelligently use SOQL to ensure the large text area fields are not truncated). For more information see here https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_custom_metadata_types.htm

**Comment by JimBTek** [comment]
@afawcett here is the code I started writing. it is not in the namespace, but it was so we could just create Schedule Item records whenever we felt like without burning SOQLs for a complex client org:

- get all metadata records
- find the ones that match the same sObject AND are Scheduled AND are Active. (mimic the trigger based functionality)
- upsert ScheduleItems

`public class dlrsCreateScheduleItems {

    
    public static void createFromMetadata(Id parentId, String parentObj, String childObj){
        List<dlrs__LookupRollupSummary2__mdt> mdts = dlrs__LookupRollupSummary2__mdt.getAll().values();
        List<dlrs__LookupRollupSummaryScheduleItems__c> scheduledItems = new List<dlrs__LookupRollupSummaryScheduleItems__c>();
        for(dlrs__LookupRollupSummary2__mdt mdt : mdts){
            if(
                mdt.dlrs__ChildObject__c == childObj && 
                mdt.dlrs__ParentObject__c == parentObj && 
                mdt.dlrs__CalculationMode__c == 'Scheduled' && 
                mdt.dlrs__Active__c)
            {
                system.debug('Adding DLRS Scheduled Rollup ' + mdt.DeveloperName + ' to ' + parentObj + ' ' + parentId);
                dlrs__LookupRollupSummaryScheduleItems__c scheduledItem = new dlrs__LookupRollupSummaryScheduleItems__c();
                scheduledItem.Name = parentId;
                scheduledItem.dlrs__LookupRollupSummary2__c = mdt.Id;
                scheduledItem.dlrs__ParentId__c = parentId;
                scheduledItem.dlrs__QualifiedParentID__c = parentId + '#' + mdt.Id;
                scheduledItems.add(scheduledItem);
            }
        }
        
        upsert scheduledItems dlrs__QualifiedParentID__c;
        
        
    }
}`

**Comment by afawcett** [comment]
@JimBTek this is very interesting - its not actually what I thought we where talking about in email actually - but none the less very valid and I can totally see what use case you are driving after with this snippet. Basically triggering a scheduled incremental update to a given parent record. I can imagine this being a helper you on the roll up definition page - what do you think?

**Comment by JimBTek** [comment]
Yeah we were just working on using it instead of the DLRS trigger to create ScheduledItems so we could avoid the 2 SOQLs based on how DLRS actually does it.  It could still get incorporated into the codebase to save those 2 SOQLs when the DLRS trigger runs, but beyond my skill level I feel.

**Comment by afawcett** [comment]
I thought I would share some implementation ideas and thoughts on this here - hope it helps! :-) 

**Summary**
Salesforce has release a new feature called "Custom Metadata Type Methods" - https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_custom_metadata_types.htm - these are alternatives to running regular SOQL over Custom Metadata Type objects. While limits are not incurred for the records read by SOQL over such objects, the number of allowed SOQL queries (max 150) is consumed. These new methods bypass this limit and also implement caching to improve performance. Making it 100% free and more performance to read custom metadata type records in compatible scenarios. In DLRS cases where query limits are close to the maximum (if there are a lot of rollups on a child and/or recursion) this feature can make or break a realtime rollup scenario. Note that this does not change our standard advice to consider async rollups if the use case permits it.

**Q: Where is the best place to take advantage of this?**
RollupSummariesSelector is the single place in which the DLRS code base reads rollup definitions. It uses another class RollupSummary to represent a rollup definition instead of the usual __c or __mdt types. This is because the selector class encapsulates both reading from the custom object and custom metadata locations where rollup definitions can exist in both places for some older customers. This encapsulation also makes it the perfect place to implement this optimization without incurring widespread changes to the rest of the code base - go separation of concerns! Additionally the selector class uses two inner selector classes to separate the concerns of reading from two different locations, these inner classes are CustomMetadataSelector and CustomObjectSelector.

**Q: How is the code and encapsulation in RollupSummariesSelector implemented?**
The RollupSummariesSelector class exposes several public methods that represent requests the rest of the code makes for rollup information (see below). These methods delegate to methods in the inner classes mentioned above. One to query for custom object based rollups and one for custom metadata based rollups. The results from both of these delegations is aggregated together before returning to the caller - so it appears as one result set and thus the storage and access patterns complexity is invisible to the caller - yay! 

These are the methods, and exist in the main class and two inner classes.
- selectById
- selectActiveByChildObject (two overloads)
- selectActiveByUniqueName
- selectByUniqueName

**Q: Can these new Custom Metadata Type Methods replace ALL queries for Custom Metadata in the code base?**
Looking at the new Salesforce methods, https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_methods_system_custom_metadata_types.htm, there is support for getting records by id, by name and querying all of them (I would be surprised if there is more than 100-150 max in DLRS impls?). These methods do not have WHERE clause support though. Thus not all the query methods can be fulfilled without some help from the developer in this case. 

For example the above selector methods that query for rollup definitions for a given child object will need to use the getAll method and filter within memory the result set. Some basic profiling (anon apex snippets) is recommended be done to see how getAll really performs and understand any row limits - as the documentation is not clear on this. With this combination of using the Custom Metadata Type methods directly and/or getAll with in-memory filtering - it should be possible to update all the above methods to remove the current SOQL. That is - in all but one scenario! 

**Q: Any gotchas with this?**
That one scenario is a case where the RollupSummariesSelector is being asked to read rollup definitions for the purpose of editing them - via the Manage Rollup Summaries tab. In this case the RollupSummariesSelector is passed true in the forEdit constructor parameter. This has historically been used to limit heap as long text area fields for test code overrides are not needed during normal runtime. This is a pretty handy clue in respect to one key restriction of the new methods - they truncated field data above 255 characters! Thus if this flag is set - the current SOQL behavior should still be executed.

**Q: Where are the best places to insert the new method calls to take advangage of the Custom Metadata Type Methods?**
Ideally make sure all changes are fully encapsulated in the RollupSummariesSelector class, specifically the CustomMetadataSelector inner class. This class extends the fflib_SObjectSelector which supports SOQL based record access only. Given the forEdit scenario above - the existing SOQL/fflib_SObjectSelector usage in the CustomMetadataSelector class methods should be retained - but only used if forEdit is true. Otherwise the code path can leverage the above new Custom Metadata Type Methods to query custom metadata rollups.

Here is an example (not tested or compiled)…

~~~
public List<RollupSummary> selectById(Set<String> idSet) 
{ 
	if(forEdit) {
		return RollupSummary.toList( Database.query(newQueryFactory().setCondition('id in :idSet').toSOQL()) ); 
	else {
		List<LookupRollupSummary2__mdt> rollups = new List<LookupRollupSummary2__mdt>();
		for(Id in idSet) {
			// TODO: Its not clear from the docs what the record not found behavior is - test if this is null or an exception
			LookupRollupSummary2__mdt rollup = LookupRollupSummary2__mdt.getInstance(id);
			if (rollup!=null) {
				rollups.add(rollup); 			}
		}
		return  RollupSummary.toList(rollups);
	}
}
~~~

**Comment by seanpat09** [comment]
While working on this we found that querying for custom metadata records consumes query rows, but not the query invocations. While we won't get the benefit of saving on SOQL calls, we should still get some performance improvements by using the new custom metadata methods.

**Comment by seanpat09** [comment]
Using the new methods will help reduce the number of query rows in an execution, though since that limit is 50,000, the benefit isn't as impactful as saving on a query invocation.

**Comment by Riley-Schill** [comment]
QE Approved
Tested the following: 
Deployed ContactTrigger and CaseTrigger
Created a rollup to concatenate text and sum a number from Case to Contact
Tested Relationship Criteria
