### ISSUE TITLE
Unable to connect to the Salesforce Metadata API

### ISSUE THREAD

**Issue by Focus-HarshitaSharma** [SFDO-Community/declarative-lookup-rollup-summaries#1051]
We are facing "Unable to connect to the Salesforce Metadata API" error in our Professional Edition salesforce org. Current we have upgraded to v2.3.
Attaching here the screenshot:

![image](https://user-images.githubusercontent.com/87760477/126481810-cc8abde8-0bfc-46c1-9c3e-22eefa8ace5d.png)

We have tried following options to resolve the error but still can't resolve these errors.
1. Created new remote site setting manually.
2. Disabled the schema setting.
3. Enabled custom metadata types and created records in profile of system admin.
4. Tried to change the calculation mode to Process builder.

Need your help to resolve the issue as we can't deploy the trigger to activate the roll ups.
Please let me know if we can uninstall and re-install the app again to resolve the issue.

**Comment by mlregal** [comment]
We also just started getting this error. No changes to our org precipitating it.

**Comment by aheber** [comment]
If you are getting the "API_DISABLED_FOR_ORG" error then you're likely in a situation where Salesforce doesn't allow API access to your system. This is most often in Salesforce versions below Enterprise. DLRS uses the API to deploy triggers and Custom Metadata records.

There is a new LWC based configuration screen available in v2.21 that uses the API a lot less, you may still get this error but you can go past it. Unfortunately once you configure the rollup you may still need to use Flow to start it.

There are a lot of open questions around current support for Professional Edition orgs without API access. As far as I know that hasn't been tested for a good while so I am not sure if it is supported or not right now. Maybe you can do some testing a report back.

I'm going to close this issue but if you find another blocker once you've tested with the new LWC UI please open a new issue.
