### ISSUE TITLE
User can't access/run/calculate summaries

### ISSUE THREAD

**Issue by bo17grapes** [SFDO-Community/declarative-lookup-rollup-summaries#1053]
I've used this tool many times with clients before, but only with the System Administrator profile. I have a client that needs the ability for one of their users to run the calculation on the summaries. I've assigned the permission sets and every time the user goes into the tool and selects a summary, the page doesn't do anything. The fields don't populate and the buttons only show the "Save". Not sure what else to do. I am testing by logging in as that user as an admin (not directly logging in as that user).

1. Login in as the user.
2. Go to Lookup Rollup Summaries Tool Tab
3. Select any of the existing summaries.
4. See screenshot of what we see.

**Expected behavior**
When a summary is selected, the fields for that summary should populate and all the buttons for running/calculating the summary should show up.

<img width="1224" alt="2021-07-28_15-25-43" src="https://user-images.githubusercontent.com/25251559/127400648-31f0030f-e58a-4ee3-93a6-1f9043c14145.png">

**Comment by aheber** [comment]
I'm not sure what caused this but we're hopeful it is fixed with the release of our new LWC based wizard in v2.21. Please give that a go and let us know if it works better for you.
