### ISSUE TITLE
Lookup Rollup Calculate Jobs Not being Deleted

### ISSUE THREAD

**Issue by cameronfinley** [SFDO-Community/declarative-lookup-rollup-summaries#1054]
As the title suggest, the Lookup Rollup Calculate Jobs are not being deleted after a job is run. 

![Screen Shot 2021-08-02 at 08 30 03 AM](https://user-images.githubusercontent.com/88193709/127862148-6477ad0b-d142-45a9-bcef-46f216db9c0f.png)

Description of Issue: As the image (taken this morning) shows, there are Lookup Rollup Calculate Jobs from several days ago, preventing the scheduled jobs from running

Background Info: We are running DLRS v. 2.14 and I have completed the preliminary steps (creating the new report type and running the report, deleting the unused field, et cetera). Our scheduled jobs are setup according to [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki/What-you-need-to-know-about-Scheduling-Rollups) article. In other words, I have set the Calculate Mode to Process Builder and then clicked the Schedule Full Calculate button and set a schedule. All DLRS scheduled rollup jobs are set to run every hour.

Effect: This is preventing any of those rollups from being calculated as when the job tries and runs, it sees there is already an existing Lookup Rollup Calculate Job record, and throws an error that the job is already running.

Temporary Work Around: In theory, I could make all of them realtime, but there are too many rollups and it comes across governor limits. Temporarily, I am manually deleting the Lookup Rollup Calculate jobs, therefore allowing the rollups to run once every couple of hours, but this is not sustainable as there are 55 rollups.

**Comment by aheber** [comment]
If you're still having these problems, @cameronfinley, by chance do you see any errors related to these calculations? Would love to see the details of any errors. If those records are getting left behind it is often because of some other failure in the system crashing the calculation jobs.

Do you have scheduled full calculates or scheduled calculation mode jobs?

Thanks for any details you can provide.
