### ISSUE TITLE
@afawcett : I have installed the DLRS package in my salesforce sandbox org. Everything is working fine except for one. whenever I am trying to merge two duplicate account records it throws me a error as "**Apex trigger dlrs_AccountTrigger caused an unexpected exception, contact your administrator: dlrs_AccountTrigger: execution of AfterDelete caused by: dlrs.RollupService.RollupValidationException: Scheduled rollups are running in legacy mode and are unable to resolve corresponding shadow rollups. Please visit the Lookup Rollup Summary Tools tab for more information and steps to resolve.: (dlrs)**".  I am trying to debug it, but unable to find out anything from debug logs, where in its goes into after delete event as

### ISSUE THREAD

**Issue by BluviumDhiren** [SFDO-Community/declarative-lookup-rollup-summaries#1055]
@afawcett : I have installed the DLRS package in my salesforce sandbox org. Everything is working fine except for one. whenever I am trying to merge two duplicate account records it throws me a error as "**Apex trigger dlrs_AccountTrigger caused an unexpected exception, contact your administrator: dlrs_AccountTrigger: execution of AfterDelete caused by: dlrs.RollupService.RollupValidationException: Scheduled rollups are running in legacy mode and are unable to resolve corresponding shadow rollups. Please visit the Lookup Rollup Summary Tools tab for more information and steps to resolve.: (dlrs)**".  I am trying to debug it, but unable to find out anything from debug logs, where in its goes into after delete event as 
"dlrs_AccountTrigger on Account trigger event AfterDelete|__sfdc_trigger/dlrs_AccountTrigger" and then it throws the below error 
"Class.dlrs.RollupService: line 1082, column 1
Class.dlrs.RollupService: line 1001, column 1
Class.dlrs.RollupService.triggerHandler: line 329, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1
23:48:22.300 (963708661)|FATAL_ERROR|dlrs.RollupService.RollupValidationException: Scheduled rollups are running in legacy mode and are unable to resolve corresponding shadow rollups. Please visit the Lookup Rollup Summary Tools tab for more information and steps to resolve. "

Can you please help me to understand why and from where I am facing this issue.  Appreciate your help. 
Thanks,
Dhirendra

_Originally posted by @BluviumDhiren in https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/928#issuecomment-893169916_

**Comment by kumarjiv** [comment]
Hi,
I am also facing the same issue when we want to merge two accounts.

**Comment by aheber** [comment]
This may be resolved by looking at this upgrade guide, https://sfdo-community-sprints.github.io/DLRS-Documentation/Installation/upgrade.html

In short you'll likely need to delete a field that used to be part of the managed package. That field is used a signal to run in "legacy" mode.

If you run into more trouble I'd recommend posting on the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) for additional support.
