### ISSUE TITLE
Currency Field summing to $0

### ISSUE THREAD

**Issue by BelmarSid** [SFDO-Community/declarative-lookup-rollup-summaries#1058]
**IMPORTANT NOTE** The Chatter Community Group can be found [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p). If it is an issue that you need help on configuring the tool or have an unexpected error its really worth seeing if the community can help first before raising a GitHub issue. Most users hangout in the Chatter Community Group. Otherwise if prefer you can post here and still link in the Chatter Community Group.

Wondering if anyone has had a similar issue with DLRS, I did a search and did not find anything similar.
I have a Custom Object Payments with a "Payment Amount" currency field. I am rolling this filed on to a related Object, Batch on a Currency Field called "Entered Amount". The Sum always returns $0, I manually updated the "Entered Amount" filed to $20 but DLRS reverted it back to $0. 

![2021-08-16_18-30-16](https://user-images.githubusercontent.com/89053594/129650257-60349f54-be0a-465b-82f6-443e5e1c8eb5.png)
![2021-08-16_18-33-48](https://user-images.githubusercontent.com/89053594/129650261-52b89c8c-975e-42a0-9a06-836bae0812b3.png)

**Comment by BelmarSid** [comment]
@afawcett can you help me identify this ghost?

**Comment by aheber** [comment]
@BelmarSid, I'm not sure what is going on with this one.

Is the "$0" being set when you update the parent or child records? In theory DLRS runs when you update the child record, if you're manually setting the value and it is immediately set to "$0" then I'd look at other automation that might be involved.

If you can capture a debug log during the execution that might help us understand what is happening.

https://help.salesforce.com/s/articleView?id=sf.code_add_users_debug_log.htm&type=5
