### ISSUE TITLE
Can no longer access DLRS

### ISSUE THREAD

**Issue by savsr** [SFDO-Community/declarative-lookup-rollup-summaries#1059]
I tried to access our DLRS today and have run into a problem. 

First, I hit this error message:
![image](https://user-images.githubusercontent.com/89640917/131120646-e32a43cd-e039-4660-959d-6fd5476319df.png)

I follow the instructions and hit this error message:
![image](https://user-images.githubusercontent.com/89640917/131120730-7a19d3a3-edc6-4f57-a6b3-11d87f996269.png)

Having spent the past 90 minutes digging around, it appears pretty common and seems to be linked to the remote site settings. To be on the safe side, I decided delete the existing remote site setting related to this and then to recreate a new one. As that had been listed as a solution previously. Unfortunately that hasn't worked. 
![image](https://user-images.githubusercontent.com/89640917/131120981-2686a528-a127-4570-a25a-780ccd32c324.png)

We haven't changed our domain recently but we did renew our certificate. I don't know if that's causing the trouble?

Any help would be much appreciated.

**Comment by aheber** [comment]
I'm going to mark this as closed but if you're still having a problem I'd recommend reaching out to the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) for support.
