### ISSUE TITLE
Cannot Access DLRS

### ISSUE THREAD

**Issue by jessicatownsend** [SFDO-Community/declarative-lookup-rollup-summaries#1066]
When trying to access a DLRS today through the "Manage Lookup Rollup Summaries" tab, I received the following error: "Error:
Salesforce Metadata API connection failure, click the link below to configure."
![DLRS Error1](https://user-images.githubusercontent.com/73909222/133168913-a7cc5b88-5abb-47e7-8cc2-3769aad1daeb.png)

I clicked the "Return to Home Page" link and saw these errors:
"Unable to connect to the Salesforce Metadata API."
"Web service callout failed: WebService returned a SOAP Fault: INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor="
![dlrs error](https://user-images.githubusercontent.com/73909222/133168836-465982b4-565c-42bc-8f0b-fea41c065c2b.png)

This organization has My Domain enabled so I believe the Remote Site Settings are not what needs to be updated here. I tried deleting and creating a new Remote Site Setting earlier just in case but it did not resolve the issue. I also tried logging in as another user that has the same profile as my user and I was able to access DLRS from their account with no errors.

@afawcett

**Comment by Szandor72** [comment]
I found this in our documentation about the error - can you tell me if this applies to your org/situation? 

> **INVALID_SESSION_ID: Invalid Session ID found in SessionHeader: Illegal Session faultcode=sf:INVALID_SESSION_ID faultactor=**. This can occur when your using the Manage Child Trigger button or editing rollups via the Manage Lookup Rollup Summaries tab. Solution is to disable the 'Lock sessions to the IP address from which they they originated.' setting under Session Settings under Setup. Salesforce documentation notes the following 'This option can inhibit various applications and mobile devices.'. Note this issue only applies while configuration changes are being made with the tool, especially via the Manage Lookup Rollup Summaries (see release notes v2.0). Once rollups are configured this issue does not apply during rollup calculations.

**Comment by jessicatownsend** [comment]
@Szandor72 Thanks for your response, I tried changing that setting briefly but the error still appeared. This setting has been enabled since before DLRS stopped working for us and DLRS is still working for the other user so I'm not sure that is the issue. The only other thing that has happened recently is that the org has had multi-factor authentication enabled but my user was left out of the permission set that was created to require it. Have you heard of multi-factor authentication causing an issue with DLRS?

**Comment by jessicatownsend** [comment]
@Szandor72 following up on this. I tried your solution again but this time I logged out and logged back in again after changing the setting. It worked and I'm able to access DLRS again, thank you so much for your help!
