### ISSUE TITLE
Winter 22 Testing

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#1070]
Before all the new automation is complete, we want to do some testing of DLRS 2.14 in Winter 22 as well as the latest Beta of 2.15

- Get latest Beta package installed in a Preview Org
- Do some UI testing with Case, etc. rollups

**Comment by Szandor72** [comment]
I could install and do a simple RollUp on Acc/Opp with a successfully deployed Trigger. Will now hand over to other QE people.

**Comment by Riley-Schill** [comment]
Successfully installed 2.15 (Beta 8) in a Winter 22 dev org. 

Created rollups from Case to Contact, deploying the below Triggers and Classes. 
- Apex Trigger dlrs_CaseTrigger is installed.
- Apex Class dlrs_CaseTest is installed.
- Apex Trigger dlrs_ContactTrigger is installed.
- Apex Trigger dlrs_ContactTest is installed.

Tested the following:
Calculation Mode: Realtime & Scheduled 
Calculation Sharing Mode: System & User
Adding Relationship Criteria 
Populating a number field using Count 
Populating a text field using Concatenate 

Didn't run into any issues during testing - Good to deploy.
