### ISSUE TITLE
dlrs_SBQQ_SubscriptionTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field

### ISSUE THREAD

**Issue by revathikalai** [SFDO-Community/declarative-lookup-rollup-summaries#1076]
Occured at CPQ - Post Install Script.
One or more failures occurred in last execution of apex job SBQQ.RootIdSetterParentSubscriptions. 1 failed out of 1 on 2021-09-28 06:15:41. Extended Status: First error: Update failed. First exception on row 0 with id a1H3L000000HpLHUA0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_SBQQ_SubscriptionTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field SBQQ__Contrac....

**Comment by aheber** [comment]
@revathikalai, Are you able to provide the additional text on the invalid field API name? Is this a package upgrade or something else? What other criteria can you provide to reproduce the problem?

What rollups do you have configured on the SBQQ_Subscription object? Do any of them reference a field that doesn't exist on either the parent or child? Is there something that is deprecated in that package with the install? Do you have any custom test code included in the rollups?

There is a very good chance this is a configuration problem. DLRS doesn't have any inherent awareness of SBQQ thus being pulled into that context would require configured rollups. That is why I'm asking about your specific configuration.

I'm happy to do what I can here but you'll likely get better support in our Trailhead group, https://trailhead.salesforce.com/trailblazer-community/groups/0F9300000009O5pCAE.
