### ISSUE TITLE
A calculate job for rollup 'XXXX' is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again.

### ISSUE THREAD

**Issue by matcipten** [SFDO-Community/declarative-lookup-rollup-summaries#1083]
Hi everybody,

I have installed DLRS (v 2.14) but this problem occurs for all rules set when I run full calcolate;

"A calculate job for rollup 'XXXX' is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again."

![Cattura](https://user-images.githubusercontent.com/80886679/137527409-a8cceae5-b4b6-4fa1-9e2b-0fe69cdcfeab.PNG)

there is no Rollup Calculate Jobs record.

Any suggestions?

Thanks

**Comment by jackyle92** [comment]
I am facing with same issue. Hi @matcipten  have you resolve this problem?
Can anyone could help me on this? 

Many Thanks.

**Comment by jackyle92** [comment]
Hi, 
I update the link if some people need help with this problem.
https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000DcWlpSAF
Thanks

**Comment by aheber** [comment]
@jackyle92 thanks for providing the link!
