### ISSUE TITLE
CampaignMember - AccountId Field not working with "Account as CampaignMember" enabled

### ISSUE THREAD

**Issue by SaschaLoeffler** [SFDO-Community/declarative-lookup-rollup-summaries#1098]
In our org we enabled "Accounts as CampaignMember" which is adding the field "AccountId" on the CampaignMember Object. As there are no "Standard Fields" on Campaign like "Number of Accounts in Campaign" and "Number of Accounts in Hierarchy" we wanted to create the rollups, to calculate this, but actually it seems the field "AccountId" is not getting accepted by DLRS Tool: 

Setup Settings: 
![image](https://user-images.githubusercontent.com/42643096/138415858-de2ca861-9f13-4e6c-86b5-313d100f68ba.png)

CampaingMember Object: 
![image](https://user-images.githubusercontent.com/42643096/138415950-910ab806-89f4-459b-a885-0ec2d2193171.png)
Note: I ensured that field level access is there for the relevant profiles 

Rollup and Error Message: 
![image](https://user-images.githubusercontent.com/42643096/138416083-a4d99118-fb3a-4256-98ac-32ee221f2c3f.png)

**Comment by dicksonstephen** [comment]
@SaschaLoeffler - we typically provide our best support through our Trailhead Community (https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) but I'll do my best to help you here.

If I'm understanding your situation correctly, then the field specified in Relationship Field should still refer to the relationship between Campaign and Campaign Member.  CampaignMember is related to Campaign via the "CampaignId" field on the CampaignMember object.  "AccountId" here would actually represent the "Field to Aggregate", i.e. the field on the CampaignMember that we're trying to count/rollup.  So try using "CampaignId" as the Relationship Field and "AccountId" in the Field to Aggregate.
