### ISSUE TITLE
Read Only profile is no longer available after Spring '21: RollupControllerTest fails

### ISSUE THREAD

**Issue by maujood** [SFDO-Community/declarative-lookup-rollup-summaries#1099]
**Describe the bug**
RollupControllerTest queries the profile named `Read Only` to create a user for running test. For orgs created after Spring '21, this profile will no longer be available and this test will fail. For orgs created _before_ Spring '21, a release update will convert this profile to a custom profile.

Additionally, new scratch orgs have a `ReadOnly` custom profile instead of a `Read Only` custom profile, which once again is causing this test class to fail. This has been reported as an issue that is under review and may be corrected soon. https://trailblazer.salesforce.com/issues_view?id=a1p4V000001v0dEQAQ

However, even if this issue is corrected, this test class would fail in newer orgs. I signed up for Health Cloud org two weeks back and just verified that the Read Only profile is not present in that org.

**To Reproduce**
Deploy the source to a scratch org or to an org created after Spring '21 (such as a new DE org) and run the test class RollupControllerTest. it will fail with a System.QueryException on line 387 since no profile with this name exists.

**Expected behavior**
Expected the test class to pass.

**Screenshots**

**Additional context**
From the release notes: https://help.salesforce.com/s/articleView?id=release-notes.rn_profiles_and_perms_read_only_new.htm&type=5&release=230

**Comment by davidmreed** [comment]
Closed in #1103
