### ISSUE TITLE
Integrate DLRS into TDTM ..... vs Deploying DLRS Trigger -

### ISSUE THREAD

**Issue by andyjb** [SFDO-Community/declarative-lookup-rollup-summaries#1112]

**Comment by Riley-Schill** [comment]
Deployed Trigger on Case and Account 
Tried to create a rollup using 'Count' to count the number of cases on the account based on the CaseNumber field but it doesn't seem to be populating any data. When switching it to concatenate the CaseId it worked as expected. 
![image](https://user-images.githubusercontent.com/48393803/159971901-f48874f9-53c3-482c-858b-6dcced365974.png)


Deployed Trigger on Contact and Campaign Member 
Tried to count the number of campaigns the contact is a member of and place that count in the 'Title' field but ran into a apex error (see attached). When I changed to rollup to concatenate the text it worked as expected, I'm guessing this is a bug unrelated to this release? 
![image](https://user-images.githubusercontent.com/48393803/159971931-f5ae2885-a092-459e-ad20-c945decf6288.png)
![image](https://user-images.githubusercontent.com/48393803/159971952-a29a150c-d08f-445f-a826-94d367f350ce.png)

**Comment by Riley-Schill** [comment]
QE Approved

Created a scratch org off of the main branch and verified the apex classes in the scratch org contained the updates from this pull. After successfully installing NPSP deployed the triggers on the Contact and Account objects and proceeded to test the SUM, Count and Concatenate functionality. While testing I did not encounter any issues.

Note the previous testing issues were not related to NPSP, they are just a general limitation of DLRS.
