### ISSUE TITLE
Apex scheduled job named rollup_Updates_Opp_with_Entities_from_EM failed to run rolllup

### ISSUE THREAD

**Issue by magnihotri11** [SFDO-Community/declarative-lookup-rollup-summaries#1115]
Receiving Error on Scheduled Job

Error: Invalid rollup m001o000000TQu8AAG not found. Review the error, rollup definition and/or delete the Apex Scheduled job under Setup. Check if the rollup still exists via the Manage Rollup Summaries and/or Lookup Rollup Summaries tabs.

**Comment by magnihotri11** [comment]
Hi Heber,

If possible can we please connect on call. I can share the screen.

Regards,
Manila Agnihotri
Salesforce Functional Business Analyst
Solution Centre and Support, ICTD
Cell: +91 8650469944
14X SALESFORCE CERTIFIED | 2X COPADO CERTIFIED

**Comment by aheber** [comment]
I don't think I could have time for a call until next week at the soonest. Are you able to answer some of my questions or help me understand how you've attempted to debug this so far and what additional information you've discovered?

**Comment by magnihotri11** [comment]
I have tried to check the logs but in logs we are not getting the error.

**Comment by aheber** [comment]
@magnihotri11 were you able to get this resolved?
