### ISSUE TITLE
DLRS updates using System mode still trigger validation rules based on the User that triggered the update

### ISSUE THREAD

**Issue by mwhenry** [SFDO-Community/declarative-lookup-rollup-summaries#1117]
**Describe the bug**
DLRS updates using System mode still trigger validation rules based on the User that triggered the update.

**To Reproduce**

1. On Object A, a validation rule is set that prevents a Community User from updating Object A if a Status is a particular value. It includes the following parameter: TEXT($User.UserType)='PowerCustomerSuccess'.
2. A Community User uses a Screen Flow to create and edit records on Object B. Object B is a child object of Object A. The Screen Flow is set to: System Context Without Sharing—Access All Data. It is deployed in the Community with a button. 
3. A DLRS updates values on the parent Object A when a child Object B is created, edited, or deleted. It is set to Realtime and System.
4. When a Community User uses the Screen Flow to create a record of Object B, the DLRS attempts to update Object A. This triggers the validation rule and the operation fails.

**Expected behavior**
It was expected that when a Community User used the Screen Flow to create a record of Object B, the DLRS would update Object A without triggering the validation rule (because both the Flow and DLRS were set to System.

**Screenshots**

**Additional context**

**Comment by aheber** [comment]
@mwhenry, we normally do our support through our Trailhead Community group, https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p. In the future we'd recommend you start there for help troubleshooting issues.

I'm not sure I'm following along on why this is an issue. I believe this is completely standard behavior. If you have a real-time rollup then that rollup will execute in the user context that initiated the transaction, your community user in this case. That will trip the validation rule and reject the entire transaction.

My recommendation is probably to move this to a scheduled rollup, in the community user context it will create a schedule record for that parent ID which can then be processed by a scheduled job at a future date, the benefit here being you can choose which user owns that scheduled job and thus who the action user is while updating the parent record.

Hope that helps.

**Comment by mwhenry** [comment]
@aheber ok, thank you. I suppose my misunderstanding is that I thought, by setting both the Flow and the DLRS to run in System context, then they would not run in the user context.
I appreciate the link to the Trailhead group too, thanks!

**Comment by aheber** [comment]
Yes, "System" mode is more about does the system respect Field Security, Object Security, and Record Sharing security rather than being about changing to a "system" user.

Good luck and I hope you can get it configured in a way that works for you.

**Comment by aheber** [comment]
Marking as closed but feel free to comment and I'll gladly respond as I can, we can reopen if it looks like we need to handle it as an issue in the project.
