### ISSUE TITLE
DLRS Account Trigger issue

### ISSUE THREAD

**Issue by JMatos99** [SFDO-Community/declarative-lookup-rollup-summaries#1119]
Hello, 

I received an error from the DLRS Account Trigger as below:
caused by: System.DmlException: Update failed. First exception on row 0 with id 00158000005jFDKAA2; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_AccountTrigger: execution of AfterUpdate

Can someone help with this please? 

Many thanks!

**Comment by aheber** [comment]
@JMatos99 are you still experiencing this issue? Would you be able to provide additional details related to your configuration? I don't think the error message above gives us much to go on for debugging.

Thanks!

**Comment by JMatos99** [comment]
Hi, thank you we are not experiencing the issue anymore.

Best regards,

Joana

**Comment by aheber** [comment]
Thank you for the response! Glad it is no longer a problem.
