### ISSUE TITLE
Create Clone functionality for Lookup Rollup Summaries

### ISSUE THREAD

**Issue by dicksonstephen** [SFDO-Community/declarative-lookup-rollup-summaries#1121]
**Is your feature request related to a problem? Please describe.**
When creating multiple Lookup Rollup Summaries of a similar nature it would save the end-user time if they could clone an existing Lookup Rollup Summary to use as a starting point.

**Describe the solution you'd like**
It has been suggested that the clone functionality take the form of a "Clone Button" in line with the other buttons on the Manage Lookup Rollup Summaries page.

**Describe alternatives you've considered**
N/A

**Additional context**
This came out of the UI/UX survey and has been deemed a developer-approved quick win.
@MelanieTolomeo

**Comment by coriobriensfdo** [comment]
Love this idea :)

**Comment by msakarettnaborg** [comment]
What I do as a workaround is go to the Custom Metadata records and clone them, make my changes, and save.
From: coriobriensfdo ***@***.***>
Date: Tuesday, January 11, 2022 at 10:46 AM
To: SFDO-Community/declarative-lookup-rollup-summaries ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [SFDO-Community/declarative-lookup-rollup-summaries] Create Clone functionality for Lookup Rollup Summaries (Issue #1121)
External Email:


Love this idea :)

—
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSFDO-Community%2Fdeclarative-lookup-rollup-summaries%2Fissues%2F1121%23issuecomment-1010156631&data=04%7C01%7Cmsakarett%40nab.org%7Cf3bafa411d4a478254ad08d9d521f861%7C9e1dc664276a46108317b9c9fa01904d%7C0%7C0%7C637775164142250508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aARID6gPkVbweXCCq5ybdOawG%2B3v5I62ugyMfWxOHwQ%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARUIOLLPZAITYW3EQ4KKMH3UVRNHZANCNFSM5LWX3CCA&data=04%7C01%7Cmsakarett%40nab.org%7Cf3bafa411d4a478254ad08d9d521f861%7C9e1dc664276a46108317b9c9fa01904d%7C0%7C0%7C637775164142250508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WK%2F53Kg%2FGX%2FaFZfPr27I0KBH%2B656XDembqTxL3OGvLI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmsakarett%40nab.org%7Cf3bafa411d4a478254ad08d9d521f861%7C9e1dc664276a46108317b9c9fa01904d%7C0%7C0%7C637775164142250508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=u9VFosLNGvOlHAEQG3bbMi%2BkzkP5Bivp3YRYs%2Bj30CU%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmsakarett%40nab.org%7Cf3bafa411d4a478254ad08d9d521f861%7C9e1dc664276a46108317b9c9fa01904d%7C0%7C0%7C637775164142250508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=AxZkm1yomh8zmEsMKyAJZOzEv%2FKYRniuCwtR7pvCH9A%3D&reserved=0>.

**Comment by sfenton3** [comment]
#1184

**Comment by aheber** [comment]
This is available in the new LWC wizard, starting in v2.21.
