### ISSUE TITLE
Clearer UX when trying to save a Summary as "Active" before the child trigger is deployed

### ISSUE THREAD

**Issue by dicksonstephen** [SFDO-Community/declarative-lookup-rollup-summaries#1123]
**The pain point:**
When creating a new rollup summary on an object for the first time (and therefore the trigger hasn't been deployed yet), the "Active" checkbox must be unchecked in order for the "Manage Child Trigger" button to appear when the user clicks "Save". Otherwise, the user receives the below error which doesn't mention the Active checkbox and can't be resolved since the "Manage Child Trigger" button hasn't appeared yet.

![image](https://user-images.githubusercontent.com/54549339/149186738-93f4e55e-47ad-466e-93f3-4fd43c535e1b.png)

**Possible Improvements:**
Per @JimBTek - it would be helpful if there was a clear indicator on the page as to whether or not the child trigger is deployed. 
 
Then we could also amend the error message to inform the user that you can't activate a DLRS until the child trigger is deployed. And the "Active" checkbox needs to be unchecked when saving in this scenario.

**Comment by JimBTek** [comment]
@dicksonstephen can you update this task to also include making it clear that it is already deployed if it is.  Perhaps a Green indicator if deployed, yellow if not, and red if not and required.

**Comment by dicksonstephen** [comment]
@JimBTek - Ok, I updated the original task
