### ISSUE TITLE
Default both Wizards to Calculation Mode: Scheduled / Async

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#1127]
# Problem
Currently DLRS defaults the Calculation Mode field to "Realtime".  It would make sense to default to "Scheduled" instead.  Also see #1122 as we are proposing to change "Scheduled" to "Async" 

# Solution
Please document a solution and review it before implementing. 

# Logic Assertions

# QA

# Implementation

**Comment by JimBTek** [comment]
this is tied to the rollupJob optimizer check and save warnings.

**Comment by aheber** [comment]
The new LWC wizard is defaulting to Scheduled thought it uses a different name.
