### ISSUE TITLE
View all rollups and their schedules in a list

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#1131]
# Problem
It is hard to manage many DLRS rollups. Users would like to see all their rollups in a list, and their schedules.  Power users can just go to the custom metadata list view, but is there a nice clean way to show the same or similar on the welcome page or in a new tab that lets you see them all and clicking edit on a record takes you to the new wizard?

# Solution
build a solution here and discuss it before implementing

# Logic Assertions

# QA

# Implementation

**Comment by Riley-Schill** [comment]
QE Approved 
![image](https://user-images.githubusercontent.com/48393803/174841463-d15af552-a726-4f61-8257-58d0255a6630.png)
