### ISSUE TITLE
Change New Wizard to allow edits as well

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#1136]
# Problem
The new community-provided Wizard is only for insert/creation of a DLRS record.  If we want to focus on it and have it be the default we need to enhance it to also load and edit existing DLRS records.

# Solution
Can we move it into the main page to solve this? 

Please determine a solution here and discuss before implementing.

# Logic Assertions

# QA

# Implementation

**Comment by aheber** [comment]
The "New" VF wizard is being deprecated and the new LWC wizard should be doing most of this now.
