### ISSUE TITLE
CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY:dlrs_Sales_Order_DataTrigger: execution of AfterInsert  caused by: System.QueryException: Non-selective query against large object type (more than 200000 rows). Consider an indexed filter or contact salesforce.com about custom indexing.

### ISSUE THREAD

**Issue by rachurigithub** [SFDO-Community/declarative-lookup-rollup-summaries#1139]
**IMPORTANT NOTE** The Chatter Community Group can be found [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p). If it is an issue that you need help on configuring the tool or have an unexpected error its really worth seeing if the community can help first before raising a GitHub issue. Most users hangout in the Chatter Community Group. Otherwise if prefer you can post here and still link in the Chatter Community Group.

**Comment by aheber** [comment]
@rachurigithub this is related to your configuration and the Relationship Criteria Fields in use. If possible can you add additional filters to give it an indexed fields to filter the query on?

Lots of good information available, this is a good starting point.
https://salesforce.stackexchange.com/questions/194897/system-queryexception-non-selective-query-against-large-object-type-more-than
