### ISSUE TITLE
DLRS Access Issue for Non System Admins

### ISSUE THREAD

**Issue by AndrewGulino** [SFDO-Community/declarative-lookup-rollup-summaries#1146]
When non system admins try to access the Manage Lookup Rollup Summaries tab they receive the below error "Salesforce Metadata API connection failure, click the link below to configure."
System admins do not receive this error. Users in question have both Lookup Rollup Summaries permission sets.
Any advice?

**Comment by AndrewGulino** [comment]
@afawcett any thoughts?

**Comment by aheber** [comment]
@AndrewGulino the current functionality of this system uses your Salesforce session to access Salesforce's API, specifically those with Admin-required features for updating Custom Metadata as well as deploying custom Triggers.

To make this work the actuating user would need to have the required level of access to reach those APIs and make those changes.
