### ISSUE TITLE
Wizard "Clear" fields

### ISSUE THREAD

**Issue by MelanieTolomeo** [SFDO-Community/declarative-lookup-rollup-summaries#1157]
**Is your feature request related to a problem? Please describe.**
When I set up a summary in the wizard, I fill out the top fields. Then I go and select a Parent Object and click Confirm. After I confirm, there's no way to get out of that selection without refreshing.

**Describe the solution you'd like**
"Clear" buttons next to the "Confirm" buttons for Parent Object and Child Object. They would clear all the details below the field but none of the details above

**Describe alternatives you've considered**
Multi-page wizard

**Additional context**
Not a show-stopper, but could be useful for people who misunderstand what object is parent v. which is child at first. Or if someone selects Account Contact Role instead of Account by accident.

**Comment by aheber** [comment]
Closing as this related to the now deprecated "new" VF wizard.
