### ISSUE TITLE
Issue coming while deploying the trigger

### ISSUE THREAD

**Issue by umeshbeti** [SFDO-Community/declarative-lookup-rollup-summaries#1161]
HI there,
basically, we trying to deploy child trigger, after the record is created,  **it works in the partner developer org,** but when we are installing it in the production org(have the namspace), which is enterprise mostly and child trigger button-> and deploy button boom, it throws an error(attached screenshot),

**Expected behavior**
it should actually deploy the trigger we have another on the same object but we are skipping that using Custom setting
like this

accessing customer setting here and storing int one variable first.
if(CustomSetting.skip__c==true){
// all trigger logic
}else{
// if custom setting field is set to false trigger logic to run
}

**Screenshots**
this white colored is the Package Namespace that is in production org.
![image](https://user-images.githubusercontent.com/32977066/157036319-5659bb81-4481-4e85-b447-6a37985c6646.jpg)

ERRORS:

Error:
dlrs_namespace_TXNTest.testTrigger System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, namespace.TxnTrigger: execution of BeforeInsert caused by: System.NullPointerException: Argument cannot be null. (System Code): [] (dlrs) Class.dlrs_namespace_TXNTest.testTrigger: line 11, column 1

Warnnings:
dlrs_namespace_TXNTrigger:Test coverage of selected Apex Trigger is 0%, at least 75% test coverage is required
Use of the Lookup Rollup Summaries tab is still functional but no longer being enhanced. Consider using the Manage Lookup Rollup Summaries tab.

**Comment by aheber** [comment]
@umeshbeti DLRS configuration allows for customized test methods. It sounds like you may want to use that features to disable your other trigger prior to executing the record save in the test code.
