### ISSUE TITLE
DLRS Test class failing

### ISSUE THREAD

**Issue by navthaleamol** [SFDO-Community/declarative-lookup-rollup-summaries#1182]
I deployed the dlrs package in sandbox org using url link.

 

now if i deploy anything to org, when it runs test classes , all dlrs test classes are failing

 

error: 

System.DmlException: Insert failed. First exception on row 1; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, Field does not exist.: [dlrs__AggregateResultField__c] Stack Trace: (dlrs)

 

field dlrs__AggregateResultField__c is part of package installed , i can see the field in custom metadata, custom metadata access is also present for admin profile by using this profile we are doing deployment.

**Comment by dicksonstephen** [comment]
Hi @navthaleamol - Just to clarify, are you receiving the error when you deploy configurations/metadata to the sandbox, or do you receive the error then deploying configurations/metadata to production?  Have you installed DLRS in production?
