### ISSUE TITLE
LastName field is required on Contact Object when installing trigger for a Custom Object (Child) and Contact(Parent)

### ISSUE THREAD

**Issue by Neteesh** [SFDO-Community/declarative-lookup-rollup-summaries#1186]
@afawcett @davidmreed @afawcettffdc 

**Describe the bug**
We are trying to install a trigger related to a Custom Object(which is a child object, in our case) and a Contact object(a Parent object). In the test class of the DLRS package, a new Contacts is being created as a part of the deployment (Child trigger) and it is failing because Lastname is required from Salesforce.

Can you please address this issue?

**To Reproduce**

1. Set up the Roll-up summary record
2. Click on Manage Trigger Button
3. Redirect to auto-generated code page
4. When trying to deploy, we are getting the error as the lastName on the Contact is a required field

**Expected behavior**
The package has to deploy without any error

**Screenshots**
![image (6)](https://user-images.githubusercontent.com/29709412/165575499-ae631913-7d96-4f29-ac3f-48c9cb683434.png)

**Comment by umeshbeti** [comment]
thanks for raising the issue @Neteesh , we are trying the same and getting the issue with last name. please let us know if anything can be done here, especially with some standard objects. @afawcett @afawcettffdc @davidmreed

**Comment by davidmreed** [comment]
Hi folks, thanks for filing a bug, but please don't directly tag multiple people. This is an open source project developed by a whole team, who may explore and triage this issue.

You'll definitely be asked to provide your version of DLRS and much more detail on reproduction steps. Screenshots of your rollup configuration will help.

**Comment by umeshbeti** [comment]
Hi @davidmreed , sorry for the earlier. 
here is the detailed information of the version package:
![image](https://user-images.githubusercontent.com/32977066/165593749-bde5d0d1-3794-40a5-a7c6-bb4f16d6c22b.png)

and 
steps are the same as above, basically after creating a Lookup summary record with the necessary field of parent and child object.
and this is the configuration 
![image](https://user-images.githubusercontent.com/32977066/165595031-ed3fc2b9-1d5b-48c8-a48c-43394eed0ab1.png)

**Comment by dicksonstephen** [comment]
Just noting that this has been added to the project roadmap for discovery and further inquiry. 

The enhancement would be to add functionality that auto-detects required fields for test classes.  The current workaround would be to adjust the test code oneself.

**Comment by Neteesh** [comment]
Thank you @dicksonstephen for adding this to your list of enhancements. Can you please let me know how do I edit the test class?

**Comment by umeshbeti** [comment]
Hi @dicksonstephen , thank you for adding this to the enhancements list.

I think the workaround won't work until we deploy the classes, I have seen that the deployed test classes can only be changed. 

since the above bug/error, we are facing is not letting us install/Deploy the test classes.

**Comment by Neteesh** [comment]
Hi @dicksonstephen Do you have an estimate on when this will be released?

**Comment by davidmreed** [comment]
You should be provided an opportunity to edit test code when you deploy a trigger using DLRS. [This article](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage) in the wiki covers in broad terms the problem here.

Please bear in mind that DLRS is a free, open source, community- and volunteer-driven effort. I don't think the project is in a position to make commitments on release of backlog items.

**Comment by Neteesh** [comment]
Hi @davidmreed, I get what you are saying and we were able to find out the error (it is happening because of the new Contact() as the Lastname field is required). Can you please let me know how/who will provide us the ability to edit the test code and add the Lastname as the parameter?

**Comment by aheber** [comment]
@Neteesh, in the rollup configuration page, at the bottom, is a large text area where you can inject the content of the function that will be used to generate the test code. Instantiating a Contact with the Lastname would be appropriate to add in that field. Once that is done you would use the Manage Child Trigger button to deploy the modified test code as well as the trigger.

On that Manage Child Trigger page you should see a preview of what will be deployed, you can leverage that to be confident that what you configured creates a valid test class.

`dlrs.RollupService.testHandler(new Contact(LastName = 'hello');`

![image](https://user-images.githubusercontent.com/2173116/166705933-f7182e0c-fbb9-4945-ac6d-d5df3c514568.png)

![image](https://user-images.githubusercontent.com/2173116/166706011-b2fa3cde-7553-4b99-9dfe-42143badee9f.png)

Hopefully that is a good start if not resolves your problem. Please let me know if you run into any additional problems.

**Comment by Neteesh** [comment]
Hi @aheber, thanks for the information. I'm not sure what version you got this screenshot from but the version we are using 2.15. We are not able to see separate fields for Test Code (child object) and Test Code (parent object), instead we are only seeing one field Test Code and if we add this statement dlrs.RollupService.testHandler(new Contact(LastName = 'hello'); in that field, it is capturing on the child object and not actually on the Parent object (which is the Contact object in our case). Please help me understand. 
![image (4)](https://user-images.githubusercontent.com/29709412/166734687-1741055b-951a-43b1-b826-aeed6613d703.png)

**Comment by aheber** [comment]
@Neteesh, apologies for missing that you're working with Contact as the parent object.

I'm also on 2.15 in my environment. 

What I'm seeing suggests that you're using the Custom Object [LookupRollupSummary__c](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/tree/main/dlrs/main/objects/LookupRollupSummary__c) to configure your rollups. The project still supports those objects but they are deprecated in favor of the [LookupRollupSummary2__mdt](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/tree/main/dlrs/main/objects/LookupRollupSummary2__mdt) custom metadata type. 

Typically you'll manage these through the `Manage Lookup Rollup Summaries` tab in the `Declarative Lookup Rollup Summaries` app.
![image](https://user-images.githubusercontent.com/2173116/166797722-fcf0bd30-7356-42f4-9f8c-ea243c5e04ed.png)

You can have a mix of both record types but my recommendation is to start with the one that is giving you trouble, convert it to the new type in a sandbox, and test being able to modify the test code to a point that everything works for you.

Not sure how much additional supporting information is in this Wiki page but passing it along as an additional resource.
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/wiki/Challenges-with-Code-Coverage

**Comment by umeshbeti** [comment]
> @Neteesh, in the rollup configuration page, at the bottom, is a large text area where you can inject the content of the function that will be used to generate the test code. Instantiating a Contact with the Lastname would be appropriate to add in that field. Once that is done you would use the Manage Child Trigger button to deploy the modified test code as well as the trigger.
> 
> On that Manage Child Trigger page you should see a preview of what will be deployed, you can leverage that to be confident that what you configured creates a valid test class.
> 
> `dlrs.RollupService.testHandler(new Contact(LastName = 'hello');`
> 
> ![image](https://user-images.githubusercontent.com/2173116/166705933-f7182e0c-fbb9-4945-ac6d-d5df3c514568.png)
> 
> ![image](https://user-images.githubusercontent.com/2173116/166706011-b2fa3cde-7553-4b99-9dfe-42143badee9f.png)
> 
> Hopefully that is a good start if not resolves your problem. Please let me know if you run into any additional problems.

Thanks to everyone on this thread, we have solved the issue using the above solution given. Happy to help if anyone facing the same issues.
