### ISSUE TITLE
DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa)

### ISSUE THREAD

**Issue by ingepepe** [SFDO-Community/declarative-lookup-rollup-summaries#1191]
**IMPORTANT NOTE** The Chatter Community Group can be found [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p). If it is an issue that you need help on configuring the tool or have an unexpected error its really worth seeing if the community can help first before raising a GitHub issue. Most users hangout in the Chatter Community Group. Otherwise if prefer you can post here and still link in the Chatter Community Group.

Hey guys,

Is there a way to go around the mixed DML error using DLRS? Something similar to https://automationchampion.com/2022/04/17/how-to-fix-mixed-dml-operation-error-2/

**Comment by aheber** [comment]
@ingepepe can you provide some details on what you're trying to do? That would help us to better suggest what you need to have happen.

Depending on what you're experiencing and what objects you're working with, you may need to use another calculation mode, such as Scheduled or even Scheduled Full Calculate.
