### ISSUE TITLE
Self Rollup Summary

### ISSUE THREAD

**Issue by ingepepe** [SFDO-Community/declarative-lookup-rollup-summaries#1192]
**Is your feature request related to a problem? Please describe.**

> I can't use a formula to compare a record with the rest of the records in the same object

**Describe the solution you'd like**

> Instead of counting records on a child object, I would like to count records on the same object. For example, on the object Timesheets, I want to populate a field Overlaps with the count of timesheet records with the same combination of Contact and Job as the current timesheet record, that have their start or end date between the current record's start and end dates.

**Describe alternatives you've considered**

> So far I have to export the data and use analytics tools like Power BI or Tableau

**Additional context**

**Comment by aheber** [comment]
@ingepepe unfortunately this is not something that DLRS is going to be able to help with. It is designed to move data along relationship fields and it doesn't sound like there are relationship fields between these objects. This request is out of scope for this tool, I'm sorry.

I'm not aware of any way to do what you're asking aside from a custom built Flow or Trigger to act on the record when it is saved and compare and update it's neighbors. Keep in mind this is a tricky situation and it will be challenging to avoid things like cross-update race conditions or circular record updates.
