### ISSUE TITLE
Professional Edition not supported anymore?

### ISSUE THREAD

**Issue by SaschaLoeffler** [SFDO-Community/declarative-lookup-rollup-summaries#1197]
Hi, we tried to deploy the Child Trigger to use the Scheduled Rollup, but actually when trying to deploy, we receive the following error message: 

classes/dlrs_TaskTest.cls-meta.xml (Line: null: Column:null) : Not available for deploy for this organization
classes/dlrs_TaskTest.cls (Line: null: Column:null) : Not available for deploy for this organization
triggers/dlrs_TaskTrigger.trigger-meta.xml (Line: null: Column:null) : Not available for deploy for this organization
triggers/dlrs_TaskTrigger.trigger (Line: null: Column:null) : Not available for deploy for this organization

Is that known already? In the Issues i found, that process builder is not supporting the Apex Action anymore, but Scheduled should still work. Now it seems that this app is not working anymore with professional edition?

**Comment by aheber** [comment]
You won't be able to use triggers in PE edition but I believe you can use Flow. PE hasn't been tested in a long time and I'm not sure how well supported it is right now.

If you did get it working or take another crack at it, please report back.
