### ISSUE TITLE
Manage Child Trigger Button not appearing for DLRS

### ISSUE THREAD

**Issue by MaxinitoEl** [SFDO-Community/declarative-lookup-rollup-summaries#1204]
This is a brand new install in my full sandbox. All the videos that walk you through the process have buttons that I do not have. Manage Child Trigger for one. I am unable to use this app as a result. Each time I complete all the fields, I'm told I need to run Manage Child Trigger, but where? Thanks!

![DLRS](https://user-images.githubusercontent.com/101673920/171941264-a778d540-4480-4de0-b1c9-3c7594a60f53.PNG)

**Comment by MaxinitoEl** [comment]
No. After I completed the first one, I couldn't save it because of this issue. So just now, I tried it again, and it states that "only Date/DateTime/Time/Numeric fields are allowed for Sum, Max, Min and Avg. What about Currency? It's not liking Currency.

**Comment by aheber** [comment]
I think I need more details about what you're trying. Please attempt to complete the fields but without setting the option for "Active," If that still fails to save then please let me know the resulting error message and give me some idea of your chosen configuration.

Thanks!

**Comment by MaxinitoEl** [comment]
Maybe I wasn't clear. I'm good now. I didn't know I had to save first, then the Manage Child Trigger button would appear, deploy the trigger, after which time I could activate it. I've done that, so I'm good. Thanks again!

**Comment by aheber** [comment]
Oh, great! Glad you have it all working.
