### ISSUE TITLE
Test Triggers Packaged in 2.13 and 2.14

### ISSUE THREAD

**Issue by cwarden** [SFDO-Community/declarative-lookup-rollup-summaries#1205]
The [test triggers](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/tree/main/dlrs/main/triggers) in the repo are included in the dlrs managed package versions 2.13 and 2.14
 
This results in unnecessary queries for the DLRS metadata when Account/Task/Contact/Opportunity DML operations occur.

```
$ force query "SELECT NamespacePrefix, TableEnumOrId, Status, Name FROM ApexTrigger WHERE NamespacePrefix = 'dlrs' AND Name LIKE '%test%Trigger' ORDER BY Name"
 Name                      | NamespacePrefix | Status | TableEnumOrId
---------------------------+-----------------+--------+----------------------
 RollupServiceTest2Trigger | dlrs            | Active | dlrs__LookupChild__c
 RollupServiceTest3Trigger | dlrs            | Active | Account
 RollupServiceTest4Trigger | dlrs            | Active | Task
 RollupServiceTest5Trigger | dlrs            | Active | Contact
 RollupServiceTestTrigger  | dlrs            | Active | Opportunity
 (5 records)
```

**Comment by Szandor72** [comment]
Thanks for bringing this to our attention, @cwarden 

The triggers were added to 2.13 by mistake. They use `Test.isRunningTest()` in all instances so we are curious to learn how you are impacted. 

Is the following correct: This impacts you during Test runs/Deployments with Test Runs? More broadly: Where are you hitting limits or obstacles due those triggers?

**Comment by cwarden** [comment]
> Thanks for bringing this to our attention, @cwarden
> 
> The triggers were added to 2.13 by mistake. They use `Test.isRunningTest()` in all instances so we are curious to learn how you are impacted.
> 
> Is the following correct: This impacts you during Test runs/Deployments with Test Runs? More broadly: Where are you hitting limits or obstacles due to those triggers?

Yes, I hit the query row governor limit when running tests in unpackaged code that creates an Account, Contact, and Opportunity during a single method invocation.

Perhaps add boolean static variables that are set in the tests for these triggers so the triggers can short circuit when the DLRS tests aren't being run.

**Comment by JimBTek** [comment]
# Solution

- Comment out the body of all these and deactivate them
- future release we will deprecate them

**Comment by aheber** [comment]
This should be resolved in the upcoming 2.18 release.

**Comment by cwarden** [comment]
@aheber do you have a link to the fix?  Does the fix handle upgrades as well as new installations of DLRS?

**Comment by whoisemiliano** [comment]
@cwarden I only see now the following Apex Classes on the query 

<img width="870" alt="image" src="https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/26259799/e27a627a-1dc1-4db9-a2d9-d508209dd3f6">
