### ISSUE TITLE
Populate Scratch Orgs with Seed Data

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#1209]

**Comment by JimBTek** [comment]
Riley and Sean worked on a sample data set and Sean was working on putting it into a package to auto-populate scratch orgs via Metecho or CCI.  @seanpat09 can you provide a status update and link this to a branch?

**Comment by JimBTek** [comment]
Branch: feature/qa-test-data__create-test-data

**Comment by seanpat09** [comment]
@JimBTek Here is the PR for populating QA scratch orgs with seed data: https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/pull/1218

**Comment by aheber** [comment]
I think this is resolved now.
