### ISSUE TITLE
Delete trigger not decrementing COUNT

### ISSUE THREAD

**Issue by gdemarcosSFDC** [SFDO-Community/declarative-lookup-rollup-summaries#1221]
**Describe the bug**
Record deletion on a rollup count of records with no filter (all records counted) not updating the value.

**To Reproduce**
Delete/Hard Delete a child record which was counted on the rollup field and the value doesn't decrement. Updates worked fine, tested by adding/removing the lookup value on a child record.

1. Go to Related List
2. Click on child record Delete action
3. Navigate to rollup field / refresh page (ensure caching is off)
4. See number not modified by delete

**Expected behavior**
The number should have decremented by 1

**Comment by aheber** [comment]
@gdemarcosSFDC could you provide some details on your rollup configuration? Out of the box this should be properly supported. The most often cause of this situation is when the checkbox for all records is checked on the rollup config. This will cause the system to include deleted records in the rollup calculation when it should not.

If we can review your rollup configuration and still determine that there might be a fundamental problem then we can start to dig down into logs and figure out what is happening.

In the future, this isn't our usual channel for support. We recommend connecting with the Trailblazer Community Group for DLRS for support requests. Thanks!
