### ISSUE TITLE
BUG: Collection Size Exceeds 1,000 in new wizard

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#1223]
# Problem
when hitting the button to load the new wizard in a real client org we hit the Collection Size limit in VF

![image](https://user-images.githubusercontent.com/1176347/180286838-a41e643e-50c7-46f1-9680-6d3acabb8994.png)

# Solution

# Logic Assertions
Steps to test the solution works:
- run the new wizard in an org with over 1,000 objects, or somehow mock the describe object list
- confirm no list size error is received

# QA  Proof it passed QA (steps and pictures)

# Implementation

**Comment by JimBTek** [comment]
could this end up returning over 1,000 objects? 
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/blob/cc5f5c2e43e919147a6bf3b44f61d0067d2a6587/dlrs/main/classes/ManageLookupRollupSummariesNewController.cls#L255

**Comment by Szandor72** [comment]
We have added an error message in #1224

Do we need more to close this issue?

**Comment by JimBTek** [comment]
it appears that using:
`[select DeveloperName from entitydefinition where IsCustomizable = true]`  could also automatically reduce the list size by 66%.  In the real org that failed during testing we ran this and got:

False: 1397 objects
True: 613 objects

**Comment by Szandor72** [comment]
Will be shipped with 2.17 and then closed.

**Comment by Szandor72** [comment]
Shipping with 2.17
