### ISSUE TITLE
DLRS welcome page does not lead to new github site

### ISSUE THREAD

**Issue by MelanieTolomeo** [SFDO-Community/declarative-lookup-rollup-summaries#1235]
**Describe the bug**
In 2.17, on the DLRS welcome page, under documentation,

_Documentation: You can learn more about this tool by reading the documentation here._

it leads to the github repo and not the new website.

**To Reproduce**

1. Go to the Welcome tab
2. Find the documentation area

**Expected behavior**
link leads to new documentation github site

**Screenshots**
Don't know how to attach, sorry.

**Additional context**
The page looks great otherwise!

**Comment by stephenbrown1** [comment]
This is in the welcome page (https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/blob/main/dlrs/main/pages/welcome.page) - line 70.
