### ISSUE TITLE
API Name (Lookup Summary Unique Name) enhancements

### ISSUE THREAD

**Issue by MelanieTolomeo** [SFDO-Community/declarative-lookup-rollup-summaries#1236]
* Limit the field input to 40 characters. Don't let people enter more than that # of characters
** Currently people get this error when they save: "Error occured processing component dlrs__LookupRollupSummary2.Opportunity_Count_Distinct_Products. Value too long for field: MasterLabel maximum length is:40 (FIELD_INTEGRITY_EXCEPTION)"
* Autopopulate unique name from Lookup Rollup Summary Name, replacing spaces with underscores
* Potentially change "Unique Name" to "API Name"
* Potentially change "Lookup Rollup Summary Name" to "Lookup Rollup Summary Label"

**Comment by mkolodner** [comment]
@Szandor72 - I just installed the 2.18 Beta 11 into a scratch org. I am able to put well over 40 characters into the Lookup Rollup Summary Name field, when I tab off that field it does not autofill the Lookup Rollup Summary Unique Name field, and of course when I try to save I get the error because my name is too long. 
Either I don't understand what this fix is supposed to do, or perhaps it's not made it into the beta package?

**Comment by mkolodner** [comment]
Update: I see that these enhancements exist _in the Wizard_ but do not appear to exist for the regular DLRS creation page. (Which is what I use as a long time user...)
There is now inconsistency where the API name in the wizard is labeled "Lookup Rollup Summary API Name" but on the regular Manage Lookup Rollup Summaries tab view it's labeled "Lookup Rollup Summary Unique Name."
I don't think this should probably slow the release, but it does seem to be an issue...

**Comment by Szandor72** [comment]
True, only new wizard was updated.

Do I understand correctly that you are (only) requesting a field label
change for the new wizard? The new wizard should use the same label as the
old one?

That's certainly doable. Please confirm if I should make the change.

Sz

**Comment by mkolodner** [comment]
I'm not actually requesting anything because I'm not sure I want to slow progress and also not sure it's my place.
I am just working on the documentation and making sure I understand the situation.

**Comment by Szandor72** [comment]
@MelanieTolomeo What do you think? Should we change the labels?
