### ISSUE TITLE
List view enhancements

### ISSUE THREAD

**Issue by MelanieTolomeo** [SFDO-Community/declarative-lookup-rollup-summaries#1237]
Great job on the list view Scott! Here are some things that may be interesting to add:

- Add Active checkbox
- For SCHEDULED APEX JOB NAME - note somehow that this is for _Full Calculate_ only
- For the regular Scheduled mode -> Show if RollupJob class is scheduled, when RollupJob is scheduled for, etc.

**Comment by aheber** [comment]
We've added a new list view interface as part of the LWC wizard. That should include more data but things like the Scheduled information are likely not going to be on that list in the future.
