### ISSUE TITLE
Add Activation step for wizard

### ISSUE THREAD

**Issue by MelanieTolomeo** [SFDO-Community/declarative-lookup-rollup-summaries#1238]
Currently there is an Active checkbox that's greyed out on the wizard. I think this could be confusing to the end user. 

Perhaps we want to have a Next page of the wizard for an activation step. This would includes the step of creating/activating the apex trigger&test class if it's not there. And if the run mode is Scheduled, the person can either schedule the RollupJob Apex Class or schedule a Full Calculate before activating as well.

**Comment by aheber** [comment]
The new LWC wizard takes care of this.
