### ISSUE TITLE
"Net Zero Cloud" objects are not supported, requires API version >= 54.0

### ISSUE THREAD

**Issue by davidlb** [SFDO-Community/declarative-lookup-rollup-summaries#1248]
**Describe the bug**
The Spring'22 release introduced new core objects for Net Zero Cloud. These objects are not available in DRLS, I guess it's because it requires an API version >= 54.0

**To Reproduce**
1. Enable Net Zero to get specif objects in your org 
2. Try to use one of them (the list of objects is available here : https://developer.salesforce.com/docs/atlas.en-us.netzero_cloud_dev_guide.meta/netzero_cloud_dev_guide/netzero_cloud_std_objects_parent.htm)

**Expected behavior**
To be able to use standard objects with DRLS

**Comment by aheber** [comment]
The upcoming 2.18 release should include the necessary API updates to resolve this.
