### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by sharicarlson13** [SFDO-Community/declarative-lookup-rollup-summaries#1263]
Existing README is being moved to the documentation repo / pages site. The README in this repo needs to be updated to reflect a more standard development README. 

At the Documentation planning meeting it was decided that a member of the dev or engineering team should take on this update.

**Comment by coriobriensfdo** [comment]
@sharicarlson13 FYI I took the liberty of updating the readme to remove the content and at the same time added some placeholder details about the project, how to access docs/install, and how to contribute which will show up once my PR gets approved. (#1261 )

**Comment by coriobriensfdo** [comment]
Closing for now as it's updated - dev can add more content later if they like via a new issue.
