### ISSUE TITLE
Error when merging Cases

### ISSUE THREAD

**Issue by tonykidd** [SFDO-Community/declarative-lookup-rollup-summaries#1264]
Hello, our Org has a few DLRS roll ups and they have been working fine. Yesterday I added a couple of new Roll Ups and now I am getting errors when trying to merge Cases. 

I thought it would be fairly easy to just deactivate the new roll up on the Case and look to add more criteria to filter out merged cases but deactivating the roll up did not help. I deleted the roll up still did not help. When I remove the Case trigger I can again merge Cases but as soon as I deploy the trigger again I get the error. 

I have deactivated all roll ups with Case as the child but Im still getting the error.

I just updated the app to 2.17 and am still getting the error when the Case trigger is deployed even with no active roll ups on Case.

Any help would be much appreciated. 
<img width="584" alt="DLRS merge error" src="https://user-images.githubusercontent.com/35230911/198679020-5092d286-70c3-4394-9e6f-ae5f94c6ca11.PNG">

**Comment by aheber** [comment]
@tonykidd 
Are you referencing `RelatedToId` anywhere? Maybe in one of the DLRS configurations? Could be on Case or EmailMessage maybe?

Something in your configured rollups appears to be referencing a field that isn't valid for the Case object and evaluating that logic is what is crashing the trigger, which is what caused that error.
