### ISSUE TITLE
Can 2 Separate DLRS roll up to the same Field on the same Object?

### ISSUE THREAD

**Issue by jasonniebauer** [SFDO-Community/declarative-lookup-rollup-summaries#1268]
### Discussed in https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/discussions/1265

<div type='discussions-op-text'>

<sup>Originally posted by **zack0816** October 30, 2022</sup>
We are working in Financial Service Cloud (FSC) and are attempting to do a summary rollup of total Assets Under Management. We need two separate DLRS configurations to run that both roll up to the same field on the same object. (One for Household Accounts. Another for Business Accounts.) Is that possible?

Here is how we have it configured:

Household - Total AUM Primary Owner

Parent Obj: Account
Child Obj: FinServ__FinancialAccount__c
Relationship Field: FinServ__Household__c
**Relationship Criteria**: FinServ__Household__c != NULL 
Field to Aggregate: FinServ__Balance__c
Aggregate Operation: Sum
Aggregate Result Field: FinServ__TotalAUMPrimaryOwner__c
Calculation Mode: Realtime

Business - Total AUM Primary Owner

Parent Obj: Account
Child Obj: FinServ__FinancialAccount__c
Relationship Field: FinServ__Household__c
**Relationship Criteria**: FinServ__Household__c = NULL
Field to Aggregate: FinServ__Balance__c
Aggregate Operation: Sum
Aggregate Result Field: FinServ__TotalAUMPrimaryOwner__c
Calculation Mode: Realtime

When individually activated, each DLRS configuration works as expected. But when both are active, the Household is updated as expected and the Business account incorrectly sets AUM to $0. 

**It appears DLRS isn't designed for multiple Summaries that Rollup to the same field on the same object. Does anyone know specifically why that is?** 

Regardless of the reason, could a solution be to change the Calculation Mode from 'Realtime' to 'Process Builder', then have a record-triggered flow activate the 'Household - Total AUM Primary Owner' DLRS. Then wait a minute before activating 'Business - Total AUM Primary Owner' DLRS?

Does anyone see an issue with this solution?

FYI @jasonniebauer </div>

**Comment by JodieM** [comment]
No, the DLRS will run and update ALL records in FinServ__TotalAUMPrimaryOwner__c. Then the next one will run and update ALL records in FinServ__TotalAUMPrimaryOwner__c again. You need to have the two rollups roll up to different fields, then do a formula field to sum the two rollup fields together. Annoying, but it's the only way.

**Comment by jasonniebauer** [comment]
@JodieM thank you for providing this insight. We are utilizing Financial Services Cloud and the out-of-the-box rollup automation for AUM (Assets Under Management) will not work with our setup, so we've had to investigate other solutions and attempted to use DLRS. Unfortunately, creating a custom formula field is not a possibility for us. There are a handful of standard fields where the formula cannot be modified and Financial Services Cloud has quite a bit of out-of-the-box design based around these standard fields. For example, AUM is a formula field that combines values from 2 other standard fields (Total AUM Primary Owner + Total AUM Joint Onwer). If we go with the custom fields and formulas then we'd be setting ourselves up to replace a good chunk of standard fields and functionality which we're looking to avoid. Any other thoughts or ideas on how to work around this limitation?

**Comment by JodieM** [comment]
Aha, Interesting... I got some insightful information today... Here's what I think you do... you have the two rollups, which is the starting point... then schedule them using the Schedule Full Calculate button, and enter a Where Clause in there. So rollup one is Total AUM Primary Owner and it will run where Account Type is Household... and rollup two is Total AUM Primary Owner and it will run where Account Type is NOT Household. (I'm not sure of the Fin Services Architecture but I'm sure there must be an IsHousehold field on the Account record like there is in NPSP).

**Comment by jasonniebauer** [comment]
@JodieM I'm currently testing your suggestion and have the automation scheduled to run daily. I included a WHERE clause so that each DLRS filters account records based on type, which is what I had tried to do in the relationship criteria that was failing. I'll let you know how the testing goes. Thanks again for the suggestion!
