### ISSUE TITLE
Reduce Execution Mode Confusion - Active Checkbox

### ISSUE THREAD

**Issue by sfenton3** [SFDO-Community/declarative-lookup-rollup-summaries#1274]
**Is your feature request related to a problem? Please describe.**
The Active checkbox is confusing to users. We should block the active checkbox until the user has deployed triggers depending on the calculation mode or/and give a large warning to deploy triggers. Do we need to have it checked for triggering scheduled item creation? It is needed for Process Builder / Flow?

**Describe the solution you'd like**
Default the Active checkbox to Active and give a large warning if in Realtime or Scheduled that the trigger needs to be deployed. We also need a large warning that the apex RollupJob class needs to be scheduled. 

**Describe alternatives you've considered**
Do we need to abstract out the schedule/actions from the rollup definition? This would allow the rollup definition to be separate from the calculation mode. The end user would then have to setup the calculation mode separately and we could create a guided experience for this.

**Additional context**
Active checkbox is confusing to users and execution mode is unclear. A combination of documentation and UX improvement could solve this.

**Comment by aheber** [comment]
This is part of the new LWC wizard, available in v2.21.
