### ISSUE TITLE
Improvements to New Wizard - Edit Mode and LWC

### ISSUE THREAD

**Issue by sfenton3** [SFDO-Community/declarative-lookup-rollup-summaries#1276]
**Is your feature request related to a problem? Please describe.**
There needs to be an Edit Mode - Is it technically possible to deploy metadata from LWC? The current limitation of the new wizard comes from needing the sessionId to create/delete CMDT for rollups and deploy the triggers for objects. We also need to make sure any new implementation of sessionId usage passes [security review.](https://salesforce.stackexchange.com/questions/389121/call-salesforce-api-from-apex-and-not-fail-security-review)

**Describe the solution you'd like**
The new wizard should be able to create the edit Lookup Rollup Records - as well as do anything the old wizard can do. We should be taking advantage of LWC for improved performance and out-of-the-box support for additional components. 

**Describe alternatives you've considered**
Develop the new wizard to have edit ability but redirect to the VF pages that require a sessionId or embed the VF into the LWC. 

**Additional context**
The current New wizard could be improved by adding edit capability and performance improvements. Before deciding on VF page for the new wizard we should consider if it is possible to implement with LWC.

**Comment by aheber** [comment]
New LWC wizard available starting v2.21
