### ISSUE TITLE
Improvements to New Wizard - Replace global describe

### ISSUE THREAD

**Issue by sfenton3** [SFDO-Community/declarative-lookup-rollup-summaries#1277]
**Is your feature request related to a problem? Please describe.**
The new wizard makes extensive use of the global describe to get the relationship between objects dynamically. This is a considerable performance hit - load time is upward of 4-5 seconds on object heavy orgs. 

**Describe the solution you'd like**
Implement an algorithm that only searches for the top 50-100 standard objects and all custom objects. We can then implement an optional feature to type in the exact parent and child relationships.

**Describe alternatives you've considered**
We can move to LWC and use the components that are prebuilt to filter results in the object describe. This would take advantage of the performance improvement that come with LWC.

**Additional context**
We need to improve the performance of the new wizard. Is the global describe needed to generate the list or could we a SOQL query with the entitydefinition object?

**Comment by aheber** [comment]
New LWC wizard is available starting v2.21
