### ISSUE TITLE
Professional Edition Link

### ISSUE THREAD

**Issue by KrissLugo** [SFDO-Community/declarative-lookup-rollup-summaries#1281]
There used to be a PE link but now it;s not available. Is PE no sorported now?

**Comment by coriobriensfdo** [comment]
@KrissLugo you can install DLRS from our [main installer page](https://install.salesforce.org/products/dlrs/latest) rather than from direct links in GitHub. Let us know in our Trailblazer group if you have any issues installing in PE as that's where we work support.

**Comment by KrissLugo** [comment]
I was able to installed it but the APEX that allows the recalculate is not available under flows, I cannot for sure manage the trigger child.
