### ISSUE TITLE
Real-time updates stopped working

### ISSUE THREAD

**Issue by tbouscal** [SFDO-Community/declarative-lookup-rollup-summaries#1286]
We have several real-time updates and all of them have stopped working since the last update.
Recent changes were installing the latest version and reassigning ownership of some records.

I recreated all the rollups we have yesterday and the new ones aren't functioning properly either.  We have close to 70 rollups from Quote Line to Quote.  Some of them are vital to getting deals closed so this is our highest priority.

**Comment by gingerbyte** [comment]
I was on version 2.11 and couldn't get QLI edits to rollup to standard Quote fields (calculate works perfectly fine), after hitting my head against the wall for a bit, I upgraded to 2.17 and suddenly all the rollups are working perfectly.  Which version are you on?

**Comment by aheber** [comment]
@tbouscal were you able to find a cause for the issue? Were you able to attempt on the most recent version and see if that helped with the problem?

**Comment by tbouscal** [comment]
@aheber I’m no longer working in that org, but I think it was resolved.
