### ISSUE TITLE
No Jobs Scheduled but "Lookup Rollup Summary Schedule Items" Being Created

### ISSUE THREAD

**Issue by jessicapethick** [SFDO-Community/declarative-lookup-rollup-summaries#1300]
Have completely reinstalled the app, deactivated and reactivated all rollups, have uninstalled and reinstalled child triggers and all rollups are in realtime mode but summary schedule items are still being created. Help?

**Comment by sfenton3** [comment]
What does the `CalculationMode` field look like for the CMDT records? They should all be set to Realtime. If any are set to scheduled and active it will create scheduled items. You can look in the list view for custom metadata records to see what the value is set to.

**Comment by jessicapethick** [comment]
Yes @sfenton3 all the calculation modes are set to realtime. They have always been set to realtime, and were never scheduled. Yet it appears to be creating a scheduled item every time a record is updated. At the time I noticed, DLRS scheduled items were using 20% of the org's storage limits. I cleared them out, and yet they haven't stopped creating. What other reason could there be for this? 

<img width="836" alt="Screen Shot 2023-02-27 at 7 27 20 am" s
<img width="1437" alt="Screen Shot 2023-02-27 at 7 27 05 am" src="https://user-images.githubusercontent.com/114837427/221443978-9af36308-cf29-4add-8eec-906067c42f5c.png">
rc="https://user-images.githubusercontent.com/114837427/221443966-7689dd15-0aef-473f-ab90-20333b8e6f49.png">

**Comment by sfenton3** [comment]
Copy and paste the lookup rollup summary: m029q... And m025g... into the url. Those are your lookup rollup summaries that are scheduled.

**Comment by sfenton3** [comment]
It's also possible to add scheduled items to the scheduled item queue through apex - though it is not typical.

**Comment by sfenton3** [comment]
I'm going to close this out - If you have any other questions feel free to re-open this issue.

You can also go to the Trailblazer community group for DLRS with [questions](https://trailhead.salesforce.com/trailblazer-community/groups/0F9300000009O5p?tab=discussion&sort=LAST_MODIFIED_DATE_DESC).

**Comment by JimBTek** [comment]
@sfenton3 i just saw this in person at SED and it is very weird. not old records data records and all the new CMDT ones are set to Realtime.

**Comment by jessicapethick** [comment]
Hi Jim,

Was great meeting you at the SED event, and thanks for having a look at
this while there.

Has there been any update on how we might fix it?

Kind Regards,
* Jessica Pethick *


* Meandr Consulting *
Phone: +1 (307) 761 9239 <+1(307)7619239>
Email: ***@***.***
Website: www.meandr.com.au


<https://www.linkedin.com/in/jessicapethick/>
<https://twitter.com/jessicapethick>
<https://wa.me/61424113754>

**Comment by aheber** [comment]
@jessicapethick I think this has gotten left behind a bit. Is this still happening? If so I'd love to understand what is going on and hopefully find a fix.

**Comment by aheber** [comment]
I'll be happy to work on this if you come back to it. In the mean time I'll mark it as closed.

**Comment by bbromberg** [comment]
@aheber just wanted to reach out to say I'm having the same issue (Schedule Items being created for "Realtime" rollups) and I haven't been able to figure out why. Spot checked a few to confirm they don't have any associated Scheduled Jobs that are active. At least some of them I can confirm have always been set to Realtime and not Scheduled. Any troubleshooting tips would be appreciated! 🙏

**Comment by aheber** [comment]
@bbromberg can you replicate these on demand or do they just show up sporadically?

Have you checked both the older Custom Object rollup definitions as the newer Custom Metadata definitions?

I don't have the ability to do a support login to debug the packaged code but if you could capture a debug log of it occurring we might be able to find a culprit, or at least a hint.

**Comment by aheber** [comment]
I'm going to mark this as closed. I think there is a reasonable explanation but I'll open another ticket for the docs team to make sure this is clearly laid out in the docs. 
It would also be good if the config management screens made it clear you'd need a scheduled job if the parent is mergable.
