### ISSUE TITLE
Rollup calculates only when Full Calculates, no when I update a record

### ISSUE THREAD

**Issue by isita** [SFDO-Community/declarative-lookup-rollup-summaries#1309]
I have a rollup that only works when I run a full calculate job. It doesn't get update when I update a child record.

It sums the amounts on won opportunities closed  during the Last fiscal year for non anonymous accounts and  with  empty lookup field on the opportunity. I haven't use the NPSP Customizable Rollups as the rollup as additional filters I cannot configure.

Calculation mode: Real Time
Calculation Sharing Mode: System
Relationship Criteria:
Customfield__c = null  and CloseDate = LAST_FISCAL_YEAR AND (not([Account.Name](https://account.name/) LIKE 'Anonymous%')).

I run the full calculate and the outcome is correct.
I update the Opp amount or the close date and the Aggregate Result Field value returns always 0.

**Comment by aheber** [comment]
@isita can you confirm the Trigger is deployed for the Opportunity?

That is the only reason i can think of why realtime configured job wouldn't work correctly the way you described.

**Comment by grigorian** [comment]
I am seeing the same issue after upgrading to the latest package version (from a very old version!), it is as if the Relationship Criteria Fields are being ignored.  FYI rollup is aggregating a formula field, with the dependent fields added to 'Relationship Criteria Fields'.  Rollups are being triggered fine where they are directly aggregated (i.e. a directly aggregated field triggers a rollup).  

I'll work my way back through versions to find one that works.

**Comment by aheber** [comment]
@isita or @grigorian do either of you still have examples of this?

Would you be able to share your configuration records and version?

**Comment by grigorian** [comment]
@aheber I think I've now worked around all the issues I had.   I'm not sure if this is still an issue or not.

**Comment by aheber** [comment]
@grigorian thanks!

**Comment by aheber** [comment]
I'm going to mark this as closed. If there are additional problems or questions please direct them to the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) for better support.
