### ISSUE TITLE
Add managed package install link to release notes

### ISSUE THREAD

**Issue by TehNrd** [SFDO-Community/declarative-lookup-rollup-summaries#1310]
The latests versions of DLRS require using Salesforce.org MetaDeploy to install. This app requires a ton of permissions, see image below. As part of a large enterprise org we try to limit the amount of connected apps for security purposes and this app requires a lot. All of these permissions seem excessive to install a managed package.

Would it be possible to include the managed package link in the release notes like before?

Or if not, perhaps provide the reasoning here as to why it is not included?

![image (36)](https://user-images.githubusercontent.com/1007085/223823383-7fe8ea60-5b24-4d63-a98f-9ef6fd38e27e.png)

**Comment by sfenton3** [comment]
Hello, if you go to the packages section of the GitHub repo it will have all beta and prod releases. You can install from a direct link using these links:

https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/releases
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/releases/tag/release%2F2.17

Does that resolve your question?

**Comment by sfenton3** [comment]
I'll make a PR to add latest release in GitHub readme. I'll link that to this and close it out
