### ISSUE TITLE
Delete doesn't Trigger when we use dlrs as apex action in Flow  and calculation mode set to Process Builder

### ISSUE THREAD

**Issue by amithkumar1592** [SFDO-Community/declarative-lookup-rollup-summaries#1315]
Hi,

I have created a flow where i have referenced DLRS as apex action in 'creation and updation' and it works fine. Calculation mode is set to 'Process Builder'. But, when i use the same apex action in 'Delete' Event of the flow, it is not showing the proper count  on the parent record when i delete the record in the org. I didn't set Calculation mode is set to 'Real Time' as i was getting SOQL query and there were too many field values to be updated on the Parent Record. Hence, I have set the Calculation mode to 'Process Builder' and used scheduled path in flow during 'creation and updation' event

Thanks,
Amith Kumar

**Comment by aheber** [comment]
@amithkumar1592, can you confirm that you have a Flow setup to execute on delete? Similar to https://help.salesforce.com/s/articleView?id=release-notes.rn_forcecom_flow_fbuilder_trigger_flow.htm&release=228&type=5

I haven't personally tried this setup so I may have to do that and see what I can find before I can be of much help here.

**Comment by amithkumar1592** [comment]
Hi,

Thanks for your reply. Yes, I have a flow to set up on delete. But, I would like to it using apex action(DLRS) in flow before delete event.

Thanks,
Amith Kumar

**Comment by JimBTek** [comment]
Are you sure it's BEFORE Delete and using the Scheduled Flow path?  Screenshots would be helpful. Thanks

**Comment by aheber** [comment]
Closing as inactive, please reopen if we need to look at this further.
