### ISSUE TITLE
New Wizard - Refactor Apex Controller for LWC. Stub out a Controller with empty Methods, or Method Start/Stop Comments to make GitHub merging easier.

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#1316]
# Problem
We need to create all new Apex Controller methods for the new wizard without breaking the existing methods. 

We want to avoid using the metadata API to create and update the custom Metadata configuration records. Use the APEX Metadata API instead. 

# Solution

# Logic Assertions
Steps to test the solution works:
- 1

# QA  Proof it passed QA (steps and pictures)

# Implementation
- Sandbox
- Objects and Fields
- Automation
- Permissions
- Github PR
- Documentation

**Comment by aheber** [comment]
Done and shipped as part of v2.21
