### ISSUE TITLE
New Wizard - Create new Object Search & Select LWC

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#1317]
# Problem
The current picklist is too large and can time out

# Solution
- user types 3+ chars
- return results that can be picked from
- have apex store a static object list and then have LWC search the static and return filtered results 
- It should allow the user to search by Label or API name of an object. 
- it needs to optionally accept a parent object, and use this as an additional filter to return objects that are allowed to be children. 

# Logic Assertions
Steps to test the solution works:
- 1

# QA  Proof it passed QA (steps and pictures)

# Implementation
- Sandbox
- Objects and Fields
- Automation
- Permissions
- Github PR
- Documentation

**Comment by aheber** [comment]
Done and shipped as part of v2.21
