### ISSUE TITLE
New Wizard - Health Check component

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#1319]
# Problem
users need to know if their rollup is actually scheduled and healthy

# Solution

- show if there is a child trigger or not
- show if the Apex schedule job is running and what it's schedule is
- if there is a Scheduled Full Calculate apex job, display those as well (could possibly be multiple)
- can we show if there are active flows/PBs that reference DLRS invocables

- Show Log Errors
- Show Number of Scheduled Item records waiting to be processed

Also make sure this works on the Optimizer page / Tools page and how can we see it on a list?

# Logic Assertions
Steps to test the solution works:
- 1

# QA  Proof it passed QA (steps and pictures)

# Implementation
- Sandbox
- Objects and Fields
- Automation
- Permissions
- Github PR
- Documentation

**Comment by aheber** [comment]
Done and shipped as part of v2.21
