### ISSUE TITLE
dlrs auto generated trigger test class is triggered while deploying to target sandbox using sfdx.

### ISSUE THREAD

**Issue by VijayakumarVeera** [SFDO-Community/declarative-lookup-rollup-summaries#1333]
**Describe the bug**
We are getting test class failure issue while deploying our custom classes to target sandbox. we are using sfdx command for deployment and we are running the sfdx command with RunLocalTest. If we use RunLocalTest class it should validate only for the custom code in our org but one dlrs test class triggered and its getting failed.

Command Used for Deployment:
sfdx force:source:deploy -x manifest/package.xml -l RunLocalTests

**To Reproduce**
While running the above command.

This is the stack trace - 

<html>
<body>

dlrs_SBQQ_QuoteLineTest | testTrigger | System.DmlException: Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, QuoteLineTrigger: execution of BeforeInsert caused by: System.NullPointerException: Attempt to de-reference a null object Class.QuoteLineTriggerHandler.updateNatureOfProjecPriceforProposalLine: line 200, column 1 Trigger.QuoteLineTrigger: line 22, column 1: []Stack Trace: (dlrs) Class.dlrs_SBQQ_QuoteLineTest.testTrigger: line 11, column 1
-- | -- | --

</body>
</html>

**Comment by aheber** [comment]
@VijayakumarVeera unfortunately this wouldn't be a problem with DLRS itself. It is an issue in your local environment. I'll provide some context for this answer as well as a few suggestions but I would advice you to reach out to the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) for additional support, there are considerably more individuals with a much greater variety of experiences that can provide assistance there. I'll be closing this issue after I provide the details as we try not to keep support tickets open on this repo.

Triggers deployed by DLRS are equivalent to custom code added by your organization, they are not managed code. This means they are considered part of your local collection of Apex and part of what needs to be passing for `RunLocalTest`.

As for why that class throws that error, that is a good question. Without seeing how your rollups are configured, or having a better understanding of your environment, I would guess that the Test code in that class doesn't provide an isolated and valid test scenario for that object. That will likely need to be corrected. The basic default test code is naïve and tries to create a record without any field data, if that is incompatible with your environment that can often cause issues like what you've reported above.

If this is passing in Production and not in this sandbox I would start there, maybe there is data available in production that isn't available here? Is it possible that new code is creating a new expectation? Is `updateNatureOfProjecPriceforProposalLine` part of your custom code or part of the `SBQQ` package? It is making assumptions about the presence of something and not finding it available, thus the NullPointerException.

I'm sorry I can't be more help as I won't know your environment and it's requirements. Hopefully the Trailblazer Community Group has some more experience with this specific scenario and can shed some light.
