### ISSUE TITLE
System.NullPointerException: Attempt to de-reference a null object (dlrs) 

### ISSUE THREAD

**Issue by micksel** [SFDO-Community/declarative-lookup-rollup-summaries#1346]
Hi everyone,
Just updated from an earlier version and now we are getting errors from all our existing dlrs, the worked fine in the earlier version.

Did I miss anything, regarding the upgrade, I just installed the package, assign the permission set to my admin user.

This error occurred when the flow tried to create records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_InternshipTrigger: execution of AfterInsert caused by: System.NullPointerException: Attempt to de-reference a null object (dlrs) Trigger.dlrs_InternshipTrigger: line 7, column 1. 

Line 7 -> dlrs.RollupService.triggerHandler(Internship__c.SObjectType);

**Comment by aheber** [comment]
@micksel, can you provide some additional information such as what version you were on previously and what version you are on now that you updated?

Can you describe the rollups that are being used where `Internship__c` is the child object?

Does this error always show up for any user on any action, or is it specific to some users or some actions?

**Comment by micksel** [comment]
I recreated all old DLRS and deleted the old ones now everything works fine.
