### ISSUE TITLE
Getting erros only when 'Deploy code to support record merging' is checked: System.SObjectException: Invalid field Incoming for Case (dlrs) 

### ISSUE THREAD

**Issue by bdsdx** [SFDO-Community/declarative-lookup-rollup-summaries#1354]
**Describe the bug**
When running a full calculate, or sometimes just updating the parent record, I get an error of this type:
```
dlrs_CaseTrigger: execution of AfterUpdate

caused by: System.SObjectException: Invalid field Incoming for Case

(dlrs)
Trigger.dlrs_CaseTrigger: line 7, column 1 : CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY ()
```

I noticed that it happens only with those two conditions:
- The Aggregate Result Field is null on the parent record
- The Child Trigger is deployed with the option "Deploy code to support record merging?" checked

I don't know if this matter, but I'm working on an environment where the Case Merge feature is active.

**To Reproduce**

1. Create at least two rollup summary rules.
![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/83812098/9e364d1f-59d0-4085-995b-2844fdfc528d)

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/83812098/889af914-0ca2-4598-85a7-13092ab98043)

2. Activate those rules and deploy the child trigger, with the option "Deploy code to support record merging?" checked
3. Verify that the Aggregate Result Field from the rules is empty (at least on the records to be tested)
4. Verify that the Case Merge feature is active on the org (not sure on this one, but it's my case)
5. Run a full calculate on one of the rule

It should create summary logs with the error like "dlrs_CaseTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field Incoming for Case (dlrs) Trigger.dlrs_CaseTrigger: line 7, column 1 : CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY () "

**Expected behavior**
No error, and correctly update the Aggregate Result Field 

**Additional context**
The error message has an inconsistency: "Invalid field Incoming for Case". It mentions the field "Incoming", which doesn't exist on the Case Object, but exist on the EmailMessage object (EmailMessage is one of the Child Object of my rollup summary rule).

I found a similair issue here: #https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/issues/1038

**Comment by aheber** [comment]
I think this is tied to #1038, please direct comments there.

If possible, please confirm that the issue is still present and report the version as a comment on that issue.
