### ISSUE TITLE
Hyperforce Lighting migration readiness: Direct reference to NA1 causes false-positive

### ISSUE THREAD

**Issue by aheber** [SFDO-Community/declarative-lookup-rollup-summaries#1357]
**Describe the bug**
The Welcome VF page uses an NA1 url to redirect to a help page. Would be good to change this so it doesn't trigger the warning as well as is a better long-term URL pattern for the purpose of helping the user understand Remote Site settings.

**To Reproduce**
Run the `Lighting migration readiness` and look at the hard-coded URLs.

**Expected behavior**
Any URL used to get the user to a help page should be done in such a way that it doesn't depend on this org or any other org to do so.
Might be best to have this page link to the Docs site and if needed, the Doc site can link to the Help pages while also adding additional context.

**Comment by aheber** [comment]
Enhancement Source:
https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000KeJnV

Code Context:
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/blob/13afe8bc47dfb13830304521080ee9f435153e85/dlrs/main/pages/welcome.page#L92

**Comment by sfenton3** [comment]
Should we send this to docs site and make a new page. This will allow us to fix the hyperforce url issue and get people used to using the docs site.
