### ISSUE TITLE
Checkbox Roll Up

### ISSUE THREAD

**Issue by Blairadams14** [SFDO-Community/declarative-lookup-rollup-summaries#1369]
Hi! I am trying to figure out what to select Aggregate Operation for my roll up fields. We created a training object (child account) and have checkboxes that need to also be checked off / summarized on the Parent account. It doesnt matter if this specific field is checked off once or 3 times depending on how many training objects are created. Its would be a summary on the account so that our CS team can identified if certain people are trained.

**Comment by aheber** [comment]
@Blairadams14 I've generally handled this as a number field on the account. COUNT aggregate operation on the ID field of the child. The Relationship Criteria then filters on the checkbox being TRUE.

It isn't the TRUE/FALSE on the account that indicates anyone having access but if the number is not zero then they have someone.

**Comment by aheber** [comment]
I'm going to mark this as closed, if you need additional help I'll direct you do the Trailblazer Community Group for DLRS. You'll get significantly more support there. We try and do our best to keep the GitHub issues about changes that need to be made in the code.
