### ISSUE TITLE
Teach RollupController how to find the latest API version

### ISSUE THREAD

**Issue by aheber** [SFDO-Community/declarative-lookup-rollup-summaries#1373]
**Is your feature request related to a problem? Please describe.**
When deploying triggers to the platform, DLRS uses a constant API version that needs to be updated with each release. It would be better if that API version was auto-determined so DLRS is able to execute rollups in preview or newly released environments without the DLRS team having to release an updated version and needing installed orgs to manually update.

**Describe the solution you'd like**
Using the "Versions" REST API hit `/services/data/` we can get a list of all the API versions the current org supports. Processing the JSON from this we can find the largest API version and install things at that newer version without having to have it hard coded.

We should have a reasonable fallback so that if that process has any problems we still resolve back to the previously manually updated version number.

**Comment by Szandor72** [comment]
To clarify: we will still have to do an API Upgrade for the package each SF release so that the describe calls we use return all newly added sObjects, correct? 

We won't have to remember to update `RollupServiceController.cls` after this has been merged.

**Comment by sfenton3** [comment]
After Merge QA:

![1  Deploy Account Triggers](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/2f4277ec-b130-41a1-b7c3-2d49451e73db)
![2  Check api version is latest](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/4032b6c6-573d-46ee-99b1-44c432474f0e)
![3  Drop API version down to 57](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/ba007f4e-d1b2-4863-8e1f-30387d23527c)
![4  Confirm API version is 57 0](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/3aeece84-2482-4ecb-aae5-de28be09a4ab)
![5  Remove trigger](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/1d34f2be-70fa-4942-a412-241a057803a2)
![6  Re-deploy trigger](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/92d62514-64d9-4937-a29d-dd798906077d)
![7  confirm api version is 58](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/2ed06b87-7bf7-47d9-9e42-41acd9abc73f)
![8  Current api version](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/b65d7fa7-a7ca-4132-88f0-8a91afdc3a05)


| QA - Reason  | QA - Picture |
| ------------- | ------------- |
| 1. Deploy Account Trigger | ![1  Deploy Account Triggers](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/2f4277ec-b130-41a1-b7c3-2d49451e73db)   |
| 2. Check API version for Account Trigger is current 58.0 | ![2  Check api version is latest](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/4032b6c6-573d-46ee-99b1-44c432474f0e) |
| 3. Change trigger API version to 57.0 | ![3  Drop API version down to 57](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/ba007f4e-d1b2-4863-8e1f-30387d23527c)  |
| 4. Confirm API version is set to 57.0 | ![4  Confirm API version is 57 0](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/3aeece84-2482-4ecb-aae5-de28be09a4ab) |
| 5. Remove trigger from Manage Triggers VF page |  ![5  Remove trigger](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/1d34f2be-70fa-4942-a412-241a057803a2) |
| 6. Re-deploy account trigger | ![6  Re-deploy trigger](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/92d62514-64d9-4937-a29d-dd798906077d)  |
| 7. Confirm API version is set to 58.0 (current version) and not 57.0 | ![7  confirm api version is 58](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/2ed06b87-7bf7-47d9-9e42-41acd9abc73f) |
| 8. Confirm org WSDL api version  | ![8  Current api version](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/20290118/b65d7fa7-a7ca-4132-88f0-8a91afdc3a05) |
