### ISSUE TITLE
Active: Apex Trigger dlrs_Object has not been deployed. Click Manage Child Trigger and try again.

### ISSUE THREAD

**Issue by peterdesio** [SFDO-Community/declarative-lookup-rollup-summaries#1386]
Description:
Impacting multiple orgs - when trying to update an existing or create a new DLRS, I am getting an error stating the child trigger needs to be deployed. I go deploy the trigger, receive a 'Deployment Complete' message at the top of the screen but still see 'Click Deploy to install the Apex Trigger......' and the Deploy button.

**To Reproduce**

1. Go to Manage Rollup Lookup Summaries
2. Select an existing or create a new DLRS
3. Configure the DLRS
4. Save, try to set to active, enter loop I described

**Expected behavior**
Child trigger should deploy 

**Screenshots**
<img width="1446" alt="image" src="https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/35781947/5a153aa5-355c-43dd-bd0b-646e0404fbcc">

<img width="1455" alt="image" src="https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/35781947/d360e260-2df5-472f-bc1b-5e1dfba47284">

**Additional context**
We are avid users of this app, and I first noticed the problem last week in a sandbox that has been upgraded to the latest Winter release.

**Comment by aheber** [comment]
@peterdesio thank you for your bug report. I believe this is likely part of #1383 which was identified as a bug in the Winter '24 sandbox release and is slated to get fixed. That issue includes the Known Issue link that you can use to see if your pod has received the necessary fixes.

I'll close this as duplicate but please let me know if you don't think this fits the known issue.
