### ISSUE TITLE
The dlrs_OpportunitySplitTrigger is generating duplicate emails in user inbox

### ISSUE THREAD

**Issue by puneeth86** [SFDO-Community/declarative-lookup-rollup-summaries#1388]
**Describe the bug**
Favorite
[Puneeth Gundlapally](https://trailblazers.salesforce.com/profileView?u=0054S0000032CCXQA2)
[The dlrs_OpportunitySplitTrigger is generating duplicate emails in user inbox](https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007CvK8dSAF)
The dlrs_OpportunitySplitTrigger is generating duplicate emails when we change the opportunity owner on the opportunity. When we change the opportunity owner we expect to get one email, but due to dlrs_OpportunitySplitTrigger after method we are getting 3 emails. As this is a package code we are not able to edit any attributes.

**Expected behavior**
How can we stop this from happening as this is part of managed package we won't be able to edit the code?

**Comment by aheber** [comment]
@puneeth86 this would be best continued in the your Trailblazer Community post. I'll respond to you there.

**Comment by puneeth86** [comment]
@aheber Thank you for the response I will be waiting for your response in trailblazer community post.
