### ISSUE TITLE
Changing the  Active DLRS owners and Reporting feature.

### ISSUE THREAD

**Issue by Satya-LIO** [SFDO-Community/declarative-lookup-rollup-summaries#1389]
Hi Team,

I got few queries in respective with DLRS Jobs. Below is the list of my queries, kindly provide an appropriate update on this.

1. I'm looking for the way to change the owner of active DLRS Jobs in a bulk, I'm unable to do that. As of now, I'm accomplishing this task by cloning the active DLRS Jobs individually(each one after the other), which is a big task when we have 100s of active DLRS job running.

2. We have generated a list view report related to DRLS Job details but in this report we didn't find the active DLRS Job list with details. Please find the attached screensots of report view where values are showing as N/A and which DLRS jobs are not in use. 
Please assist us to get this report with all active DLRS job & details.

![MicrosoftTeams-image (3)](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/145951993/390c8c13-3c55-4342-ab7a-f7721ad72305)
![MicrosoftTeams-image (4)](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/145951993/a15dc901-7cad-4695-8116-6ff8db5830ba)

3. As of now, only the DLRS job creator/ owner gets the notifications. However I'm looking for a feature which notifies about the Active DLRS jobs to all salesforce system admins in our organisation.

Looking forward to your response.

With Best Regards,
Satya

**Comment by Satya-LIO** [comment]
Hi Team,

Any update on the above mentioned issues. 
Also, we are also having a warning in our DLRS Optimizer. Could please check this error as well.
![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/145951993/fe586e95-d8a7-4874-bb9a-0555eb20357e)

Looking for some help on this. 

Thanks
Satya

**Comment by aheber** [comment]
@Satya-LIO sorry this response is coming long after your report.

Based on what I see in your screenshot it looks like you're concerned with some placeholder records in your environment. The real configuration records are Custom Metadata records that manage your configuration. That is why you have all the `N/A` values.

I wouldn't worry about those records. 

As for the emails, please open another issue only requesting that feature. I don't know when it will get developed but having a single issue with multiple requests isn't actionable for the development team.

For the scheduled items, you'll need to look at the associated Lookup Rollup Scheduled Item records and see why they are being displayed. It might be that thy are completely normal and you simply have that much record volume in a normal day. If they are very old then you might need to see what rollups are creating the records and if you have the `RollupJob` scheduled Apex active in your org to clean those up.

**Comment by aheber** [comment]
In the future we recommend support inquiries to go through the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) where there is a wonderful group of individuals who volunteer their time and talents.
