### ISSUE TITLE
Better Documentation w/ Community Contributors

### ISSUE THREAD

**Issue by JimBTek** [SFDO-Community/declarative-lookup-rollup-summaries#139]
First off,  I'm really excited about this tool.  But I'm a big believer in the importance for dead-cimple documentation for open-source tools.  

Is it OK for some of use to contribute to the currently empty WIKI to show how to use the tool? 

For example I got confused on finding the RollupJobs filter because I am new to Apex in general.  I'd be happy to document this in the wiki with screenshots.

Let me know what you think and if the community can help build more documentation.

Cheers,

Jim

**Comment by JimBTek** [comment]
Looks like I may have spoken too soon about this!  The RollupJob does exist in the main list as well if you go to the right page.  Sorry I am new to Apex in general.  

I would still love to help create wiki pages with screenshots on how to use the tool!

**Comment by wes1278** [comment]
Are you aware of the extensive blog posts that have been written about this tool? This is one of the best documented open source projects I've seen. Here are the four latest blog posts about the tool. The last one I linked even has a video.

http://andyinthecloud.com/2015/02/16/declarative-lookup-rollup-summaries-tool-dlrs-spring15-release/
http://andyinthecloud.com/2014/04/09/new-declarative-rollup-tool-release-community-powered/
http://andyinthecloud.com/2014/02/09/new-release-spring14-declarative-rollup-summary-tool/
http://andyinthecloud.com/2013/07/07/new-tool-declarative-rollups-for-lookups/

**Comment by JimBTek** [comment]
Hey Wes, I did see those and read the one to find the RollUpJob for scheduling Apex Triggers.  

But would it not be better to have that find it's way into a logically structured wiki so as the project ages and grows it's easy to find the latest compilation of that info?  I'd be happy to help do this. 

If no one else thinks it would be helpful I will concede to being out of my league! :)

Thanks again for all the greatness that exists in this.

**Comment by wes1278** [comment]
I was more just hoping those blog posts would help you get to the answer you needed. :) I'm certain we would more than welcome some additional documentation help. @JimBTek did you have any ideas for how/where you wanted to put said wiki? Do you want to just do another markdown somewhere? @afawcett any thoughts?

**Comment by JimBTek** [comment]
Yes I found the answer.  It was more because there were no screenshots and I was too unfamiliar with what I was doing so I did figure it out.

there is an empty wiki here:  https://github.com/afawcett/declarative-lookup-rollup-summaries/wiki

**Comment by JimBTek** [comment]
https://readthedocs.org is also quite nice depending on how big the docs will be.  supports per version docs as well which can be nice.

**Comment by afawcett** [comment]
Gents, i'm so pleased to get this offer, and while i thank @wes1278 for surfacing the blog links here, i do agree it's time it got more structured help behind it as well. I'm more than happy to get contributions for the wiki thank you so much! :+1:

**Comment by JimBTek** [comment]
How do you want additions to the wiki to be done?

On Tuesday, March 17, 2015, Andrew Fawcett <notifications@github.com> wrote:

> Gents, i'm so pleased to get this offer, and while i thank @wes1278
> <https://github.com/wes1278> for surfacing the blog links here, i do
> agree it's time it got more structured help behind it as well. I'm more
> than happy to get contributions for the wiki thank you so much! [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/139#issuecomment-82599806>
> .
>


-- 
Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by afawcett** [comment]
What ever you guys feel is easiest for you i don't mind, there is some docs on the GitHub Wiki approach [here](https://help.github.com/articles/about-github-wikis/) (i can make you a repo contributor if you want) or if you want to use the readthedocs.org thing thats also cool with me, i'm just super grateful for the offer, so honestly whatever you feel is best.

**Comment by JimBTek** [comment]
Andrew,  do you see there being:
Major changes in revisions
AND support for past versions?

I think something more robust like Read The Docs is good if there will be multiple versions in the wild and reasons for people to not upgrade  (Like Python 2 vs. 3,  Node .10 vs .12, etc.)
But it’s also more work.

If changes will be relatively streamlined and there is no reason for people to need/want to use old versions GitHb Wiki would be less work.  this might also be better to start for simplicity’s sake.  

With Github wiki you might want to lock it so only contributors can edit and then give us access.



Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301 <>
BTekVentures.com <http://btekventures.com/>

**Comment by afawcett** [comment]
I retire old version each time i release new ones, so this helps keep the user base on the latest. So no I don't think we need the complexity of multiple releases. So sounds like Read the Docs it is? :+1:

**Comment by JimBTek** [comment]
Oh, cool.  That would probably make the Github wiki easier since you don’t need to keep version specific docs.


Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301 <>
BTekVentures.com <http://btekventures.com/>

**Comment by afawcett** [comment]
Cool, i'll add you to the project, welcome! :+1:

**Comment by JimBTek** [comment]
Great. I am going to be re enabled it on a project this week and will take
some screenshots.

I had to turn it off when do imports on data and will have to schedule it
instead of realtime.

On Saturday, March 21, 2015, Andrew Fawcett <notifications@github.com>
wrote:

> Cool, i'll add you to the project, welcome! [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/139#issuecomment-84409351>
> .
>


-- 
Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by afawcett** [comment]
Awesome, i've marked this as an enhancement and assigned to yourself. As soon as we get something up and running, lets socialise it and attract more contributions etc...

**Comment by afawcett** [comment]
I've referenced this initiative a couple of times already in the [Salesforce Community Chatter](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) group i setup a few days ago, check it out.

**Comment by chalemic** [comment]
Jim, I'd like to help contribute to the documentation. I'd be happy to contribute articles on deployment, example rollups, etc. . .

**Comment by JimBTek** [comment]
Sounds great.  Right now I just put up an outline for getting started, and then I plan on doing a how-to on scheduling nightly rollups.  @chalemic would be good to have someone explain how to do the formulas, what the Manage Child Triggers does (how it works, when to hit the button, etc.), and how to use the Enhanced Edit.  

Also, any questions in Issues on how to do something make for good FAQs or How-Tos

@afawcett should we store wiki images here: declarative-lookup-rollup-summaries/images/  ? Or can you suggest somewhere else to centrally store screenshots, etc.

**Comment by afawcett** [comment]
Fine to store images here if that works

**Comment by afawcett** [comment]
Just reflecting on [this](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/138), maybe until we get a nice criteria UI editor we include some criteria examples in the docs?

**Comment by JimBTek** [comment]
My thoughts as well.  Can there be an issues label "add to docs"

I did add an answer to this on the new FAQ page and referenced it

On Saturday, March 28, 2015, Andrew Fawcett <notifications@github.com>
wrote:

> Just reflecting on this
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/138>,
> maybe until we get a nice criteria UI editor we include some criteria
> examples in the docs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/139#issuecomment-87202291>
> .
>


-- 
Best,

Jim Bartek
BTek Ventures, LLC
317-292-6301
BTekVentures.com

**Comment by afawcett** [comment]
Yep sounds good, feel free to add, you should be able to. :+1:

**Comment by JimBTek** [comment]
@afawcett @wes1278 sorry for being out of the loop for a bit. I'm still happy to help build out the wiki, but not paying attention to every issue at the moment.  If you mark an issue with Add To Wiki I'll be sure to document the issue!  I hope all is well. 

Andy, i'll be in Edinburgh and London here in July, not sure if you will be near either when I am. Gonna meetup with a few Salesforce folks in London as well.

**Comment by afawcett** [comment]
No problem @JimBTek will do!

RE: Meetup, drop me a Direct Message via Twitter.

**Comment by JimBTek** [comment]
i followed you on twitter. don’t think you are following back  @jimbtek.
Best,

Jim

**Comment by afawcett** [comment]
Resolved! :+1:

**Comment by aheber** [comment]
For anyone interesting in helping improve the docs head over to https://github.com/SFDO-Community-Sprints/DLRS-Documentation and give us a hand!
