### ISSUE TITLE
Wizard doesn't support selecting Task as child object

### ISSUE THREAD

**Issue by baobao917** [SFDO-Community/declarative-lookup-rollup-summaries#1390]
**Describe the bug**
Wizard throws an error when child object = Task.  
"No appropriate relationship found between these objects"

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/104730171/d4c256ed-b183-4609-82d3-c2c7a05dc60c)

**To Reproduce**

1. Click Wizard
2. Select Parent Object as a custom object and confirm
3. Select Child Object as Task and confirm
4. Error message displays and the child object picklist is removed

**Expected behavior**
Task object should be supported.  The relationship is the WhatId

**Screenshots**

**Additional context**

**Comment by aheber** [comment]
This wizard is being deprecated in v2.21, we have a new "New Wizard" in that release that uses LWC. Hopefully this will help to resolve the problem.
