### ISSUE TITLE
Rollup seems to be ignoring relationship criteria

### ISSUE THREAD

**Issue by pbillyc** [SFDO-Community/declarative-lookup-rollup-summaries#1399]
Hi. 

I have created a rollup using the RecordType.DeveloperName in the relationship criteria but the rollup is also 'working' on records with different record type. This is setup on an object with a self-relationship if that changes anything. Please see image below of setup. I have looked on this forum but I cant seem to find a solution.

<img width="1419" alt="Screenshot 2023-10-31 at 10 49 56" src="https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/149473910/21bab72b-428e-434f-b07a-fa22df9c5d0f">

**Comment by aheber** [comment]
@pbillyc, if you are still having challenges with this rollup we recommend you reach out to the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) for assistance with using DLRS. That group is very responsive and has a large community.
