### ISSUE TITLE
Create QA Recipe: Standard Object Low Ratio

### ISSUE THREAD

**Issue by acrosman** [SFDO-Community/declarative-lookup-rollup-summaries#1407]
**Is your feature request related to a problem? Please describe.**
We need stress testing of DLRS in several scenarios, to determine where DLSR can be further optimized or runs into platform limits.  To do those tests we need large volumes of data in different patterns. This task if for rollups on select standard objects with low ratios for the relationships between them.

**Describe the solution you'd like**
A Snowfakery recipe that generates data to populate the QA org as follows:

* Account
  * Pattern
    * 1 level of hierarchy (parent and child)
  * Fields
    * just name
* Contact: 
  * Pattern: 
    * 5 contacts per Account. 
  * Fields 
    * First Name
    * Last Name
* Case:
  * Pattern
    * 5 Per Account
  * Fields
    * Name
    * Description
    * Account Reference
    * Contact Reference
* Opportunities
  * Pattern
    * 5 Per Account
  * Fields
    * Name
    * Close Date (from the current year)
    * Account Reference
    * Contact Reference
    * Amount ($1,000 - $10,000)
* Opportunity Contact Role
  * Pattern
    * 2 per Opportunity
  * Fields
    * Required references to each side.
    * Randomly selected roles

**Additional context**
These patterns were worked out during the OS Commons Sprint in Chicago October, 2023

**Comment by Nickers3** [comment]
At the Feb 2024 Sprint, we have these patterns added to a snowfakery data set and also DLRS rollups to test.  Branch: https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/tree/feature/nw/rollup-lwc__feb-24-sprint-add-test-dlrs-rollups
