### ISSUE TITLE
Create QA Recipe: Custom Object Low Ratio

### ISSUE THREAD

**Issue by acrosman** [SFDO-Community/declarative-lookup-rollup-summaries#1411]
**Is your feature request related to a problem? Please describe.**
We need stress testing of DLRS in several scenarios, to determine where DLSR can be further optimized or runs into platform limits.  To do those tests we need large volumes of data in different patterns. This task if for rollups on QA using the custom objects included in the project.

**Describe the solution you'd like**
A Snowfakery recipe that generates data to populate the QA org as follows:

* QA Lookup Parent
  * Pattern:
    * 1 level of hierarchy
    * 1 "Self Relationship" to other lookup parents
  * Fields
    * Name
    * Self Relationship (lookup to QA Lookup Parent, see pattern) 
* QA Lookup Child
  * Pattern:
    * 5 children for each parent.
    * Connect 50% to another parent
  * Fields
    * Amount (1,000.00 - 10,000.00)
    * Color  (Picklist with red, yellow, green, blue)
    * Description
    * Description 2
    * Parent (always populated with a parent)
    * Parent 2 (populate 50% of the time)
    * Parent by String (populate a 18 character Id from a parent on 25% of records -- probably requires a second pass to assign. Does _not_ need to be a match for either of the other parent fields)

**Additional context**
These patterns were worked out during the OS Commons Sprint in Chicago October, 2023

**Comment by Nickers3** [comment]
At Feb 2024 sprint, added this scenario into snowfakery and DLRS test rollups. 

-Currently have it so parent 2 populates on more than half of the records, but not all.  Also do not have DLRS rollup for Parent 2 Lookup Field
-Snowfakery does not include parent by string.  I wonder if we could add an unpackaged flow to do this.
-Branch work completed on: https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/tree/feature/nw/rollup-lwc__feb-24-sprint-add-test-dlrs-rollups
