### ISSUE TITLE
Running the rollup does not update the Aggregate Result Field

### ISSUE THREAD

**Issue by JohnsonTitus** [SFDO-Community/declarative-lookup-rollup-summaries#1416]
**Describe the bug**
Running the rollup does not update the Aggregate Result Field

**To Reproduce**

1.In Manage Lookup Rollup Summaries -using Calculation Mode - Process Builder- click on 'Calculate' button, the process runs in the background without any failure.
2. But the Aggregate Result Field does not show the updated data.
Note:
Used Apex script to find the aggregate result with the same relationship criteria.

**Expected behavior**
Aggregate Result Field should be updated with the latest data when rollup summary is run.

**Screenshots**
![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/38673179/13a853a0-72a4-41ff-af2a-9cff5368fcc0)

**Additional context**

**Comment by aheber** [comment]
@JohnsonTitus I'm going to mark this as closed. If you still need help we recommend you reach out to [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) to let the larger DLRS community help.
