### ISSUE TITLE
Aggregate field of Parent object does not update

### ISSUE THREAD

**Issue by JohnsonTitus** [SFDO-Community/declarative-lookup-rollup-summaries#1417]
Aggregate field of Parent object does not update when the child records are more than 70.
Settings:
![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/38673179/3ebc094b-3b16-4c1d-8c0d-b65daf430287)

**Comment by charles-thompson-salesforce-com** [comment]
@JohnsonTitus Hi there!  We meet again!
Please help us with some more detail on your experience.

Remember that DLRS is building up a SOQL query for you, using SOQL criteria and summary functions.  SOQL doesn't have a practical limit to the number of child records to summarise.   The usual advice (to avoid data skew issues) is to limit the number of children for any individual parent to <10K records.  70 child records is a dawdle!

**Comment by aheber** [comment]
@JohnsonTitus I'm going to mark this as closed. If you are still having issues please start a new conversation on [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) to allow the larger DLRS community to help.
