### ISSUE TITLE
Migrating to Hyperforce

### ISSUE THREAD

**Issue by Eman-Bass** [SFDO-Community/declarative-lookup-rollup-summaries#1420]
Hardcoded URL preventing step verification for migrating to Hyperforce. 
This is caused on Viusalforce Page:' Welcome', the hardcoded URL is "http://na1.salesforce.com/help/doc/en/configuring_remoteproxy.htm"

**Comment by aheber** [comment]
@Eman-Bass, this shouldn't be a problem in the latest release (2.19). 

This is a false positive problem by the scanner utility, it won't break on Hyperforce even if you don't upgrade.
