### ISSUE TITLE
Child Object: Object does not exist for Nonprofit Cloud standard objects

### ISSUE THREAD

**Issue by EricRumsey** [SFDO-Community/declarative-lookup-rollup-summaries#1421]
I'm using DLRS to create rollups as part of a Nonprofit Cloud implementation. I'm getting the "Child Object: Object does not exist" error for the GiftTransaction object. The Program object is the parent and GiftTransaction is the child via relationship field Donor (Account lookup). GiftTransaction is part of the Fundraising data model. I can see the objects in the Program Management data model just fine (e.g., Program, Benefit), but not those in the Fundraising data model.

I've seen other posts here describing the same error and the solution was an updated API version in the next DLRS release. I'm assuming that's the same in this case?

I'm currently using DLRS v2.19.

I had another API-related issue with Nonprofit Cloud where the "System.QueryException: sObject type 'Program' is not supported" error was getting thrown. I understand that issue will be fixed in the upcoming v2.20.

Can I assume the "Object does not exist" error will also be resolved with v2.20?

**Screenshots**
![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/154465356/4f3ae9bd-4474-488d-97b7-2403dea1ec20)

Thank you!

**Comment by aheber** [comment]
@EricRumsey, you're correct. The GiftTransaction object is new in API v59.0 and DLRS 2.19 is at API v58.0. The code to bump to 59 is in the repo and the very next release will include support for that object.

We've also been trying to improve the project so it can support new objects without API bumps but we're not fully there yet (a few pieces are in place though!) so stay tuned over the next few releases when we will hopefully stop having this problem.

**Comment by EricRumsey** [comment]
Thank you!
