### ISSUE TITLE
Sprint and Survey Feedback for new UI 

### ISSUE THREAD

**Issue by sharicarlson13** [SFDO-Community/declarative-lookup-rollup-summaries#1423]
**Is your feature request related to a problem? Please describe.**
No - feedback from sprint to incorporate into the new UI / wizard 

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
Spreadsheet of feedback -
https://docs.google.com/spreadsheets/d/1rI5S47PU75P6ltIttZ5RexT4yc-adXxZ4LSoTftXiMQ/edit?usp=sharing

**Comment by aheber** [comment]
I think we've completed the items on here. I'm going to mark this as closed.
