### ISSUE TITLE
Scheduled DLRS processed 0 batches

### ISSUE THREAD

**Issue by jessicatownsend** [SFDO-Community/declarative-lookup-rollup-summaries#1424]
**Describe the bug**
I scheduled the apex class RollupJob to run on Jan 23, 2024 and it looks like it processed 0 batches. I can see that there are several parent records that have not been updated and their associated Lookup Rollup Summary Schedule Item records have not yet been deleted so it does seem that the job failed in some way, but I do not see any errors in the Lookup Rollup Summary Logs that indicate what the error may be. I saw issues [#417](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/issues/417) and [#394](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/issues/394) but in our case we did not use the full calculate. The DLRS was set to scheduled mode and the RollupJob apex class was scheduled to run. It ran successfully but did not update records as expected.

**Expected behavior**
When the RollupJob apex class runs, it updates the parent record and then deletes the related Lookup Rollup Summary Schedule Item record.

**Screenshots**
![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/73909222/4b6b3a8c-990f-4729-838e-fea4f31ce11b)

**Additional context**
These rollups were first created in May 2023 but the RollupJob apex class was not scheduled to run until Jan 23, 2024.

**Comment by aheber** [comment]
@jessicatownsend I know we're long past you reporting this. Were you able to get this working or do you still need some help with this one?

**Comment by jessicatownsend** [comment]
@aheber I was able to resolve this, thank you!
