### ISSUE TITLE
Full Calculate not working but Real time is working fine

### ISSUE THREAD

**Issue by kristencrane** [SFDO-Community/declarative-lookup-rollup-summaries#1434]
Full Calculate will not work but real time works fine.  Parent object is Lead, child object is task with WhoId as the relationship field

**To Reproduce**

1. Go to Manage Lookup Rollup Summaries
2. Choose Lead PYE Branded Promo/Life Event roll up
3. click on Full Calculate
4. There are 32 records that should update.

**Expected behavior**
The PYE Branded Promo/Life Event Gifts field on the Lead should update for all 32 records

**Screenshots**

**Additional context**

**Comment by aheber** [comment]
@kristencrane have you posted this issue in the [Trailblazer Community](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p)? We direct support needs there so the wider community can assist.
