### ISSUE TITLE
Wizard creates double underscore in Rollup API Name which causes error thinking it is namespace

### ISSUE THREAD

**Issue by baobao917** [SFDO-Community/declarative-lookup-rollup-summaries#1473]
**Describe the bug**
The wizard creates a double underscore in the rollup API name when typing in the label " - " (space dash space) and that causes an error to think it's referencing a namespace when trying to save the rollup

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/104730171/2d7fbeb1-c7ef-4ec7-8be1-04a48f68b757)

**Comment by aheber** [comment]
We are rolling out a new LWC based wizard in v2.21 and will deprecate the VisualForce editor & wizard in the future. I'm going to marked this as "will not do" as this feature will not be further developed.

If you get a chance please take a look at the new v2.21 and brand new wizard available there.
