### ISSUE TITLE
Values on fields are not being updated real-time. 

### ISSUE THREAD

**Issue by kelfjrd** [SFDO-Community/declarative-lookup-rollup-summaries#1475]
I still need to hit the full calculate button to calculate the changes on the amounts of the fields. Can you please advise on how to automate the calculation in real-time. Below is the screenshot for reference.Thank you.

![Screenshot 2024-06-07 102741](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/171997489/6272b493-cabe-4bbc-b9b9-0a2e852f6cdf)

**Comment by aheber** [comment]
@kelfjrd please direct "how to use" questions to the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p), thank you.

Before you go, It looks like you'd need to add `Stage__c` to the Relationship Criteria Fields to instruct DLRS to react to changes in that field.

**Comment by kelfjrd** [comment]
I already put the stage= Closed Won in the relationship criteria and it still does not work. That is the reason I raise a case here.
