### ISSUE TITLE
Currency are converted when value is populated. 

### ISSUE THREAD

**Issue by PinalSF** [SFDO-Community/declarative-lookup-rollup-summaries#1476]
We are using Salesforce CPQ, and we had a need to create a Contract AER based on AER from Opportunities that contract tied with.
A contract can have Opp which contract is created from and some amendments Opportunities as contract life progress. 
Contract object has "Contract Opportunity" and "amendment Opportunities" as Opportunity lookups.
On Opp object we have Opp AER which is currency field I created a Custom field on contract object call Contract Opp AER a currency field.
then I created a DLRS to get the Opp AER value on Contract Opp AER when Opp IsWon.

DLRS: 

![DLRS](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/172833885/5d65d548-276a-4177-b71c-ee38a59b433a)

On contract object the Contract Opportunity AER = AUD 982,392.48 (USD 706,757.18)

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/172833885/b156d048-40e8-4231-9ea8-2fcba7fade18)

While On Opp Object the AER = AUD 916,633.33 (USD 706,757.18)
![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/172833885/7d2204e3-bc6b-490b-b3e4-14ef766a4ecb)

from UI it looks like this since they are in AUD

Opportunity

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/172833885/6329e818-3f95-4f69-98cb-2eb91295e035)

contract:

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/172833885/0bcfd58f-a97e-47bb-b7ed-57e1cc08add6)

As you can see, the DLRS working and providing value as correct USD conversion value but the local value on both Opp and contract are different.  

I thought this may be a currency conversion issue? but then again, I am not sure what to explain here. Hope this helps. 

There are no logs as there are no errors on job execution this is just a currency /local value are not correct as per the Objects in relation.
Our SFDC default currency is USD and we do support 9 other currencies.  All the fields are currency type fields.

**Comment by aheber** [comment]
@PinalSF DLRS doesn't currently respect Advanced Currency Management (Dated Exchange Rates).

DLRS has a couple of problems with currency right now. When it rolls up values it poorly converts all values to USD in the database and often loses a slight amount of value.

For something like this it is doing the exchange rates in the current exchange rate for the org, not the exchange rate when the Opp closed, which is Salesforce's native behavior.

This is one of our oldest issues, #40. I can't commit to timelines but this project has been getting a lot more development time recently and I expect this issue to come up for review sooner than later.

I'm going to close this but please comment on that other issue with your needs and it will help prioritize future work.

If you search around on here and the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) you're likely to see some suggested workarounds though I don't have anything specific to recommend, unfortunately.

If you'd like some other input I'd suggest you post on that trailblazer group to get input from others that may be deailling with the same issue.

**Comment by aheber** [comment]
Sorry, I used the wrong issue. #284 is part of this and should be the issue number.

**Comment by PinalSF** [comment]
Hi @aheber  - Thank you for your reply !! Will keep it an eye on.
