### ISSUE TITLE
Need to delete unused field on dlrs__LookupRollupSummaryScheduleItems__c

### ISSUE THREAD

**Issue by jtscloudservices** [SFDO-Community/declarative-lookup-rollup-summaries#1491]
I just loaded version 2.21 in a Sandbox upgrading from 2.11

Got the message to delete/remove dlrs__LookupRollupSummary__c on dlrs__LookupRollupSummaryScheduleItems__c

There is no Delete or Remove button
This was reported before but I could find no resolution
Any suggestions?

![image](https://github.com/user-attachments/assets/355236ec-8f2b-46bb-bcd2-9d3b680558ea)

**Comment by aheber** [comment]
Hi, have you gone through the steps in this link?

It has a specific note for needing to use classic to delete the field.

https://sfdo-community-sprints.github.io/DLRS-Documentation/Issues/#attention-need-to-delete-unused-field-on-dlrs__lookuprollupsummaryscheduleitems__c

Hopefully that helps you out.

In the future we'd recommend using the Trailblazer Community Group linked in the README for this project.

**Comment by jtscloudservices** [comment]
Howdy ... yes ... looks the Same in Classic and Lightning
![image](https://github.com/user-attachments/assets/9f661b4e-3868-43bb-a7a8-46cf59da6f5a)
I'll check trailblazer

**Comment by jtscloudservices** [comment]
Thanks

**Comment by aheber** [comment]
Very weird. My recommendation would be to open a support case. I hope that gives you a path forward.
