### ISSUE TITLE
Disable Rollup using Custom Permission doesn't work when the app is packaged

### ISSUE THREAD

**Issue by aheber** [SFDO-Community/declarative-lookup-rollup-summaries#1507]
**Describe the bug**
We're adding a new feature to disable a Rollup for users holding specific custom permissions. This worked great in dev orgs but when installed as a package the scoping on `FeatureManagement.checkPermission` can't check for non-namespaced Custom Permissions. 

We'll need to change to check for Custom Permissions by directly inspecting the underlying SObjects

**Expected behavior**
When I place a Custom Permission in a Rollup and the running user holds that Custom Permission then the Rollup shouldn't run. Especially when the code is packaged but the Custom Permission is owned by the org.

**Comment by ArnasBaronas** [comment]
Hi @aheber,

When packaging a solution into a managed package, testing interactions between namespaced and non-namespaced metadata can indeed become tricky. I’ve encountered a similar issue in the past and developed a workaround that worked well in my case.

You can find the approach in this [GitHub example](https://github.com/ArnasBaronas/chat-gpt-sfdc/blob/main/force-app/main/default/classes/PackageUtility.cls#L92). Essentially, it checks the class name to determine if the class is part of a managed package and then returns the namespace for processing in subsequent interactions.

I hope this method can help you address the bug you’re facing. Let me know if you need further details or clarification!

Best regards,
Arnas

**Comment by aheber** [comment]
@ArnasBaronas thank you for helping. I ended up changing the utility method build a cache of all Custom Permissions the current user has access to with their namespaces. Built on-demand.

This allows me to not only check Custom Permissions that have zero namespace (which you can't do from a namespaced package against non-namespaced Custom Permission) but all the names are checked from the perspective of a non-namespaced user which will make a lot more sense to the user configuring the tool.
