### ISSUE TITLE
Useability, clarify use 'Relationship Criteria Fields' field

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#152]
See chatter post [here](https://success.salesforce.com/0D53000001vho9m).

**Comment by wes1278** [comment]
Closing this issue as it's answered in the chatter post.

**Comment by afawcett** [comment]
Thanks, but i marked it as an Enhancement to remind me to relabel / clarify in help the role of this field. I agree though in the meantime the Chatter post is a good reference.

**Comment by aheber** [comment]
Included in the new LWC wizard that is introduced in v2.21
