### ISSUE TITLE
User Permissions 

### ISSUE THREAD

**Issue by Pixelkelly** [SFDO-Community/declarative-lookup-rollup-summaries#16]
Hi Andrew,
Ok, I have another newbie question for you....

I granted access to one profile which need to use this, but now all users of different profiles receive this error message when trying to save a Opportunity & account record.  The 2 DLRS I have active rollup all won child opportunities on the opportunity record, and the other one rolls up all won opportunities on the account record. Field to aggregate 'Amount'

Error:Apex trigger dlrs_OpportunityTrigger caused an unexpected exception, contact your administrator: dlrs_OpportunityTrigger: execution of AfterUpdate caused by: dlrs.SObjectDomain.DomainException: Permission to access an dlrs__LookupRollupSummary__c dennied.: (dlrs

So, what can I do to resolve??
Also...(this may be a roll the eyes moment)...is it possible to have the tool activated without the profiles having the 'Modify all Data', as I don't want the users to have this.....

Appreciate any assistance!  Kelly

**Comment by mubeen-qawi** [comment]
Thanks Andrew! I think profile based approach worked well for me. permission set involves lot of maintenance.
