### ISSUE TITLE
Option to discard scheduled items

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#237]
John Hyaenidae (Customer)
Does one ever need to remove and re-add the child trigger on a roll up? 
Does the child trigger affect all roll ups using the same child object?
Topics:   Child Object, Roll Ups, Trigger
Comment   ·   Like   ·   Share   ·  
18 August 2015 at 16:54   ·  
Dan Donin (Jive Software)
Dan Donin (Jive Software)
If you have 3 Roll-ups on say Opportunities rolling up-to say Accounts, you only need a single child trigger. This can be seen when you deploy the trigger off one of the rollups then go to the others they only have the option to remove.

"trigger dlrs_XTrigger on X
(before delete, before insert, before update, after delete, after insert, after undelete, after update)
{
dlrs.RollupService.triggerHandler(); ... More
Unlike
   ·  2 people   ·   18 August 2015 at 17:01   ·  
John Hyaenidae (Customer)
John Hyaenidae (Customer)
Excellent, thanks. What I thought. One deploys the trigger with the first roll up for a child object and then simply adds roll ups as needed.
Like
   ·   18 August 2015 at 17:05   ·  
John Hyaenidae (Customer)
John Hyaenidae (Customer)
What happens if there are scheduled items and I change the criteria in the roll up?
Like
   ·   18 August 2015 at 17:28   ·  
Dan Donin (Jive Software)
Dan Donin (Jive Software)
I have no idea. I have mine running in RealTime.
Like
   ·   18 August 2015 at 17:29   ·  
Andrew Fawcett (FinancialForce.com)
Andrew Fawcett (FinancialForce.com)
Existing scheduled items are currently not adjusted if criteria changes. Is this something you feel is needed?
Like
   ·   19 August 2015 at 01:15   ·  
John Hyaenidae (Customer)
John Hyaenidae (Customer)
I think this is worth considering. If I change the criteria, there's a good chance that I want a different set of items to be rolled up. An option to discard scheduled or somehow re-asses items would be good.
Like
   ·   19 August 2015 at 14:15   ·

**Comment by aheber** [comment]
I'm cleaning things up and will be closing this one out. Processing a Scheduled item for a parent record when the criteria changed shouldn't cause damage to any data, worst case it will over-update a record that might not benefit from the update but it shouldn't cause a problem or invalidate the results.

As a reminder to anyone coming after, if you change a rollup configuration you're likely going to need a full calculation to reconcile the system to the new configuration.


If this doesn't capture the need in this request please ping me and we can clarify and reopen if needed.
