### ISSUE TITLE
Add Apex Tests for Custom Metadata features (requires Apex Mocks)

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#270]
Its not possible to dynamically created Custom Metadata records in Apex tests. Thus at present there is not coverage for the new UI controller for editing them, nor further tests covering both Custom Object and Custom Metadata usage scenarios. This enhancement will address that, through adopting Apex Mocks in the Selector layer.

**Comment by aheber** [comment]
This is generally supported via `RollupSummariesSelector.setRollupCache` which allows you to mock records during testing.
