### ISSUE TITLE
Merge Enhanced UI features into new Custom Metadata UI

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#272]
The Custom Metadata UI, 'Manage Lookup Rollup Summaries' tab, mimics the standard Salesforce Custom Object UI at present. This ticket is to update this UI with the great features of the Enhanced UI. :+1:

**Comment by afawcett** [comment]
At @wes1278 the new page name is [managelookuprollupsummaries](https://github.com/afawcett/declarative-lookup-rollup-summaries/blob/master/rolluptool/src/pages/managelookuprollupsummaries.page).

**Comment by afawcett** [comment]
Regarding unit test coverage for the controller see https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/270 for the current status.

**Comment by aheber** [comment]
This is superseded by the new LWC wizard in v2.21
