### ISSUE TITLE
RollupJob vs calculate errors

### ISSUE THREAD

**Issue by wes1278** [SFDO-Community/declarative-lookup-rollup-summaries#30]
Andrew,

We're running into a weird error with some scheduled jobs. This is on the financial force object model. We're trying to rollup parent milestones to phases and then phases to projects. When we run the RollupJob, we get an error that says :"Invalid Id for pse__Project_Phase__c"; However, when we run the RollupCalculateJob, it seems to work without any issues.

Any idea what might be going on?

Some other background info: 
- We tried to have these all as realtime, but it says we were causing too many rollups or something related to the # of objects in the chain. Due to having timecard rollup to child milestone, rollup to parent milestone, rollup to phase, rollup to project. So, we tried to break out the last 2 levels into scheduled jobs.
- Clicking the calculate button seems to work.

**Comment by afawcett** [comment]
FYI, i have now got a handle on this error [here](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/185), fixing it now!
