### ISSUE TITLE
Rollup fires on new record even though criteria excludes the current record for count rollup.

### ISSUE THREAD

**Issue by jjulicher** [SFDO-Community/declarative-lookup-rollup-summaries#340]
When we are using boolean values in the relationship criteria it still fires if that value is false or doesn't match the criteria. 

To stop this from happening on new records check that the relationship criteria matches the current record. 

I believe it would be the same for deletes as well. 

Not sure if this should be the case for other rollups? 

This would be good to avoid unnecessary updates although parsing of the relationship query would be required (if not already done).

**Comment by afawcett** [comment]
Yeah the tool does not evalatue the criteria only that the field to aggregate field and any of the relationship criteria field fields have changed. Having it not run the rollup if the criteria is not met does involve parsing the criteria as you say, currently though this can be quite rich, basically the SOQL WHERE syntax. I am sure there is another GitHub issue discussing this and is still open to continue to try to figure this one out. I'll leave this one open until i find it! 👍

**Comment by jjulicher** [comment]
Thanks Andy. 

I don't know if this would help but if you ran a soql query with the where clause returning the id of the sobject would it not satisfy this requirement as we are in the after (in trigger terms) the Id should be populated and and soql queries that run should return the current object? 

Something like:

'SELECT Id From OBJECT WHERE Id = \'' + oldRecord.Id + '\' AND ' + relationshipCriteria 

It would require an extra soql query but you could add this as an option in the config?

The alternative is like I suggested earlier to parse the where clause.

**Comment by afawcett** [comment]
Yes that would work, at the expense of performance and SOQL governor usage. As you say though an option to let the user choose what they want would be the way to go, put the decision in the users hands. Thanks for the thought. 👍

**Comment by aheber** [comment]
This should be handled by the new logic provided by #1289 that will validate that the DML will modify the target record.

If this is the first child and the parent record doesn't already have a correct default value the first update will populate the value according to having zero matching child records. But if the parent already has the expected value then the DML against the parent will be skipped.
