### ISSUE TITLE
Support new picklist field types on custom metadata rollups

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#366]
These have arrived on the platform since this functionality was written. Consider ways to introduce them.

**Comment by JimBTek** [comment]
@afawcett can you recall if here you meant:

- let DLRS support aggregating Picklist fields? (for concat, etc.)
- OR change the DLRS custom metadata records to use picklists themselves vs.

**Comment by BethHoward** [comment]
Not sure if this is the right place to comment, but it seems like a related topic. I'd love to see an option for aggregating unique picklist values from child records into a multi-select picklist on the parent record - I thought I'd done this with DLRS at some point, but I must have misremembered.

**Comment by BethHoward** [comment]
> Not sure if this is the right place to comment, but it seems like a related topic. I'd love to see an option for aggregating unique picklist values from child records into a multi-select picklist on the parent record - I thought I'd done this with DLRS at some point, but I must have misremembered.

Ahahaha, wrong again - this is a supported feature; I'd just set it up badly. Thanks to everyone who works on this tool for the great features you provide!

**Comment by aheber** [comment]
I believe the thought here is to use the Entity Reference picklist options in Metadata to help configure the rollups. I believe this was later reviewed and due to these picklist not supporting all possible SObjects it was decided not to use these configurations.

We can always reopen if needed at a future date.
