### ISSUE TITLE
Record type specific rollups

### ISSUE THREAD

**Issue by pgfreire** [SFDO-Community/declarative-lookup-rollup-summaries#37]
It would be nice to be able specify rollups that are applicable only to certain record types in order to avoid processing irrelevant records. This is a subset of WHERE clause building that makes sense by itself and that is much easier to implement than the generic condition builder approach. Thanks.

**Comment by wes1278** [comment]
@pgfreire are you aware of the ability to put RecordType.DeveloperName = 'myRecordTypeName' into the where clause?

Will this meet your requirement or did you have something else in mind?

Thanks!

**Comment by afawcett** [comment]
@wes1278 thanks for this suggestion, great point, though i think @pgfreire is suggesting its perhaps a common criteria it might be worthy of its own field on the rollup definition e.g. 'Where Record Type'

**Comment by pgfreire** [comment]
@wes1278 @afawcett is right. The record type, more than a common criteria, defines a partitioning of the object such that each record type becomes a sort of sub-object. Thus, when a record type is specified in a rollup, only the records of that record type should be read, improving the rollup performance.

**Comment by wes1278** [comment]
@afawcett @pgfreire How do you guys feel about this enhancement still?

**Comment by afawcett** [comment]
Still think its a good idea, i notice some one on the Chatter Group posted recently struggling with the same requirement.

**Comment by SebasCanseco** [comment]
Hi. First of all, great tool! Congrats!
I've used RecordType.DeveloperName = 'Household' for Contact object and getting an "Invalid field RecordType.DeveloperName for Contact" error.
Any thoughts?

**Comment by afawcett** [comment]
Can you include a screenshot of your error and your rollup definition?

**Comment by SebasCanseco** [comment]
I'm attaching the screenshot now. Finally! I have used formula fields instead of referencing related object's field directly, with the caveat that formula fields won't work for real time or custom schedule rollups.

![screen shot 2016-06-14 at 2 03 50 pm](https://cloud.githubusercontent.com/assets/5733582/16056155/d7ec308a-3239-11e6-9a0a-53a9369dbe9b.png)

**Comment by afawcett** [comment]
Thanks for the screenshot. I think we have all we need now to shape and scope this enhancement.

**Comment by JimBTek** [comment]
I am not having this problem, I am using RecordType.Name  It works fine if you just remove the RecordType field from the Relationship Criteria Fields section which I have documented on the wiki today.

![image](https://cloud.githubusercontent.com/assets/1176347/17158001/561854dc-5361-11e6-8dcc-04c3d03d0ad8.png)

**Comment by wes1278** [comment]
You need to keep record type in the criteria fields.

If you take it out, and we're to change the record type of a data record, it would not recalculate.

You probably need to use recordtypeid though.

**Comment by JimBTek** [comment]
Ah that makes sense. In my scenario however I am only doing Scheduled Calculations

**Comment by KevStarSF** [comment]
I am struggling a bit with restricting Scheduled & Calculated Rollups to one Record Type on the Parent Object side of the calculation.  I have attempted to use the "Filter master object using WHERE clause (OPTIONAL):" with a RecordTypeId = '012610000002guk' entry which works for an Opportunity < Custom Object rollup.  I get an error, however, on the batch job when attempting to use this same approach with an Account < Custom Object rollup.  I get the following status on the Apex Jobs List:

First error: line 2:0 mismatched character '<EOF>' expecting '''	Total Batch = 0

I am assuming this means that there were no Parent records the matched the filter criteria from the WHERE clause but I have verified that Parent Records that meet the RecordType criteria exist with corresponding Child records to rollup.  Running a Calculate on the same rollup without the WHERE clause filter on the Calculate page produces a successful batch run on All parent records.  Any help?

**Comment by afawcett** [comment]
So your using the Schedule Calculate page. And with one rollup your criteria (for the parent records) works for one rollup but not another? Have i understood correctly? Could you include screenshots of the one the tworks and the one that does not if so? Also can i ask that you please raise this via a new GitHub issue, as this is the enhancement thread. We need an issue that reflects the current design. Thanks and appreciated! 👍

**Comment by arshava-arshava** [comment]
Hi!
Can we add OR, AND statement in 
"Filter master object using WHERE clause (OPTIONAL):"
I am trying to use filter with 2 OR and it doesn't work. But, if i filter only with one value everything works fine

FYI: using your app without triggers

**Comment by x98agw** [comment]
Hi, 
I should start by stating I'm not a developer... I do have a lot of years on the Salesforce platform though, and generally know my way around :). I had this exact issue recently on a number of DLRS roll-ups I created referencing:

Relationship Criteria = RecordType.DeveloperName = 'RecordTypeDevName'
Relationship Criteria Fields = RecordType

When running the roll-up stand-alone, it worked just fine and properly rolled-up the values. We ran into a scenario though where another trigger was running on the same object and, when this trigger was called, it would throw the "Invalid field RecordType for {object}" error, and everything would stop. If I tried adding "RecordType.DeveloperName" to the roll-up, that would fail to save. I had to get around it by using a custom field on the {object} that copied down the Record Type name (as I didn't want to use RecordTypeId, given the administrative headache (and poor practice) of changing IDs after deployment. 

So, I'm just sharing this additional info in case it helps anyone. It appears that this approach I noted above does "work", but it can run into other issues. I think it would be ideal to be able to be able to filter by a related "object" (e.g.: record type, in this case), so we could filter in this manner.

**Comment by x98agw** [comment]
> You need to keep record type in the criteria fields.
> 
> If you take it out, and we're to change the record type of a data record, it would not recalculate.
> 
> You probably need to use recordtypeid though.

In addition to my prior note, I'm wondering if you know whether putting the following in place would a) work, or b) solve my issues?

Relationship Criteria = RecordType.DeveloperName = 'RecordTypeDevName'
Relationship Criteria Fields = **RecordTypeId**

**Comment by aaronbauman** [comment]
@x98agw yes, this is exactly what i just did and it seems to be working as expected.

**Comment by aheber** [comment]
I think this can be solved using existing methods. We'll be researching better UX to manage criteria in the future and I believe the core request here would be covered by improving the condition builder.

I'll close this and look forward to future, more broad, enhancements that would also reach some of these goals without being a narrow additional criteria.
