### ISSUE TITLE
DLRS fails to fire, but nothing appears in DLRS Logs as an error

### ISSUE THREAD

**Issue by JenNelsonChicago** [SFDO-Community/declarative-lookup-rollup-summaries#374]
This is very sporadic, and we still have no idea of the root cause, but since it has occurred 5 times in 6 months, I thought it was time to report it.

Every now and again, in one of our customer's Orgs with DLRS, we will notice that values on Parent records are not updating with the expected Real-time rollup from the Child.

There is no record in the DLRS Logs object to indicate an error such as a validation on parent and when I go to the DLRS and manually initiate "Calculate", the Apex Job shows completed with no error.

Org is Unlimited Edition and we are on 2.3, operation for all DLRSes is "Sum" and all are Real-Time

Would love to see additionally error-trapping for stall _and_ would love to see a Last Run Date/Time field and Last Run Result (i.e. Success / Fail) on the DLRS record.

**Comment by afawcett** [comment]
Thanks @JenNelsonChicago good idea, will give it some thought.

**Comment by dthowell** [comment]
Hi

I know this might not be the place for support. We seem to be one of those orgs. the roll up isn't udating the target fields but also no logs are created. 

I have tried realtime and scheduled with no luck. It might be timing out but without logs I cannot confirm.

**Comment by afawcett** [comment]
No worries, a few of us hang out here, but more support from the community is available via the Success Community chatter group (see link in the readme). Try reporting your issue there with a screenshot of your rollup, the kind folks in the group will be sure to help more. 👍

**Comment by JenNelsonChicago** [comment]
Hey, @afawcett - is it possible that https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/347 could be causing the Stall described here on 374?  We continue to get the stall more frequently now, but with nothing in the logs.

**Comment by afawcett** [comment]
For realtime rollups the rollup summary log object is not used. Both scheduled and realtime rollups with criteria live and breath by being able to spot changes to criteria fields, if your using formulas in your criteria or certain date based formula functions this gets much harder. Do any of the rollups use these type of criteria?

**Comment by JimBTek** [comment]
This may not be related but I did notice that if you manually calculate a DLRS and a field is missing, there is noting in the DLRS Logs, but the Apex Job will show an error.  I don't think this really needs to be "Fixed" but re-iterating that the DLRS logs may look like it worked, when there was an Apex Error so it's important to check both places.

Is it possible to both have a DLRS be realtime and add a weekly or monthly scheduled full recalc to make sure everything is in line?

**Comment by afawcett** [comment]
RE: "a field is missing", what do you mean by this?

RE: "realtime and add a weekly or monthly scheduled full recalc", yep that should work.

**Comment by justinNiM** [comment]
@afawcett and @JenNelsonChicago thanks for flagging this.  This helped me troubleshoot a misspelled SOQL query issue earlier today and get these DLRS firing correctly for a client.  Happy Friday y'all! (cheers!)

**Comment by aheber** [comment]
I'm going to mark this ticket as closed. If anyone has any ongoing issues related to rollups not firing as expected please reach out to the Trailblazer Community channel (found in the README) for the best help.
