### ISSUE TITLE
SOQL Copy -  Sample Formula 

### ISSUE THREAD

**Issue by danhowellnz** [SFDO-Community/declarative-lookup-rollup-summaries#398]
Hey, I love the tool. I was testing some of my Rollup summaries in the developer console. 

I created a text formula so I could quickly copy and paste my Roll up summaries as SOQL. 

Is this useful for other users? 

![image](https://cloud.githubusercontent.com/assets/21028276/18621752/b9606968-7e7b-11e6-9d4c-94b2ef540bb9.png)

"SELECT "& 

/\* Include field to aggregrate if not in where clause */
If( CONTAINS(dlrs__RelationshipCriteriaFields__c, dlrs__FieldToAggregate__c) ,"",
dlrs__FieldToAggregate__c &",")& 

/\* Remove line breaks */
SUBSTITUTE(dlrs__RelationshipCriteriaFields__c ,  mid($Setup.Global__c.Line_Break__c,2,1) , ", ") 

&" FROM "& dlrs__ChildObject__c &" WHERE "&  dlrs__RelationshipCriteria__c

---

It requires a custom setting field for the line break character detection. A custom settign field of:
"a
b"

**Comment by wes1278** [comment]
I think that's awesome! :)

**Comment by afawcett** [comment]
Yes I agree, @dthowell thank you for sharing this idea. I'm marking it as an enhancement to feed into an upcoming release.

**Comment by aheber** [comment]
Closing this out. The new LWC wizard in v2.21 starts on some of this but future release will do a lot more to make the SOQL building/testing better.
