### ISSUE TITLE
Multiple criteria in one rollup?

### ISSUE THREAD

**Issue by CapstoneLogistics** [SFDO-Community/declarative-lookup-rollup-summaries#41]
Is there a way to have multiple criteria for a rollup? I want to pull opportunities that are won and are of a certain Record Type.﻿

**Comment by egagnier** [comment]
Hi,

The AND operator works great. But What about the OR? It doesn't works for me (error is 'unexpected token: or').

Thank you for your help.

**Comment by aheber** [comment]
See #138

**Comment by egagnier** [comment]
Hi,

Thank you aheber but ...

I tried this criteria in Relationship Citeria field :
SELECT Nom_session__c FROM Participation_animation__c WHERE Presence__c = 'Réalisé' or Presence__c = 'Prévu'
I tested it with Worbench. It works.

I get this error :
Error: Relationship Criteria 'SELECT Nom_session__c FROM Participation_animation__c WHERE (Presence__c = 'Réalisé' or Presence__c = 'Prévu')' is not valid, see SOQL documentation http://www.salesforce.com/us/developer/docs/soql_sosl/Content/sforce_api_calls_soql_select_conditionexpression.htm, error is 'unexpected token: 'SELECT''

Thank you for your help

**Comment by egagnier** [comment]
It works !

I needed to remove the Trigger, write my criteria (Presence__c = 'Prévu' or Presence__c = 'Réalisé' or Presence__c = null) and deploy again the Trigger.

Thanks a lot.
Have a good day :)
