### ISSUE TITLE
Filtered sets

### ISSUE THREAD

**Issue by jrz** [SFDO-Community/declarative-lookup-rollup-summaries#456]
Hi Andy,

My client has a requirement for a sum() over the last X (20) children, ordered by date.

I'd like to extend dlrs, but I'd like to know if the change will go upstream.

It would extend the non-aggregate-query is extended to support sum/avg for use with limit filters.

Example:  average customer rating over the last 10 bookings.

Maybe you have a better idea for this?

**Comment by afawcett** [comment]
Yes Row Limit only applies to concat and last operators currently.

More than happy for you to work on this, its what its all about! 👍 

If you want to review the code and share ideas on what to change here, that might be best.

Then once it looks good, make the changes, write the tests and generate a PR.

I'll then sweep it up into the next manage package release.

Is generally how it works.

Make sense?

Keep in mind, your work will be under the open source license of the tool, make sure your client understands that.

**Comment by wes1278** [comment]
@jrz I wouldn't be worried at all about getting them implemented upstream. @afawcett is the most dedicated maintainer I've ever seen.

As far as your enhancement goes, I love and need the idea as well. I actually didn't know this was unsupported. Would be willing to help if you wanted to get started.

**Comment by afawcett** [comment]
Thanks for the kinda words @wes1278, its tricky at times with work and personal life, but i try my best. Any help is always welcome! 👍

**Comment by aheber** [comment]
I'll close this for now. If down the road someone wants to pick this up please do so.
