### ISSUE TITLE
Record the WHERE claused used when using the full calc Schedule feature

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#469]
Per discussion in the group [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p&fId=0D53A00002yTS3x&s1oid=00D300000000iTz&OpenCommentForEdit=1&emkind=chatterCommentNotification&s1nid=0DB30000000072L&emtm=1485184300136&s1uid=005300000098P0U&fromEmail=1&s1ext=0).

**Comment by aheber** [comment]
Dup of #605
