### ISSUE TITLE
Clone a Rollup

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Community/declarative-lookup-rollup-summaries#494]
It'd be great to be able to clone a (metadata) rollup definition, when creating a pile of rollups that are similar (e.g last year, 2 years ago, 3 years ago)

**Comment by afawcett** [comment]
Yeah nice enhancement @cdcarter 👍

**Comment by tet3** [comment]
Current work around: use Clone button in native CMDT UI in Setup.

**Comment by atbryant** [comment]
Thank you for the suggestion tet3! Much appreciated, and a great time saver.

**Comment by aheber** [comment]
This is available using the new LWC wizard starting in v2.21
