### ISSUE TITLE
RollupJob error: Cannot have more than 10 chunks in a single operation

### ISSUE THREAD

**Issue by dcarter** [SFDO-Community/declarative-lookup-rollup-summaries#51]
"First error: Cannot have more than 10 chunks in a single operation. Please rearrange the data to reduce chunking."

My scheduled rollups (there are several) include (filtered) counts of Assets rolled up to Entitlements, and then (filtered) counts of Entitlements rolled up to Accounts. 

From a little Googling, it appears that the usual suggestion when encountering this is to ensure that different types in SObject are sorted in order by type, to minimize breaks/switches between types. For example: 
http://sfdcmaniac.blogspot.com/2013_10_08_archive.html

**Comment by sethstone** [comment]
Hi Andy, my co-worker @Adair21 submitted a pull request that fixes this issue and provides a test case.  This is a super-critical fix for us, so I was wondering if you have any plans to build a new package soon.  (We currently have DLRS installed as managed package in our Sandbox and Production environments).  

Also, one note on the pull request (#104) we pulled out the permission sets that wouldn't deploy and accidentally committed that file.  The pull request includes both the change and the revert of the change - sorry about that.  Perhaps github allows for cherry-picking from a pull request?

**Comment by afawcett** [comment]
Wow thanks guys! Will take a look and yes will get a release out asap.

**Comment by Adair21** [comment]
Yes, although I never use it. It's @jlukeadair.
