### ISSUE TITLE
Question:  If using only Custom MDT-based Rollups, is it possible to avoid queries of config sObjects?

### ISSUE THREAD

**Issue by jclark-dot-org** [SFDO-Community/declarative-lookup-rollup-summaries#528]
In a new org with only Custom MDT-based rollups, it appears that DLRS still queries the sObject-based config in Lookup Rollup Summary object.  Is it possible to configure DLRS to ignore all sObject-based config and only look at Custom MDT rollups?  It would reduce the number of SOQL queries in complex testing scenarios.

**Comment by afawcett** [comment]
Its not possible, but, i guess we could add a custom metadata/object setting for this easily. I'll flag this as an enhancement. Would be a pretty easy change to the selector class methods tbh.
