### ISSUE TITLE
Errors when installing: Permission Set will not deploy (Developers Only)

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#58]
When using the Deploy to Salesforce link to deploy the raw source code the following error appears during the deployment. Workaround is to either use the managed package to install or clone the repo and remove the Permission Sets for now.

Deployment Complete
Failures:
permissionsets/LookupRollupSummariesFull.permissionset(LookupRollupSummariesFull):Unknown user permission: AllowUniversalSearch
permissionsets/LookupRollupSummariesReadOnly.permissionset(LookupRollupSummariesReadOnly):Unknown user permission: AllowUniversalSearch

**Comment by Adair21** [comment]
Sorry, I incorrectly referenced this issue in my commit. I mean to reference issue #51
