### ISSUE TITLE
Rollup of opportunity contact role

### ISSUE THREAD

**Issue by agnaramasi** [SFDO-Community/declarative-lookup-rollup-summaries#59]
Hello,
I am trying to create a rollup on the opportunity to count the number of contact roles a certain type that have been assigned. I get an error when I deploy the trigger stating that the object does not support triggers. I get the same error if I attempt to use scheduled mode. 
I understand that opportunity contact roles do not support triggers, but shouldn't scheduled mode still be possible?
Many thanks for your wonderful tool.
Jonathon

**Comment by tenacoder** [comment]
Are we able to Rollup of opportunity contact role now?

**Comment by DanDonin** [comment]
That object doesn't support triggers :(

**Comment by tenacoder** [comment]
Thanks for confirming that.
