### ISSUE TITLE
Adopt Apex Metadata API 

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#607]
This will avoid depending on SOAP Metadata API and thus Remote Site setting when configuring.

**Comment by aheber** [comment]
This is being used where possible, to create and update Custom Metadata records in the new LWC wizard in v2.21.

We still need SOAP to manage triggers and delete Custom Metadata, unfortunately.

I'll close this and we can open a new issue when Salesforce improves support via the Apex Metadata API.
