### ISSUE TITLE
DLRS Trigger Preventing Campaign Influence Record Creation

### ISSUE THREAD

**Issue by slhemingway** [SFDO-Community/declarative-lookup-rollup-summaries#624]
Hi, I'm using DLRS to count customizable campaign influence records on an opportunity. However, discovered that the trigger created to count the number of influence records (when active) ended up preventing campaign influence records from natively being created when an opportunity was in certain stages. Is this a known issue? Thanks in advance!

**Comment by slhemingway** [comment]
<img width="1422" alt="screen shot 2018-01-26 at 12 43 54 pm" src="https://user-images.githubusercontent.com/35386633/35457611-c24c8b56-0296-11e8-838e-0e3cdca65d29.png">
<img width="1443" alt="screen shot 2018-01-26 at 12 44 31 pm" src="https://user-images.githubusercontent.com/35386633/35457621-c4881b92-0296-11e8-9d41-2f0df4f7a5d9.png">

**Comment by afawcett** [comment]
I am not aware of such an issue no. Would you be able to provide more details on the error you are getting, steps to perform it and if you would links to more info on this functionality. All this would help reproduce the issue and determine the root cause.

**Comment by slhemingway** [comment]
Hi! Thanks for getting back to me. I actually think the issue DLRS ran into actually had to do with our validation rules rather than DLRS itself. I believe this has been resolved for now.
