### ISSUE TITLE
Enhancement - Validation Rule/Code Check make sure Relationship Criteria fields is populated when Relationship Criteria isn't blank

### ISSUE THREAD

**Issue by DanDonin** [SFDO-Community/declarative-lookup-rollup-summaries#638]
Maybe a validation rule that checks if you have Relationship Criteria to make sure you fill in your Relationship Criteria Fields.

AND(
NOT(ISBLANK(RelationshipCriteria__c)),
ISBLANK(RelationshipCriteriaFields__c)
)

Error message top of page
If you have Relationship Criteria please put the fields in that criteria into the Relationship Criteria Fields.

**Comment by afawcett** [comment]
Great idea thanks!

**Comment by aheber** [comment]
I'm not convinced this is always a good idea to enforce.
What if the Relationship Criteria Fields may not actually be necessary in every single criteria is, for instance, related to the parent record and not the child (I know it is a bad idea and could really only be kept in sync via scheduled calculated)

I'll leave this open for discussion but I suspect we won't be able to guarantee this is always necessary and people would have to put in redundant values like the Relationship Field, which is already included in the field set.

**Comment by aheber** [comment]
I'm going to close this. I still don't think it would be ideal to mandate Relationship Criteria Fields in this case.
We will be making some improvements in the future to make that field more automatic and less error prone.
