### ISSUE TITLE
Can't remove dlrs trigger

### ISSUE THREAD

**Issue by petec-i2isys** [SFDO-Community/declarative-lookup-rollup-summaries#668]
We were using Financial Force and they installed a trigger called:dlrs_VanaHCM_TimeSheetTrigger
No matter what we try we can't seem to remove this. Financial Force said to contact you.

Can you help?
Thanks,
Pete 
petec@i2isys.com
707-303-4168

**Comment by petec-i2isys** [comment]
Hello,


I have looked but that roll up is no where to be found that I can see.  Here are all of the rollups and none of them related to the trigger item, or are on the PS object and Financial Force Time sheet.


[cid:261aa7e6-09a5-4bd6-b714-5f4115005727]



Pete Castagnetta

Director, Sales Operations



707-303-4168 w

petec@i2ipophealth.com

<https://www.i2ipophealth.com/2018/03/28/2018-i2i-user-conference-in-phoenix-az/>
[cid:de8acb5c-759a-4798-80b6-34930305614c]
Book my Calendar<https://calendly.com/pcastagnetta>


This message, including files attached to it, may contain confidential information that is intended only for the use of the ADDRESSEE(s) named above.  If you are not an intended recipient, you are hereby notified that any dissemination or copying of this information contained in this message, or the taking of any action in reliance upon the information is strictly prohibited.  If you have received this message in error, please notify the sender immediately by reply e-mail and destroy any and all copies of the original message



________________________________

**Comment by DanDonin** [comment]
You can always create a new DLRS point it to the object that the trigger
lives on and then click the manage child trigger and remove the trigger
that way.

**Comment by afawcett** [comment]
Yep what @DanDonin said. btw @petec-i2isys if you want to share images yuo have to do it via the GitHub you, attachments don't make it through. :-(

**Comment by petec-i2isys** [comment]
Ok so when I try to re-create the roll up I getting that neither object exists.  Which I know they do.


I've attached the apex and trigger downloads to see if you can see what is the child and what is the parent object.


Thanks,



Pete Castagnetta

Director, Sales Operations



707-303-4168 w

petec@i2ipophealth.com

<https://www.i2ipophealth.com/2018/03/28/2018-i2i-user-conference-in-phoenix-az/>
[cid:ca39a0c1-dac9-43bc-9b34-7142976fa1ba]
Book my Calendar<https://calendly.com/pcastagnetta>


This message, including files attached to it, may contain confidential information that is intended only for the use of the ADDRESSEE(s) named above.  If you are not an intended recipient, you are hereby notified that any dissemination or copying of this information contained in this message, or the taking of any action in reliance upon the information is strictly prohibited.  If you have received this message in error, please notify the sender immediately by reply e-mail and destroy any and all copies of the original message



________________________________

**Comment by afawcett** [comment]
@petec-i2isys GitHub is a real pain with email integration, so none of your images or attachments have come through. Can you add them via the GitHub Issue web ui please. Thanks.

**Comment by petec-i2isys** [comment]
Here are the screen shots and what I attached.
[dlrs_VanaHCM_TimeSheetTrigger.txt](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/1938952/dlrs_VanaHCM_TimeSheetTrigger.txt)
[dlrs_VanaHCM_TimeSheetTest.txt](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/1938953/dlrs_VanaHCM_TimeSheetTest.txt)
![roll ups](https://user-images.githubusercontent.com/26910998/39136713-b1ba5380-46d0-11e8-9a0d-378afabad8b4.png)

**Comment by afawcett** [comment]
On this screen, click New Lookup Rollup Summary. Create a rollup (does not matter how basic) for the VanaHCM_TimeSheet__c object then click the Manage Child Triggers button and click Remove. Then delete the rollup.

**Comment by ayalanydia** [comment]
I am having the same problem in trying to remove 2 old DLRS child triggers that were left behind.  The Rollup Summary was deleted without removing the trigger.  And one of the referenced objects was part of another managed package, which has been deprecated by that company.  Any advise on how to remove those triggers in my case?

**Comment by troveryor** [comment]
This is a little different in LEX, I was able to remove a DLRS trigger by doing the following.
From App Menu waffle search for Lookup Rollup Summaries and click. 
Change listview to All and click on the name in the Lookup Rollup Summary Name column.
Navigate to the dropdown menu on the far right, for me right after the Edit button.
You should see a bunch of options including "Manage Child Trigger". Click that one.

Here you will see the Trigger code and it's test, and have a button to Remove it. 

This kicks of a deployment action, you can see it in the Setup->Environment->Deployment Status page. 
So keep that in mind if you might have other deployment actions happening in your org.

I suspect otherwise a destructive deployment with the ApexTrigger members would be a better way if you wanted to dump more than one.

**Comment by aheber** [comment]
Closing as a dup of #674, should be able to manage these without needing a rollup.
