### ISSUE TITLE
CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_CampaignMemberTrigger - preventing leads from being created?

### ISSUE THREAD

**Issue by mountainmonk** [SFDO-Community/declarative-lookup-rollup-summaries#679]
I'm getting 2 errors associated with the apex created by DLRS. Below is my intended use case and the error messages.

Use Case:
I was looking to create 2 fields that show the first campaign of a lead or contact. The 2 configs are below:
<img width="1247" alt="screen shot 2018-04-25 at 9 45 19 am" src="https://user-images.githubusercontent.com/6128722/39260309-ec63966a-486d-11e8-9d4f-5ab6552de617.png">
<img width="1245" alt="screen shot 2018-04-25 at 9 45 32 am" src="https://user-images.githubusercontent.com/6128722/39260307-ec4c8f38-486d-11e8-954e-2fc3be43dcf9.png">

I had also created the child trigger from the Contact-CampaignMember DLRS so I could use realtime calculation.

<img width="789" alt="screen shot 2018-04-25 at 10 00 35 am" src="https://user-images.githubusercontent.com/6128722/39260872-93466cae-486f-11e8-8577-b80ba764113c.png">

Days went by before we started to notice fewer leads from our AppExchange listing and an increased instance of orphaned license records (no lead or contact associated with them). Simultaneously, I began getting 2 errors in my inbox.

1) Process builder error - which attempts to add a CampaignMember record to a Lead. The error reads:
> Error Occurred: This error occurred when the flow tried to create records: >CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_CampaignMemberTrigger: execution of >AfterInsert caused by: System.SObjectException: Invalid field ContactId for CampaignMember (dlrs) . >For details, see API Exceptions.

The LeadId in each process builder error is not found in SFDC - leading me to believe that this is preventing the creation of a Lead record.

2) Developer script exception - 
> Apex script unhandled trigger exception by user: >005400000022qte
>
>dlrs_CampaignMemberTrigger: execution of AfterInsert
>
>caused by: System.SObjectException: Invalid field ContactId for CampaignMember

What I noticed was that both referenced ContactId despite being Lead-based. My config looks correct - but I thought maybe the deployed Apex being from the Contact-CampaignMember DLRS might have had something to do with it - so the system is always looking for ContactId instead of differentiating between the two.

I've turned off real-time calculation - opting for Process Builder calculation instead so we don't lose lead records.

A few questions:

1. Any thoughts about why this is occurring?
2. Could this error be responsible for the un-creation of a lead? (bad word choice, I know!) After disabling, we're noting an uptick in the # of leads we're getting, so my hunch was yes - but I wasn't programmatically sure.

Appreciate this app - it's pretty dang awesome!

System Info:
- Salesforce - Enterprise Edition 
- DLRS - 2.9

**Comment by afawcett** [comment]
I think this might be the same as https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/926.

**Comment by DennisYoo1** [comment]
I get a similar error when trying to edit a record. To give some context to this issue, When we mark an Opportunity in Salesforce as Closed Won, it starts a Process to create a Case and some tasks. The error we keep seeing (as of today after I updated the app to version 2.12 ): "**_This error occurred when the flow tried to create records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: dlrs_TaskTrigger: System.LimitException: Apex CPU time limit exceeded. You can look up ExceptionCode values in the SOAP API Developer Guide. Error ID: 590262402-212596 (353122398)._** "
Not sure how to resolve the issue

**Comment by aheber** [comment]
I think this might be related to various issues around merging as well as a bad rep we have where Salesforce recommends against us being installed in PBO (Partner Business Org) environments.

This and it's related items are probably a high priority.

**Comment by aheber** [comment]
I think this might be resolved via #1038, should be fixed starting v2.16. If someone runs into a similar problem please open a fresh issue and reference this issue for context.
