### ISSUE TITLE
Not sure what fields to Choose

### ISSUE THREAD

**Issue by jillmyers** [SFDO-Community/declarative-lookup-rollup-summaries#680]
Hello, 

I am trying to build a Concatenate rollup to tell me all of the campaigns a particular lead is in. I want to either roll up the Campaign names, or the Campaign ID's. However, I cannot seem to get either to work. Any guidance on fields to choose would be greatly appreciated.

I have screenshot my first attempt:
![screen shot 2018-04-27 at 12 49 32 pm](https://user-images.githubusercontent.com/28907558/39379736-77532248-4a19-11e8-8e80-b175debcf92d.png)

Thanks!

**Comment by streetyouth** [comment]
It can be tricky to make campaign memberships rollup to contact and or
leads. I managed to do it. The trickiest bit was deploying The trigger on
the campaign member. It required a little bit of extra test code which I
found by googling. I also found that it was not reliable in real time mode
– perhaps my fault. I do have the five most recent campaign summarized on
every contact and it updates nightly.

**Comment by StormsEnd** [comment]
@streetyouth 

I have a similar end goal - congrats on solving it! Hope you had a moment to for a couple questions:
 
1. Can you clarify what you mean by requiring extra test code? 
2. Did you build a rollup for leads and contacts, or just leads? If both, did you deploy just for leads? I'm running into an issue where deploying from the Contact rollup window gets me [this issue](https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/679)
3. Which Calculation Mode is declared on your rollup? I read elsewhere that even if scheduling, some circumstances operated best with Calc Mode = Process Builder

Appreciate any help you can afford. :)

**Comment by jillmyers** [comment]
@streetyouth Any insight into the campaign member trigger modification would be greatly appreciated. 

Thanks!!

**Comment by DanDonin** [comment]
Campaignid isn't what relates leads to campaign member I think the field is LeadId and for contacts it is ContactId.  The tricky part will making it not fire on campaign membership changes where it is a converted lead as it will have a LeadId and ContactId and the lead update will fail as the record is locked. It should fail silently if you don't mind a ever growing error log.

**Comment by afawcett** [comment]
@mountainmonk   take a look at this thread > https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/197

**Comment by aheber** [comment]
I'm going to go ahead and close this but is anyone comes here with similar questions, questions like this are better supported through the [Trailblazer Community Group](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p) and the awesome group of people there.
