### ISSUE TITLE
Did Ip whitelisting and then getting error while manage LRS

### ISSUE THREAD

**Issue by sisodiasaurabh** [SFDO-Community/declarative-lookup-rollup-summaries#682]
Hi,
We have recently done Ip whitelisting to some of our salesforce profiles and after that we are unable to Manage Lookup rollup summary. As soon as we click on the manage LRS tab we get the error "Salesforce Metadata API connection failure, click the link below to configure."

dlrs_mdapi is set in Remote site settings(no change
![dlrs_error](https://user-images.githubusercontent.com/26732343/39483814-9db75c80-4d41-11e8-8527-f83a7a63c863.png)
). Infact it was working fine till yesterday.

Thanks.

**Comment by afawcett** [comment]
If you click "Return to the Welcome page" there is a debug message at the bottom of that page, what does it say? Also see https://github.com/afawcett/declarative-lookup-rollup-summaries#usage-information-and-known-issues
