### ISSUE TITLE
Lookup Rollup Summary Schedule Items occupied 15% of Space

### ISSUE THREAD

**Issue by athisachi** [SFDO-Community/declarative-lookup-rollup-summaries#735]
Hello,
  I think its a known issue. However I m still not clear  about next step. What should I do Next?
Most of DLRS are scheduled mode . Any help and suggestion greatly appreciated.

**Comment by aheber** [comment]
@athisachi you have the DLRS rollup set to scheduled mode but do you also have processing jobs scheduled? If you do not have jobs scheduled then the queue of records to be processed will just continue to build up.

**Comment by timmy2cakes** [comment]
Please can someone help me here I'm not getting any response on this https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/733

**Comment by athisachi** [comment]
Hi @aheber ,

Thanks for your response. It was set by another SF administrator. I am trying to get information from her.  How will I know processing jobs scheduled or not?  Last month, We deactivated all DLRS scheduled jobs(also some other jobs) because there were terrible performance issue with SF APEX jobs. Now We turned back ON everything.   Does it caused scheduled items overflow?
My question here is: How will I know every DLRS working fine? Should I delete scheduled items manually?  If I delete all scheduled items, What will be the impact on existing DLRS calculation? 
Thanks again

**Comment by aheber** [comment]
I don't remember if there is an easy way to check the schedule but you should be able to review the scheduled jobs in your Org (Setup>Scheduled Apex) and see if there are scheduled jobs for DLRS there. It is possible that you simply process that many records that you're keeping a constant backlog of that many records but I am making the assumption that isn't likely. If that is whats happening then you'll likely need to schedule additional runs of the processing jobs to keep the queue drained.

**Comment by athisachi** [comment]
thanks for your quick response.. I did checked scheduled Apex . there is only job DLRS scheduled . Though there are 12 scheduled DLRS active.  As per your response, u mean to say by scheduling all active DLRS will clear up the scheduled items table and I don't need to delete it.  Should it be incremental or full in this case? Assume user wants only 7 DLRS to be schedule. How can i safely Deactivate rest 5 DLRS?

**Comment by aheber** [comment]
If it were me. I would take the following steps.
1) Cancel the existing scheduled job.
2) Clear the scheduled items custom object.
3) Deactivate any DLRS jobs you do not want running
4) Perform a full recalculation of all remaining active jobs
5) Schedule the remaining active jobs to keep numbers current

That will ensure everything has a clean start and that you can go forward with confidence.

If performing full recalculation isn't an option then you need to deactivate the DLRS jobs you no longer need, clear their respective scheduled items (by tracking job ids), reschedule the remaining active jobs. I don't love this option just because it doesn't quite guarantee a clean house like the above steps.

**Comment by athisachi** [comment]
Thank you so much for detail explanation. That helps. We too like the first approach. I am going to test for one DLRS. I have question on Point 3.  Is there any steps involved to do it? 
My assumption:
1. Remove Active Flag in DLRS UI
2. Remove Schedule Jobs at backend 
3. Remove triggers if there is no other DLRS for that object.

Let me know thanks
athi

**Comment by aheber** [comment]
Yes, I think you're right on with that. Just remember that real-time calculations don't create the scheduled items so the performance profile changes.

**Comment by athisachi** [comment]
Hi @aheber 

I did clean up on one schedule item and did full run by 'Calculate' button. Once done I schedule by 'Calculate Schedule' for nightly job.  I assumed scheduling is incremental ( just run on records changed from last full run or processed records in schedule item). However total batch processed on full calculation was 2,009 and took 2 hr :45min to complete. Yesterday schedule shows 2011 batches and almost same time. I don't think there were so much change in a day. Am I missing something? Time taken expected. I have schedule 10 other job. I am not sure if system can accommodate all. Let me know your thoughts.
Thanks again
athi

**Comment by athisachi** [comment]
I just saw ,incremental way should be set up an apex job for the ApexClass "RollupJob" to run.  Excuse Me for that.

It also says "When RollupJob runs it will process all DLRS records that are active with Calculation Mode set to Schedule." Whether job  should be scheduled as well at the same time?.

**Comment by athisachi** [comment]
I upgrade to 2.11 in sandbox. It still insert any updates in child record .  This is actually creating close to 1M record everyday in scheduled item as we have 10 DLRS. Is there any solution for this?Help please

**Comment by aheber** [comment]
Can you justify to running these in real-time? That would avoid creating child records but does immediate DML on the parent record which might have cascading changes.

**Comment by athisachi** [comment]
That is good point. It was changed from realtime to scheduled item as was creating some issue . I was told parent object changes doesn't trigger rollup . yesterday I set the Schedule mode to 'Process builder' and 'Calculate Schedule' . I don't see any schedule item and it updated my test data. Was all DLRS set wrong all along?. I tried Schedule Mode to 'Schedule' 2 days back and schedule class apex 'RollupJob', thats was not working. 
I set the Schedule mode to 'Process builder' and 'Calculate Schedule'  is the right way to schedule the job I guess.

**Comment by aheber** [comment]
Yes. The three general forms for setup are real-time, scheduled (which is an incremental scheduled job which uses the Scheduled Items custom object to track the incremental children needed to recalculate), and a full scheduled recalculation.

It sounds like what you're looking for is the full recalculation, as you've already found and setup.

**Comment by athisachi** [comment]
@dwindibank I totally agree with your suggestion. Even I had hard time making others understand about "Process builder" and "schedule" mode. 
Admin User were setting up realtime/schedule and clicking "Calculation" button all along.
But DLRS is absolutely free and amazing , I couldn't ask more.

**Comment by afawcett** [comment]
Marking this as both enhancement (might be a dupe, but will leave it for now until i find it) and Wiki enhancement.

**Comment by aheber** [comment]
The next release will include improvements to the Optimizer related to Scheduled Items. It should make it easier to diagnose and resolve some of these errors.
