### ISSUE TITLE
Initial Calculation of ~40 DLRS

### ISSUE THREAD

**Issue by vseafordACF** [SFDO-Community/declarative-lookup-rollup-summaries#771]
Hi there.  I've read through much of the documentation and per the information I've done the following to kick off the calculation of rollups in my org for the first time.

1- Set Calculation mode for all rollups to Scheduled.
2- Deployed trigger(s).
3- Scheduled the RollupJob to fire every day.
4- Did a "touch" of all records that should be aggregated for the rollups to get them in the queue for the job.

Are there steps I'm missing?  No rollup data is getting populated, and I don't see any records in the Lookup Rollup Summary Schedule Items pertaining to my rollups.

I prefer to not do an explicit Calculate on each rollup b/c I'm working w/ 2M+ records and it will take hours for one calculate to finish. I'm assuming I cannot run the calculations concurrently since they're touching the same objects.

Thanks for your help!

**Comment by vseafordACF** [comment]
Thank you, I ended doing the following to perform a full calc of ~40 summaries-
1- Extracted a file of account Ids + child record Id (essentially, Select Max(child record ID), account ID from child object).  This reduced the list to about 400k records (instead of 2M+).
2- Created process builder flow handler on child object used for record aggregation.  The handler calls the DLRS, passing in parameters needed for DLRS. (Each of my summaries are for the same object.)
3- Touch (update) of each child record in the file using data loader.
4- Clone process in step 2 and enter next DLRS name + parameters.  Repeat step 3.  (Do this for all DLRS that need full recalc.)

Each update using bulk API with 2000 batch took about 10 minutes to complete updates.  Ensure automations on the object getting updated (ie, Account) are turned off to avoid timeout issues.

I like this approach b/c I can also update a small batch of records and confirm the roll-up is aggregating data correctly before performing the full calc on all records.

I hope this is helpful.  Happy to share more information if needed.

**Comment by aheber** [comment]
Thank you for sharing. Sounds like you found a good method to get the system caught up the way you wanted.

**Comment by afawcett** [comment]
Yes @vertexcs-suraj thanks so much for sharing, very cool!

**Comment by aheber** [comment]
Very interesting for the reasons of a workaround. The official recommendation, and what will be referenced in the documentation will be to use the Full Calculate features.

I love that this is hear if anyone has the same specific needs they can find a solution.
