### ISSUE TITLE
Scheduled Rollups form two different child objects to same parent throws an error

### ISSUE THREAD

**Issue by pandeygyan** [SFDO-Community/declarative-lookup-rollup-summaries#802]
Scheduled Rollups form two different child objects to same parent throws an error if:

1. Sharing Mode is same for both rollups. 
2. Relationship Field is same i.e. Relationship Field name is same from both child objects.
3. Relationship Criteria is same/null for both rollups.
4. rsfType is same for both.

Essentially, problem is coming from getContextKey method in RollupService class. Rollups from two different child objects returning same key. To fix this , I have made changes as follows and this seems to fix the problem. Do you see any problem with the fix.

    private static String getContextKey(LookupRollupSummaryWrapper lookupWrapper)
    {
        // Context Key Based On: ParentObject__c, RelationshipField__c, RelationShipCriteria__c, rsfType, SharingMode, AggergateAllRows
        // Note we do not include OrderBy here because orderby map is contained within the map of contextKeys
        String rsfType = lookupWrapper.RollupSummaryField.isAggregateBasedRollup() ? 'aggregate' : 'query';
        // Lowering case on Describable fields is only required for Legacy purposes since RollupSummary records
        // will be updated with describe names on insert/update moving forward.
        // Ideally this would not be needed to save CPU cycles but including to ensure context is properly re-used when possible for
        // rollups that have not been updated/inserted after the insert/update enhancement is applied
        // Unable to lower RelationShipCriteria__c because of field value case-(in)sensitivity configuration
        return  (lookupWrapper.Lookup.ParentObject.toLowerCase() + '#' + 
                 lookupWrapper.lookup.ChildObject.toLowerCase() + '#' +  // GP Added: 20190313 To fix bug: Scheduled Rollup form two different child to same parent throws an error. 
                 lookupWrapper.Lookup.RelationshipField.toLowerCase() + '#' + 
                 lookupWrapper.Lookup.RelationShipCriteria + '#' + 
                 rsfType + '#' + 
                 lookupWrapper.SharingMode + '#' +
                 lookupWrapper.AggregateAllRows);
    }

 
Screen shots of two rollups: 

![Rollup1](https://user-images.githubusercontent.com/48500777/54250933-be81c800-4599-11e9-9058-7161c51f44a0.png)

![Rollup2](https://user-images.githubusercontent.com/48500777/54250941-c5103f80-4599-11e9-8ea2-7d9c79406369.png)

**Comment by pandeygyan** [comment]
Screen shots of the two rollups: 

![Rollup1](https://user-images.githubusercontent.com/48500777/54250873-85495800-4599-11e9-8553-001f9a3fb19e.png)


![Rollup2](https://user-images.githubusercontent.com/48500777/54250880-8bd7cf80-4599-11e9-893d-8c4289e36e78.png)

**Comment by aheber** [comment]
@pandeygyan apparently I read the wrong part of my email first :)

Are you interested in building this as a pull requests or would you rather someone else take care of that?

**Comment by pandeygyan** [comment]
@aheber Thanks for your reply.
I have cloned the repo and have made the changes in a branch. But it does not allow me to push to your repo. The error message is:
remote: Permission to afawcett/declarative-lookup-rollup-summaries.git denied to pandeygyan.
fatal: unable to access 'https://github.com/afawcett/declarative-lookup-rollup-summaries.git/': The requested URL returned error: 403

Do I need a permission to push my branch?

**Comment by aheber** [comment]
@pandeygyan very excited you're making this pull request. I think reading through that you're trying to manipulate afawcett's repository. To do this successfully you'll want to start by forking his project (using the button on the page in GitHub). From there you can make the changes in a branch on your project and then put that to GitHub. That will update your personal copy. Once that is complete then you will want to create a Pull Request inside of GitHub from your modified branch to the master branch of afawcett's repository. From there afawcett would be able to review and accept or comment and work with you to get it in a shape that he likes it before merging into into the code base.

https://help.github.com/en/articles/creating-a-pull-request

Hope that helps.

**Comment by pandeygyan** [comment]
Hi @aheber, 

Thanks for your help. I have now created a pull request from my modified branch to the master branch of afawcett's repository.

**Comment by aheber** [comment]
Closing this. These changes were merged and included in v2.16.
