### ISSUE TITLE
Value '0' is updated on Parent Record even when no child record is present. My child record is a feedback object.Due to this even if client has not filled the feedback it appears client has rated with 0 feedback.Any help regarding this will be appreciated 

### ISSUE THREAD

**Issue by nkulkarni2021** [SFDO-Community/declarative-lookup-rollup-summaries#804]

**Comment by JimBTek** [comment]
Have you tried using a query filter to ignore records with blank fields?

**Comment by afawcett** [comment]
Hmmm i think this has been raised before, sometimes folks want it to be null, othertimes zero when their is no aggregate result. I am sure we have an enhancement to add a option to control this behavior but will flag this one for now as an enhancement and do a de-dupe later.

**Comment by aheber** [comment]
Duplicate of #161, we invite you to review the notes there and provide any input/additional criteria to help us reach an action plan.
