### ISSUE TITLE
Date field not updated after being updated the first time

### ISSUE THREAD

**Issue by tcharles12** [SFDO-Community/declarative-lookup-rollup-summaries#828]
Hi! I have three questions:

1. My DLRS worked mostly as expected the first time that the date field (Aggregate Result Field) got populated, but it did not trigger after that (or it at least did not update the date field again), after that first time. I tested this by adding more records that changed the criteria, and then more records that fit the criteria again. I tried testing both realtime calculate and scheduled calculate.

2. Is it possible to clear out the value in a date field if child records are added that pushes the DLRS to not fit the criteria anymore? Or once a date is populated, it stays there indefinitely?

3. Is it possible to set up DLRS to look at the last two consecutive records, versus just looking at the last two records that fit the criteria? My goal is to look at the last two Opportunity records off of the Contact, and roll up the most recent date of those two if those records' Stage = Closed Lost. I tried achieving this by Last and 2 rows, but it seems to just look at the last two records that fit the criteria.

![DLRS 2](https://user-images.githubusercontent.com/42197522/58685952-402ff900-8332-11e9-9819-22df676a5d01.png)

![DLRS](https://user-images.githubusercontent.com/42197522/58685759-9d777a80-8331-11e9-9c8e-8b477a8a45a3.png)

**Comment by JimBTek** [comment]
You might be able to get your SOQL query to limit 2 and sort DESC or something like that. 

If a record does not match the criteria anymore, then DLRS will not run, so it will not clear out old values.  You might need a WFR or PB to achieve that.

**Comment by aheber** [comment]
@tcharles12 if you still need help with this please let us know and we'll reopen the issue.

Without taking a longer look at it I'd probably suggest using a MAX on the ClosedDate is what you're after.

Your current configuration orders by ClosedDate (defaults to Ascending, so oldest first) but limits it to two records (the oldest two records) and takes the last value of those two records, any more records than two will not be retrieved via SOQL and will not be considered.
