### ISSUE TITLE
Suggestion: Generate Mock data , copy prod to sandbox data

### ISSUE THREAD

**Issue by cropredy** [SFDO-Community/declarative-lookup-rollup-summaries#87]
Andrew - Great tool as I was certainly getting tired of writing custom triggers to do rollups across lookup fields.  However, it creates some interesting challenges with regression testing:

Assume the following dev cycle:
1. Install package in sandbox
2. Instantiate `dlrs__LookupRollupSummary__c` through the UI
3. Deploy the custom trigger via the UI button
4. Write regression tests that depend on the parent record's rollup field having some value (new functionality is why we installed the package in the first place)

It is at step 4 where the developer, presuming one wants to avoid `@isTest(SeeAllData=true)`, has to mock out the values in `dlrs__LookupRollupSummary__c`.

So, **Suggestion#1** would be to provide another button in the tool that would generate the data in a form suitable for inclusion in `Test.loadData(somestaticResource)`  This becomes even more important as you add fields and functionality.

Continuing the dev cycle...
1. Install package in PROD
2. Populate PROD records of  `dlrs__LookupRollupSummary__c`; 
3. Deploy any dev-created code plus the generated trigger; SFDC runs all tests and hence mocked data needed

and ...
1. Refresh dev sandbox (we tend to refresh dev sandboxes every quarter from PROD)
2. Uh-oh, `dlrs__LookupRollupSummary__c` has to be built all over again for any UI testing in the dev sandbox.

**Suggestion#2**: Provide a button that allows auto-copy of rows from one org to another via REST API so the reinstantiation of data rows from PROD to sandbox is painless and error-free.

**Summary** - In essence, SObject values are being used for metadata but they aren't really SFDC metadata and hence require copying/management/mocking.

Obviously easy for me to propose and not so easy for you to dispose so I'm certainly understanding.

**Comment by aheber** [comment]
Closing this, I believe the needed functionality has been available for a long time now that DLRS uses Custom Metadata Records for the configuration and if needed supports custom Test method definitions to enable mocking records for successful test execution.
