### ISSUE TITLE
Default DLRS CustomObjects to externalSharingModel Private

### ISSUE THREAD

**Issue by cropredyHelix** [SFDO-Community/declarative-lookup-rollup-summaries#898]
SFDC Health Check flags as "Critical" any Custom Object with External Sharing other than Private. 

![Screen Shot 2020-01-06 at 1 46 22 PM](https://user-images.githubusercontent.com/25649155/71851284-0de63700-308b-11ea-869c-333e0794778e.png)

For DLRS, this includes:

- Lookup Child Big 
- Lookup Parent
- Lookup Rollup Calculate Job
- Lookup Rollup Summary
- Lookup Rollup Summary Log

DLRS install makes the external sharing model = Public Read/Write

![Screen Shot 2020-01-06 at 1 43 00 PM](https://user-images.githubusercontent.com/25649155/71851116-a8924600-308a-11ea-82d5-410ec4326c92.png)

but should be Private as per:

    <externalSharingModel>Private</externalSharingModel>

in the CustomObject metadata

This avoids the SFDC Health Check "Critical" issue for objects under DLRS control

**Comment by chininchu** [comment]
Fixed: Salesforce by default now sets all DLRS objects to Private for **Default External Access**, resolving the security Health Check warning.
