### ISSUE TITLE
Use SOQL Formulas in 'Field to Aggregate' and 'Aggregate Result Field'

### ISSUE THREAD

**Issue by krysolov** [SFDO-Community/declarative-lookup-rollup-summaries#899]
Would be great to be able to specify a formula to aggregate a calculation. Current workaround is to create formula work fields on the child object. That in turn gets aggregated via DLRS. And if some formula is necessary for the result field, then again the result gets output into a work field and a formula is applied to that to be displayed on the page. 
If formulas are allowed in both Field to Aggregate and Aggregate Result Field, then this would be solved right within the tool. So if I (hypothetically) need to find the max value of Field_A__c * Field_B__c and then apply, dunno, some percentage calculation to the result, I would avoid all the extra steps to create and document work fields.

**Comment by aheber** [comment]
Unfortunately I don't think SOQL supports calculations. If you have a more detailed example of a SOQL query that runs and what you'd like to achieve we can figure out how to get it added to the tooling.

SOQL does have some limited functions but not mathematical calculation. I believe there is already an open issue to see if we can support the existing SOQL functions.
