### ISSUE TITLE
How to address helpText not rendering for <apex:pageBlockSectionItem> in Lightning?

### ISSUE THREAD

**Issue by tet3** [SFDO-Community/declarative-lookup-rollup-summaries#903]
**Describe the bug**
This is 100% an upstream bug - the `helpText` attribute of `<apex:pageBlockSectionItem>` [doesn't render in Lightning Experience](https://success.salesforce.com/ideaView?id=0873A000000CZqhQAG). The DLRS Visualforce pages make extensive use of this attribute, and it's a big loss for new users in Lightning not to see it. 

**To Reproduce**
1. Switch to Salesforce Classic , if not already in Classic.
2. Open the Declarative Lookup Rollup Summaries app, and go to the Manage Lookup Rollup Summaries tab.  
3. Observe that almost all fields have a help text bubble with useful text displayed on mouse-over.
3. Switch to Lightning Experience, and return to the Manage Lookup Rollup Summaries tab.
4. Observe that there are no field help bubbles displayed for any fields. 

**Expected behavior**
Field help is displayed for fields on Visualforce pages for users in Lightning Experience as well as  Classic.

**Comment by tet3** [comment]
I can't assign the "discussion" tag myself, so if someone else can, that would be great.

I was thinking of some ways to address this, which have varying levels of effort:
1. Build and package a Lightning app as well as the Classic app, but build and use new Lightning components instead of the current VF pages. LOE: high
2. Build new Lightning components and expose them through Lightning Out in the current VF page. LOE: Almost as high, and makes for a jarring UI change for Classic users. 
3. Use conditional rendering in Visualforce, based on [`{$User.UIThemeDisplayed}`](https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_variables_global_useruitheme.htm) to change the display in Lightning:
  a. render a different `<apex:outputLabel>` with a `title` attribute of the field help. The text would then show on mouseover but wouldn't have any UI hint that it's there.
  b. render a 2-column `<apex:pageBlockSection>` with all the field help in it for a given section.
LOE: easiest, but if/when the bug gets fixed, then a new release of DLRS would be required to go back to a single fieldHelp solution. 

Thoughts? I'm up for building and submitting a PR for some version of option 3.

**Comment by afawcett** [comment]
@tet3  thanks for raising.

**Comment by afawcett** [comment]
@tet3 none are ideal tbh.... i wonder if just rendering a simple bullet list with the descriptions at the bottom of the page would be cheaper. Not as visual for sure. But as you say we really need the platform to fix this and not incur debt by working around it.

**Comment by tet3** [comment]
I though that an option in between a list at the bottom and per-field conditional rendering might be a help section per existing `pageBlockSection`, and so I'm [working on that](https://github.com/tet3/declarative-lookup-rollup-summaries/tree/feature/fieldhelpbblock), using a VF component that takes a list of fields and produces a pageBlockTable of their Labels and inlineHelpText. Here's [a screenshot](https://tet3nas.myqnapcloud.com/share.cgi/2020-04-06-Manage%20Lookup%20Rollup%20Summaries%20_%20Salesforce-33.png?ssid=0g3wEAE&fid=0g3wEAE&open=normal&ep=). 

Does that seem like a good compromise at first glance? There are some other implied compromises, though... 😁

I'd like the help sections to be collabsible **and** collapsed on initial page load. The problem with  `<apex:pageBlockSection collapsible="true">` is that [it doesn't open/close when inside of an `<apex:pageBlock mode="edit"`>]( https://salesforce.stackexchange.com/questions/11513/apexpageblocksectionitem-collaspe-or-expand-throws-twistsection-is-not-defined), and the workaround listed there, of tricking the platform into providing the `twistSection()` function with an unrendered PB or PBS doesn't seem to work anymore. So the linked screenshot uses `mode="detail"` for the pageBlock, and sets all the other pageBlockSections to `collapsible=false` to override the default for that mode. In Lightning the only other difference is that there's no legend for the red "required" asterisk at the left end of the first section's header. In Classic, the styling is a little bit more different, but not radically so. 

And even then, closing the sections by default requires using [officially provided, but "as is" JavaScript](https://help.salesforce.com/articleView?id=000332075&type=1&mode=1) to make the sections close on page load. I haven't implemented that yet. It'll need adjusting from what's at the link to find all the relevant sections and close each of them.  

Let me know if this looks like a good direction, @afawcett

**Comment by afawcett** [comment]
@tet3 love it! Thank you for this fine work. With more growing users usability is key.

**Comment by aheber** [comment]
This should be improved/resolved with the new LWC wizard in v2.21.
