### ISSUE TITLE
New and Could Use a Little Help on first DLRS

### ISSUE THREAD

**Issue by jcontre52408** [SFDO-Community/declarative-lookup-rollup-summaries#904]
Hello! 

I am new to using DLRS and am having issues deploying my first rollup. To summarize:

1. I created a field on a custom object that is used to summarize a value from a child object. In this case I created a field called Total PO Value on the SCMC Sales Order Object. 

2. I want to have the DLRS look at this field and aggregate the value of this field on all sales orders on the opportunity. The "parent" is Opportunity and the child is "sales orders" 

3. When I deploy I receive the following issues (see screen shots). Screen shot 1 is what's in DLRS and SS2 is the result.

I believe this is saying I'm running into code coverage problems but I don't understand the messages in Red indicating a null value. 

Any help would be greatly appreciated.

THANKS!!!! 
[DLRS SS.docx](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/4151105/DLRS.SS.docx)

**Comment by afawcett** [comment]
@jcontre52408 I am sorry but I don't have Word to open your file. Can you paste here?

**Comment by aheber** [comment]
I'm going to mark this as closed. Our preferred channel for support is the Trailblazer Community Group for DLRS. There are many fantastic individuals there that are able to help out.
