### ISSUE TITLE
Calculate Roll up Summary not running

### ISSUE THREAD

**Issue by mickbroberts** [SFDO-Community/declarative-lookup-rollup-summaries#922]
I created a roll up summary which works OK.
I scheduled it to calculate overnight at 2pm, but this failed as my selection criteria were incorrect.
I tried running the calculate this morning , but got the message
Error:
A calculate job for rollup 'Calculculate most recent case note' is already executing. If you suspect it is not aleady running try clearing the applicable record from the Lookup Rollup Calculate Jobs tab and try again.

I checked the Lookup Summary Roll Up Logs - nothing there.  I checked the Apex job logs and the job had failed with this message , so there was no batch job running

- "First error: No such column 'Active__c' on entity 'eCASS02t1__Referral__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names"

**Comment by afawcett** [comment]
@mickbroberts did you try _"try clearing the applicable record from the **Lookup Rollup Calculate Jobs** tab and try again"_

**Comment by mickbroberts** [comment]
There is nothing in the lookup rollup calculat jobs
![Issue with DCLR](https://user-images.githubusercontent.com/29703225/78531656-bf594d80-77dd-11ea-9f3c-d8f94452f571.png)

**Comment by afawcett** [comment]
@mickbroberts that is the wrong object please check "Lookup Rollup Calculate Jobs"
