### ISSUE TITLE
RollupJob failing with error Invalid field

### ISSUE THREAD

**Issue by afawcett** [SFDO-Community/declarative-lookup-rollup-summaries#926]
**Describe the bug**
RollupJob failing with error ```First error:
Name, dlrs__LookupRollupSummary2__c, dlrs__LookupRollupSummary__c
^
ERROR at Row:1:Column:39
Invalid field: 'Amount'``` 

**To Reproduce**
Create Custom Metadata based rollup:
Parent: Account
Child: Opportunity
Field to Aggregate: Amount
Field to Store Result: AnnualRevenue
Aggregation Type: Sum
Calculation Mode: Scheduled

Create Custom Object based rollup:
Parent: Account
Child: Contact
Field to Aggregate: Id
Field to Store Result: NumberOfEmployees
Aggregation Type: Count
Calculation Mode; Scheduled

Add a Opportunity and Contact record.

**Expected behavior**
It calculates the rollups as expected.

**Screenshots**
Not needed.

**Additional context**
- Found this while testing latest release, tested in v2.11.
- Not sure if this is due to mixing Custom Object and Custom Metadata types or not.

**Comment by afawcett** [comment]
I have a hunch, based on this https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/679 that this error will occur on realtime rollups as well.

**Comment by aheber** [comment]
I'm unable to replicate now. Considering this resolved as a result of #1038. Shipped in v2.16
