### ISSUE TITLE
Failed to process batch for class 'dlrs.RollupCalculateJob' for job id 'XXXXXXX00C09xiA'

### ISSUE THREAD

**Issue by kumarjiv** [SFDO-Community/declarative-lookup-rollup-summaries#933]
Hello Andy,
I am also getting this error
Apex script unhandled exception by user/organization: (Organisation ID)

Failed to process batch for class 'dlrs.RollupCalculateJob' for job id '7070X0000C09xiA'
Could you please help me.
Thanks

**Comment by afawcett** [comment]
@ashwinjangam i need more information. Do you see anything on Setup > Apex Jobs?

**Comment by aheber** [comment]
Closing, if further help is needed please reach out to the Trailblazer Community Group for DLRS which is our preferred channel for support requests.
