### ISSUE TITLE
Sort in descending order? (for concatenating)

### ISSUE THREAD

**Issue by samlimster** [SFDO-Community/declarative-lookup-rollup-summaries#948]
Hi folks.

Is there a way to sort the results in descending order?  I need to be able to concatenate a list records sorted by date from newest to oldest.  However, it appears that it's sorting from oldest to newest.

Thanks!

**Comment by afawcett** [comment]
Yes please see the field "Field to Order By" on the rollup definition - that should do what you want. 👍

**Comment by samlimster** [comment]
Hi @afawcett Thanks for getting back to me.  Yes, I select "Field to Order By", but is there a way to change the direction of the sort?  i.e. it always sorts from oldest to newest, but I need it to sort the other way around.

Thank you.

**Comment by afawcett** [comment]
Yes you can use the syntax described here https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_orderby.htm

**Comment by IdealSalesforce20Bedford** [comment]
How do you use the syntax, I have a similar issue in which I need the data to sort new to old, I understand DESC and ASC are the terms to use, how do I use that with Field to Order By on the Lookup Rollup Summary page?

**Comment by aheber** [comment]
Adding in some detail before closing this.

Field to Order By with a value like `CreatedDate DESC` would be what you'll want.

If that doesn't resolve your concerns please reach out to the Trailblazer Community Group from DLRS for additional help.
