### ISSUE TITLE
Typo on Welcome tab after Install in SB

### ISSUE THREAD

**Issue by JayKilian** [SFDO-Community/declarative-lookup-rollup-summaries#949]
![image](https://user-images.githubusercontent.com/18370582/84538448-87232f00-aca6-11ea-8daa-3ea088e085cd.png)

**Comment by aheber** [comment]
I believe this has been fixed.
https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/blob/main/dlrs/main/pages/welcome.page#L69
