### ISSUE TITLE
Documentation Update for Concatenate

### ISSUE THREAD

**Issue by JayKilian** [SFDO-Community/declarative-lookup-rollup-summaries#950]
Not sure it's a typo or not, but in the description for the Concatenate operation in DLRS it states that it only works on Text fields, yet it also works on Picklist fields (I just did this and was surprised it works). This is a FR to update the documentation.

![image](https://user-images.githubusercontent.com/18370582/84546123-6dd5af00-acb5-11ea-9b26-fa03c3532354.png)

**Comment by afawcett** [comment]
@JayKilian  thanks for this - piklists are text fields basically - so this makes sense - however i am not familar with the doc you mention - do you have a link?

**Comment by aheber** [comment]
This project has gone through some changes over the last few years. Documentation now lives here: https://github.com/SFDO-Community-Sprints/DLRS-Documentation

If you'd like to make improvements then we'd love to have you adding in some support there in the form of feature requests or even better, directly PR contribution.
