### ISSUE TITLE
Missing Buttons "Schedule & Trigger" after installing

### ISSUE THREAD

**Issue by StefanWeirauch** [SFDO-Community/declarative-lookup-rollup-summaries#988]
**Describe the bug**
I'm missing the Buttons for Running Full Calculate, Scheduling and Manage Child Trigger after the initial installation.
Therefore i can't create a new Lookup Rollup Summary.

However i was able to work around this by adding the Lookup Rollup Summary via adding Custom Metadata. After that the Buttons did appear within the App and i was able to deploy the Trigger and add a Scheduling.

![image](https://user-images.githubusercontent.com/22793329/95728566-f07a7500-0c7b-11eb-9071-2b8342a3d10f.png)

**Comment by paweitzmann** [comment]
I also had this issue, and Stefan's workaround help me, too. Thanks, Stefan!

**Comment by aheber** [comment]
This is very odd, is anyone able to add details or still experiencing this issue? Is it possible that the record wasn't saved yet? It must be successfully saved at least once to enable the buttons for calculation.

I know this is a bit down the road but hopefully if there is a consistent problem here we can still get it resolved.

**Comment by aheber** [comment]
I'm going to close due to inactivity. Going forward, v2.21 introduces a new LWC based configuration editor that shouldn't have the same problems.
