### ISSUE TITLE
More informative name for "Aggregate All Rows" option

### ISSUE THREAD

**Issue by mnort9** [SFDO-Community/declarative-lookup-rollup-summaries#997]
It may be helpful for "Aggregate All Rows" to describe better that recycled/archived items will be included in the rollup. I made the assumption this option just meant a LIMIT won't be applied to the query. After doing a mass delete of records and re-calculating a rolloup field, I got pretty stuck on the rollup producing a result based on deleted records. It could just be me, but I think it could be more obvious in the description, maybe something like "Aggregate All Rows (including recycled/archived records)".

**Comment by aheber** [comment]
This would be an awesome improvement for our documentation. We'd love to have your contributions on our newer documentation repository.
https://github.com/SFDO-Community-Sprints/DLRS-Documentation

**Comment by aheber** [comment]
This should be improved in the new LWC wizard released as part of v2.21.
